//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM_HEADER
    {
        public decimal INTERNAL_NUM { get; set; }
        public string COMPANY { get; set; }
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public decimal REVISION_NUM { get; set; }
        public string BUILD_INSTRUCTIONS { get; set; }
        public string QUANTITY_UM { get; set; }
        public string ACTIVE { get; set; }
        public string BUILD_LOC { get; set; }
        public Nullable<System.DateTime> VALID_FROM_DATE { get; set; }
        public Nullable<System.DateTime> VALID_END_DATE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
        public string PROCESS_STAMP { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
        public string LAST_MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
    }
}
