//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAINER_TYPE
    {
        public decimal INTERNAL_NUM { get; set; }
        public string CONTAINER_TYPE1 { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTAINER_CLASS { get; set; }
        public string CONTAINER_GROUP { get; set; }
        public Nullable<decimal> SEQUENCE { get; set; }
        public Nullable<decimal> EMPTY_WEIGHT { get; set; }
        public string WEIGHT_UM { get; set; }
        public Nullable<decimal> LENGTH { get; set; }
        public Nullable<decimal> WIDTH { get; set; }
        public Nullable<decimal> HEIGHT { get; set; }
        public string DIMENSION_UM { get; set; }
        public Nullable<decimal> MAXIMUM_WEIGHT { get; set; }
        public Nullable<decimal> WEIGHT_TOLERANCE { get; set; }
        public Nullable<decimal> FILL_PERCENT { get; set; }
        public string USE_AS_DEFAULT { get; set; }
        public string RATING_SYMBOL { get; set; }
        public string ACTIVE { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
    }
}
