//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCLE_COUNT_PREFERENCE
    {
        public decimal INTERNAL_PREFERENCE_NUM { get; set; }
        public string PREFERENCE_ID { get; set; }
        public string PREFERENCE_NAME { get; set; }
        public string PROMPT_LOCATION { get; set; }
        public string PROMPT_LPN { get; set; }
        public string PROMPT_ITEM { get; set; }
        public string PROMPT_QUANTITY { get; set; }
        public string COUNT_INVENTORY_STS { get; set; }
        public string ALLOW_ADD_NEW_INVENTORY { get; set; }
        public string ACTIVE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
        public string LAST_MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public Nullable<decimal> USER_DEF7 { get; set; }
        public Nullable<decimal> USER_DEF8 { get; set; }
    }
}
