//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCLE_COUNT_DETAIL
    {
        public decimal INTERNAL_COUNT_NUM { get; set; }
        public decimal INTERNAL_CYCLE_COUNT_NUM { get; set; }
        public Nullable<decimal> ROUND { get; set; }
        public Nullable<decimal> GROUP_NUM { get; set; }
        public Nullable<decimal> GROUP_INDEX { get; set; }
        public string WAREHOUSE { get; set; }
        public string LOCATION { get; set; }
        public string PARENT_LPN { get; set; }
        public string LPN { get; set; }
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public string COMPANY { get; set; }
        public string INVENTORY_STS { get; set; }
        public Nullable<decimal> SYSTEM_QTY { get; set; }
        public Nullable<decimal> COUNTED_QTY { get; set; }
        public string QUANTITY_UM { get; set; }
        public Nullable<decimal> ATTRIBUTE_NUM { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string COUNT_ATTRIBUTE { get; set; }
        public Nullable<System.DateTime> COUNTED_DATE_TIME { get; set; }
        public string COUNTED_BY_USER { get; set; }
        public string ASSIGNED_USER { get; set; }
        public Nullable<System.DateTime> ASSIGNED_DATE_TIME { get; set; }
        public string COMPLETED_USER { get; set; }
        public Nullable<System.DateTime> COMPLETED_DATE_TIME { get; set; }
        public string CONDITION { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
        public string LAST_MODIFIED_USER { get; set; }
        public Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
    }
}
