//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERFACE_PROCESS
    {
        public decimal INTERNAL_NUM { get; set; }
        public string DESCRIPTION { get; set; }
        public string INTERFACE_TYPE { get; set; }
        public string DIRECTION { get; set; }
        public string INTERFACE_MODE { get; set; }
        public string PRE_INTERFACE_ACTION { get; set; }
        public string POST_INTERFACE_ACTION { get; set; }
        public string INTERFACE_ACTION { get; set; }
        public string SAVE_DATA { get; set; }
        public Nullable<decimal> TRANSACTION_SIZE { get; set; }
        public string ACTIVE { get; set; }
        public string IN_PROCESS { get; set; }
        public Nullable<System.DateTime> LAST_RUN_TIME { get; set; }
        public Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
        public string USER_STAMP { get; set; }
        public string LAST_RUN_RESULT { get; set; }
    }
}
