//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_LOCATION_CAPACITY
    {
        public string WAREHOUSE { get; set; }
        public decimal INTERNAL_ITEM_CAPACITY_NUM { get; set; }
        public string COMPANY { get; set; }
        public string ITEM { get; set; }
        public string ITEM_CLASS { get; set; }
        public string LOCATION { get; set; }
        public string LOCATION_TYPE { get; set; }
        public Nullable<decimal> MAXIMUM_QTY { get; set; }
        public string QUANTITY_UM { get; set; }
        public Nullable<decimal> MINIMUM_RPLN_PCT { get; set; }
        public string USER_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
    
        public virtual COMPANY COMPANY1 { get; set; }
    }
}
