//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKING_CLASS
    {
        public decimal INTERNAL_NUM { get; set; }
        public string PACKING_CLASS1 { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONTAINER_GROUP { get; set; }
        public string USER_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
    }
}
