//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPLENISHMENT_REQUEST
    {
        public decimal INTERNAL_RPLN_REQ_NUM { get; set; }
        public string COMPANY { get; set; }
        public string WAREHOUSE { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public decimal ALLOCATED_QTY { get; set; }
        public string QUANTITY_UM { get; set; }
        public Nullable<decimal> ATTRIBUTE_NUM { get; set; }
        public string ALLOCATION_ZONE { get; set; }
        public Nullable<decimal> INTERNAL_WAVE_NUM { get; set; }
        public string USER_STAMP { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public Nullable<decimal> CONVERTED_ALLOC_QTY { get; set; }
        public string CONVERTED_QTY_UM { get; set; }
        public string FROM_LOC { get; set; }
        public string TO_LOC { get; set; }
        public string FROM_TEMPL_FIELD1 { get; set; }
        public string FROM_TEMPL_FIELD2 { get; set; }
        public string FROM_TEMPL_FIELD3 { get; set; }
        public string FROM_TEMPL_FIELD4 { get; set; }
        public string FROM_TEMPL_FIELD5 { get; set; }
        public string TO_TEMPL_FIELD1 { get; set; }
        public string TO_TEMPL_FIELD2 { get; set; }
        public string TO_TEMPL_FIELD3 { get; set; }
        public string TO_TEMPL_FIELD4 { get; set; }
        public string TO_TEMPL_FIELD5 { get; set; }
        public string TASK_CREATED { get; set; }
        public string FROM_ZONE { get; set; }
        public string FROM_LPN { get; set; }
        public string FROM_PARENT_LPN { get; set; }
        public string TO_ZONE { get; set; }
        public string TO_LPN { get; set; }
        public string TO_PARENT_LPN { get; set; }
        public string REPLENISHMENT_TYPE { get; set; }
        public string INVENTORY_STS { get; set; }
    
        public virtual COMPANY COMPANY1 { get; set; }
        public virtual WAREHOUSE WAREHOUSE1 { get; set; }
    }
}
