//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_SERIAL_NUMBER
    {
        public int ID { get; set; }
        public string SHIPMENT_ID { get; set; }
        public string TRACKING_NUMBER { get; set; }
        public string ITEM { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public Nullable<decimal> INTERNAL_SHIPMENT_NUM { get; set; }
        public System.DateTime DATE_TIME_STAMP { get; set; }
        public string CARRIER { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
        public string USER_DEF9 { get; set; }
    }
}
