//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_FLOW_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUS_FLOW_HEADER()
        {
            this.STATUS_FLOW_DETAIL = new HashSet<STATUS_FLOW_DETAIL>();
        }
    
        public decimal INTERNAL_NUM { get; set; }
        public string STATUS_FLOW { get; set; }
        public string STATUS_FLOW_NAME { get; set; }
        public string STATUS_FLOW_TYPE { get; set; }
        public string ACTIVE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_TIME { get; set; }
        public string LAST_MODIFY_USER { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE_TIME { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATUS_FLOW_DETAIL> STATUS_FLOW_DETAIL { get; set; }
    }
}
