//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_ORDER_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORK_ORDER_HEADER()
        {
            this.WORK_ORDER_DETAIL = new HashSet<WORK_ORDER_DETAIL>();
        }
    
        public decimal INTERNAL_NUM { get; set; }
        public string WAREHOUSE { get; set; }
        public string COMPANY { get; set; }
        public string ITEM { get; set; }
        public string ITEM_DESC { get; set; }
        public Nullable<decimal> REVISION_NUM { get; set; }
        public string WORK_ORDER_ID { get; set; }
        public string BUILD_LOC { get; set; }
        public decimal TOTAL_QTY { get; set; }
        public Nullable<decimal> OPEN_QTY { get; set; }
        public Nullable<decimal> BUILT_QTY { get; set; }
        public string QTY_UM { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public System.DateTime CREATED_DATE_TIME { get; set; }
        public Nullable<System.DateTime> RELEASED_DATE_TIME { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE_TIME { get; set; }
        public Nullable<System.DateTime> PLANNED_UNIT_BUILD_TIME { get; set; }
        public string MANUALLY_ENTERED { get; set; }
        public string BUILD_INSTRUCTIONS { get; set; }
        public string USER_DEF1 { get; set; }
        public string USER_DEF2 { get; set; }
        public string USER_DEF3 { get; set; }
        public string USER_DEF4 { get; set; }
        public string USER_DEF5 { get; set; }
        public string USER_DEF6 { get; set; }
        public string USER_DEF7 { get; set; }
        public string USER_DEF8 { get; set; }
        public string USER_STAMP { get; set; }
        public string PROCESS_STAMP { get; set; }
        public System.DateTime LAST_MODIFIED_DATE_TIME { get; set; }
        public string IN_ALLOCATION { get; set; }
        public string CONDITION { get; set; }
        public string ALLOC_ATTEMPTED { get; set; }
        public string IN_CONFIRMATION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORK_ORDER_DETAIL> WORK_ORDER_DETAIL { get; set; }
    }
}
