//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class APPOINTMENT
	{
		public Apps.Models.SCV.Sys.APPOINTMENT_MODEL ToPOCO(){
			return new Apps.Models.SCV.Sys.APPOINTMENT_MODEL(){
								INTERNAL_APPOINT_NUM=this.INTERNAL_APPOINT_NUM,
				INTERNAL_RECEIPT_NUM=this.INTERNAL_RECEIPT_NUM,
				DOCK=this.DOCK,
				START_DATE_TIME=this.START_DATE_TIME,
				END_DATE_TIME=this.END_DATE_TIME,
				STATUS=this.STATUS,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
			};
		}
	}
}
