//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class CYCLE_COUNT_PREFERENCE
	{
		public Apps.Models.SCV.CYCLE.CYCLE_COUNT_PREFERENCE_MODEL ToPOCO(){
			return new Apps.Models.SCV.CYCLE.CYCLE_COUNT_PREFERENCE_MODEL(){
								INTERNAL_PREFERENCE_NUM=this.INTERNAL_PREFERENCE_NUM,
				PREFERENCE_ID=this.PREFERENCE_ID,
				PREFERENCE_NAME=this.PREFERENCE_NAME,
				PROMPT_LOCATION=this.PROMPT_LOCATION,
				PROMPT_LPN=this.PROMPT_LPN,
				PROMPT_ITEM=this.PROMPT_ITEM,
				PROMPT_QUANTITY=this.PROMPT_QUANTITY,
				COUNT_INVENTORY_STS=this.COUNT_INVENTORY_STS,
				ALLOW_ADD_NEW_INVENTORY=this.ALLOW_ADD_NEW_INVENTORY,
				ACTIVE=this.ACTIVE,
				CREATED_USER=this.CREATED_USER,
				CREATED_DATE_TIME=this.CREATED_DATE_TIME,
				LAST_MODIFIED_USER=this.LAST_MODIFIED_USER,
				LAST_MODIFIED_DATE_TIME=this.LAST_MODIFIED_DATE_TIME,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
			};
		}
	}
}
