//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class CYCLE_COUNT_HEADER
	{
		public Apps.Models.SCV.CYCLE.CYCLE_COUNT_HEADER_MODEL ToPOCO(){
			return new Apps.Models.SCV.CYCLE.CYCLE_COUNT_HEADER_MODEL(){
								INTERNAL_CYCLE_COUNT_NUM=this.INTERNAL_CYCLE_COUNT_NUM,
				ORIGINAL_CYCLE_COUNT_NUM=this.ORIGINAL_CYCLE_COUNT_NUM,
				ROUND=this.ROUND,
				MASTER_ID=this.MASTER_ID,
				COUNT_TYPE=this.COUNT_TYPE,
				CONDITION=this.CONDITION,
				COUNT_ATTRIBUTE=this.COUNT_ATTRIBUTE,
				REFERENCE_ID=this.REFERENCE_ID,
				REMARK=this.REMARK,
				TOTAL_LOCS=this.TOTAL_LOCS,
				TOTAL_ITEMS=this.TOTAL_ITEMS,
				INVENTORY_STSES=this.INVENTORY_STSES,
				ITEMS=this.ITEMS,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
				CREATED_USER=this.CREATED_USER,
				CREATED_DATE_TIME=this.CREATED_DATE_TIME,
				RELEASED_USER=this.RELEASED_USER,
				RELEASED_DATE_TIME=this.RELEASED_DATE_TIME,
				CLOSED_USER=this.CLOSED_USER,
				CLOSED_DATE_TIME=this.CLOSED_DATE_TIME,
				LAST_MODIFIED_USER=this.LAST_MODIFIED_USER,
				LAST_MODIFIED_DATE_TIME=this.LAST_MODIFIED_DATE_TIME,
			};
		}
	}
}
