//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class DOWNLOAD_ITEMS
	{
		public Apps.Models.SCV.DOWNLOAD.DOWNLOAD_ITEMS_MODEL ToPOCO(){
			return new Apps.Models.SCV.DOWNLOAD.DOWNLOAD_ITEMS_MODEL(){
								INTERFACE_RECORD_ID=this.INTERFACE_RECORD_ID,
				INTERFACE_ACTION_CODE=this.INTERFACE_ACTION_CODE,
				INTERFACE_CONDITION=this.INTERFACE_CONDITION,
				PROCESS_STAMP=this.PROCESS_STAMP,
				COMPANY=this.COMPANY,
				ITEM=this.ITEM,
				ITEM_DESC=this.ITEM_DESC,
				ATTRIBUTE_TRACK=this.ATTRIBUTE_TRACK,
				ITEM_STYLE=this.ITEM_STYLE,
				DEPARTMENT=this.DEPARTMENT,
				ITEM_CATEGORY1=this.ITEM_CATEGORY1,
				ITEM_CATEGORY2=this.ITEM_CATEGORY2,
				ITEM_CATEGORY3=this.ITEM_CATEGORY3,
				ITEM_CATEGORY4=this.ITEM_CATEGORY4,
				ITEM_CATEGORY5=this.ITEM_CATEGORY5,
				ITEM_CATEGORY6=this.ITEM_CATEGORY6,
				ITEM_CATEGORY7=this.ITEM_CATEGORY7,
				ITEM_CATEGORY8=this.ITEM_CATEGORY8,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
			};
		}
	}
}
