//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class ITEM_ZONE_CAPACITY
	{
		public Apps.Models.SCV.ITEM.ITEM_ZONE_CAPACITY_MODEL ToPOCO(){
			return new Apps.Models.SCV.ITEM.ITEM_ZONE_CAPACITY_MODEL(){
								INTERNAL_ITEM_ZONE_NUM=this.INTERNAL_ITEM_ZONE_NUM,
				COMPANY=this.COMPANY,
				ITEM=this.ITEM,
				LOCATION_SEL=this.LOCATION_SEL,
				MAXIMUM_QTY=this.MAXIMUM_QTY,
				MINIMUM_QTY=this.MINIMUM_QTY,
				QUANTITY_UM=this.QUANTITY_UM,
				MINIMUM_RPLN_PCT=this.MINIMUM_RPLN_PCT,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
			};
		}
	}
}
