//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class ITEM_UNIT_OF_MEASURE
	{
		public Apps.Models.SCV.ITEM.ITEM_UNIT_OF_MEASURE_MODEL ToPOCO(){
			return new Apps.Models.SCV.ITEM.ITEM_UNIT_OF_MEASURE_MODEL(){
								INTERNAL_ITEM_UM=this.INTERNAL_ITEM_UM,
				ITEM=this.ITEM,
				COMPANY=this.COMPANY,
				SEQUENCE=this.SEQUENCE,
				QUANTITY_UM=this.QUANTITY_UM,
				CONVERSION_QTY=this.CONVERSION_QTY,
				LENGTH=this.LENGTH,
				WIDTH=this.WIDTH,
				HEIGHT=this.HEIGHT,
				DIMENSION_UM=this.DIMENSION_UM,
				WEIGHT=this.WEIGHT,
				WEIGHT_UM=this.WEIGHT_UM,
				USER_STAMP=this.USER_STAMP,
				PROCESS_STAMP=this.PROCESS_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
				TREAT_FULL_PCT=this.TREAT_FULL_PCT,
				MOVEMENT_CLS=this.MOVEMENT_CLS,
				ITEM_CLASS=this.ITEM_CLASS,
				TREAT_AS_LOOSE=this.TREAT_AS_LOOSE,
				GROUP_DURING_CHECKIN=this.GROUP_DURING_CHECKIN,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
			};
		}
	}
}
