//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class PURCHASE_ORDER_HEADER
	{
		public Apps.Models.SCV.PURCHASE.PURCHASE_ORDER_HEADER_MODEL ToPOCO(){
			return new Apps.Models.SCV.PURCHASE.PURCHASE_ORDER_HEADER_MODEL(){
								INTERNAL_PURCHASE_ORDER_NUM=this.INTERNAL_PURCHASE_ORDER_NUM,
				WAREHOUSE=this.WAREHOUSE,
				COMPANY=this.COMPANY,
				PURCHASE_ORDER_ID=this.PURCHASE_ORDER_ID,
				PURCHASE_ORDER_TYPE=this.PURCHASE_ORDER_TYPE,
				CLOSE_DATE=this.CLOSE_DATE,
				PRIORITY=this.PRIORITY,
				STATUS=this.STATUS,
				ERP_ORDER_ID=this.ERP_ORDER_ID,
				SHIP_FROM=this.SHIP_FROM,
				SHIP_FROM_ADDRESS1=this.SHIP_FROM_ADDRESS1,
				SHIP_FROM_ADDRESS2=this.SHIP_FROM_ADDRESS2,
				SHIP_FROM_CITY=this.SHIP_FROM_CITY,
				SHIP_FROM_STATE=this.SHIP_FROM_STATE,
				SHIP_FROM_COUNTRY=this.SHIP_FROM_COUNTRY,
				SHIP_FROM_POSTAL_CODE=this.SHIP_FROM_POSTAL_CODE,
				SHIP_FROM_NAME=this.SHIP_FROM_NAME,
				SHIP_FROM_ATTENTION_TO=this.SHIP_FROM_ATTENTION_TO,
				SHIP_FROM_EMAIL_ADDRESS=this.SHIP_FROM_EMAIL_ADDRESS,
				SHIP_FROM_PHONE_NUM=this.SHIP_FROM_PHONE_NUM,
				SHIP_FROM_FAX_NUM=this.SHIP_FROM_FAX_NUM,
				SCHEDULED_ARRIVE_DATE=this.SCHEDULED_ARRIVE_DATE,
				ACTUAL_ARRIVE_DATE=this.ACTUAL_ARRIVE_DATE,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
			};
		}
	}
}
