//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class PURCHASE_ORDER_DETAIL
	{
		public Apps.Models.SCV.PURCHASE.PURCHASE_ORDER_DETAIL_MODEL ToPOCO(){
			return new Apps.Models.SCV.PURCHASE.PURCHASE_ORDER_DETAIL_MODEL(){
								INTERNAL_PURCHASE_ORDER_LINE_NUM=this.INTERNAL_PURCHASE_ORDER_LINE_NUM,
				INTERNAL_PURCHASE_ORDER_NUM=this.INTERNAL_PURCHASE_ORDER_NUM,
				PURCHASE_ORDER_ID=this.PURCHASE_ORDER_ID,
				WAREHOUSE=this.WAREHOUSE,
				COMPANY=this.COMPANY,
				ITEM=this.ITEM,
				ITEM_DESC=this.ITEM_DESC,
				ITEM_CLASS=this.ITEM_CLASS,
				ATTRIBUTE_TRACK=this.ATTRIBUTE_TRACK,
				ATTRIBUTE_NUM=this.ATTRIBUTE_NUM,
				ATTRIBUTE1=this.ATTRIBUTE1,
				ATTRIBUTE2=this.ATTRIBUTE2,
				ATTRIBUTE3=this.ATTRIBUTE3,
				ATTRIBUTE4=this.ATTRIBUTE4,
				ATTRIBUTE5=this.ATTRIBUTE5,
				ATTRIBUTE6=this.ATTRIBUTE6,
				ATTRIBUTE7=this.ATTRIBUTE7,
				ATTRIBUTE8=this.ATTRIBUTE8,
				TOTAL_QTY=this.TOTAL_QTY,
				OPEN_QTY=this.OPEN_QTY,
				QUANTITY_UM=this.QUANTITY_UM,
				ERP_ORDER_ID=this.ERP_ORDER_ID,
				ERP_ORDER_LINE_NUM=this.ERP_ORDER_LINE_NUM,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
				INVENTORY_STS=this.INVENTORY_STS,
			};
		}
	}
}
