//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class SHIPPING_CART_DETAIL
	{
		public Apps.Models.SCV.SHIPPING.SHIPPING_CART_DETAIL_MODEL ToPOCO(){
			return new Apps.Models.SCV.SHIPPING.SHIPPING_CART_DETAIL_MODEL(){
								INTERNAL_NUM=this.INTERNAL_NUM,
				PARENT=this.PARENT,
				CART_ID=this.CART_ID,
				INTERNAL_CONTAINER_NUM=this.INTERNAL_CONTAINER_NUM,
				CONTAINER_ID=this.CONTAINER_ID,
				INTERNAL_SHIPMENT_NUM=this.INTERNAL_SHIPMENT_NUM,
				SHIPMENT_ID=this.SHIPMENT_ID,
				COMPANY=this.COMPANY,
				TRAILING_NUM=this.TRAILING_NUM,
				STATUS=this.STATUS,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
			};
		}
	}
}
