//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class TASK_CREATION_MASTER
	{
		public Apps.Models.SCV.TASK.TASK_CREATION_MASTER_MODEL ToPOCO(){
			return new Apps.Models.SCV.TASK.TASK_CREATION_MASTER_MODEL(){
								INTERNAL_MASTER_NUM=this.INTERNAL_MASTER_NUM,
				RECORD_TYPE=this.RECORD_TYPE,
				DESCRIPTION=this.DESCRIPTION,
				TASK_TYPE=this.TASK_TYPE,
				PRIORITY=this.PRIORITY,
				FILTER_NAME=this.FILTER_NAME,
				MAXIMUM_QTY=this.MAXIMUM_QTY,
				QUANTITY_UM=this.QUANTITY_UM,
				MAXIMUM_WEIGHT=this.MAXIMUM_WEIGHT,
				WEIGHT_UM=this.WEIGHT_UM,
				MAXIMUM_VOLUME=this.MAXIMUM_VOLUME,
				VOLUME_UM=this.VOLUME_UM,
				MAXIMUM_INSTRUCTIONS=this.MAXIMUM_INSTRUCTIONS,
				CREATE_USER=this.CREATE_USER,
				CREATE_DATE_TIME=this.CREATE_DATE_TIME,
				TASK_ID_FIELD=this.TASK_ID_FIELD,
				INTERNAL_TASK_TYPE=this.INTERNAL_TASK_TYPE,
				ACTIVE=this.ACTIVE,
				LAST_MODIFY_USER=this.LAST_MODIFY_USER,
				LAST_MODIFY_DATE_TIME=this.LAST_MODIFY_DATE_TIME,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
			};
		}
	}
}
