//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class TRANSFER_ORDER_HEADER
	{
		public Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL ToPOCO(){
			return new Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL(){
								INTERNAL_TRANSFER_NUM=this.INTERNAL_TRANSFER_NUM,
				TRANSFER_ID=this.TRANSFER_ID,
				LEADING_STS=this.LEADING_STS,
				CART_ID=this.CART_ID,
				BEGIN_DATE_TIME=this.BEGIN_DATE_TIME,
				END_DATE_TIME=this.END_DATE_TIME,
				CREATED_USER=this.CREATED_USER,
				CREATED_DATE_TIME=this.CREATED_DATE_TIME,
				LAST_MODIFIED_USER=this.LAST_MODIFIED_USER,
				LAST_MODIFIED_DATE_TIME=this.LAST_MODIFIED_DATE_TIME,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
				WAREHOUSE=this.WAREHOUSE,
				COMPANY=this.COMPANY,
				TRAILING_STS=this.TRAILING_STS,
			};
		}
	}
}
