//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class USER_ZONE_AUTH
	{
		public Apps.Models.SCV.USER.USER_ZONE_AUTH_MODEL ToPOCO(){
			return new Apps.Models.SCV.USER.USER_ZONE_AUTH_MODEL(){
								ZONE=this.ZONE,
				ZONE_NAME=this.ZONE_NAME,
				USER_ID=this.USER_ID,
				USER_NAME=this.USER_NAME,
				USER_STAMP=this.USER_STAMP,
				DATE_TIME_STAMP=this.DATE_TIME_STAMP,
			};
		}
	}
}
