//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class WAREHOUSE_ACTIVITY
	{
		public Apps.Models.SCV.WAREHOUSE.WAREHOUSE_ACTIVITY_MODEL ToPOCO(){
			return new Apps.Models.SCV.WAREHOUSE.WAREHOUSE_ACTIVITY_MODEL(){
								INTERNAL_NUM=this.INTERNAL_NUM,
				WAREHOUSE=this.WAREHOUSE,
				COMPANY=this.COMPANY,
				ACTIVITY_TYPE=this.ACTIVITY_TYPE,
				ACTIVITY_NAME=this.ACTIVITY_NAME,
				REFERENCE_NUM1=this.REFERENCE_NUM1,
				REFERENCE_ID1=this.REFERENCE_ID1,
				REFERENCE_TYPE1=this.REFERENCE_TYPE1,
				REFERENCE_NUM2=this.REFERENCE_NUM2,
				REFERENCE_ID2=this.REFERENCE_ID2,
				REFERENCE_TYPE2=this.REFERENCE_TYPE2,
				REFERENCE_NUM3=this.REFERENCE_NUM3,
				REFERENCE_ID3=this.REFERENCE_ID3,
				REFERENCE_TYPE3=this.REFERENCE_TYPE3,
				REFERENCE_NUM4=this.REFERENCE_NUM4,
				REFERENCE_ID4=this.REFERENCE_ID4,
				REFERENCE_TYPE4=this.REFERENCE_TYPE4,
				REFERENCE_STATUS=this.REFERENCE_STATUS,
				START_DATE_TIME=this.START_DATE_TIME,
				END_DATE_TIME=this.END_DATE_TIME,
				COMPLETED_USER=this.COMPLETED_USER,
				USER_DEF1=this.USER_DEF1,
				USER_DEF2=this.USER_DEF2,
				USER_DEF3=this.USER_DEF3,
				USER_DEF4=this.USER_DEF4,
				USER_DEF5=this.USER_DEF5,
				USER_DEF6=this.USER_DEF6,
				USER_DEF7=this.USER_DEF7,
				USER_DEF8=this.USER_DEF8,
			};
		}
	}
}
