//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.Sys
{
	public class Virtual_SysLogService
	{

		public Apps.IRepository.IDBSession DBSession{
			 get
			{
				return DBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.Sys.ISysLogRepository m_Rep{
			 get
			{
				return DBSession.SysLog;
			}
		}
		

		public virtual List<Apps.Models.Sys.SysLogModel> GetList(Expression<Func<Apps.Models.SysLog, bool>> where = null){
		
				IQueryable<SysLog> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysLogModel> GetListSort<TKey>(Expression<Func<Apps.Models.SysLog, bool>> where,Expression<Func<Apps.Models.SysLog, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<SysLog> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysLogModel> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.SysLog, bool>> where = null)
		{

			IQueryable<SysLog> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.Id.Contains(queryStr)
								|| a.Operator.Contains(queryStr)
								|| a.Message.Contains(queryStr)
								|| a.Result.Contains(queryStr)
								|| a.Type.Contains(queryStr)
								|| a.Module.Contains(queryStr)
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.Sys.SysLogModel> CreateModelList(ref IQueryable<SysLog> queryData)
		{

			List<Apps.Models.Sys.SysLogModel> modelList = (from r in queryData
											  select new Apps.Models.Sys.SysLogModel
											  {
													Id = r.Id,
													Operator = r.Operator,
													Message = r.Message,
													Result = r.Result,
													Type = r.Type,
													Module = r.Module,
													CreateTime = r.CreateTime,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.Sys.SysLogModel model)
		{
				SysLog entity = m_Rep.GetById(model.Id);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new SysLog();
			   				entity.Id = model.Id;
				entity.Operator = model.Operator;
				entity.Message = model.Message;
				entity.Result = model.Result;
				entity.Type = model.Type;
				entity.Module = model.Module;
				entity.CreateTime = model.CreateTime;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.Sys.SysLogModel model,params string[] updateProperties)
		{
				SysLog entity = m_Rep.GetById(model.Id);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							if (updateProperties.Count() <= 0){
										entity.Id = model.Id;
											entity.Operator = model.Operator;
											entity.Message = model.Message;
											entity.Result = model.Result;
											entity.Type = model.Type;
											entity.Module = model.Module;
											entity.CreateTime = model.CreateTime;
									}else{
					
						Type type = typeof(Apps.Models.Sys.SysLogModel);
						Type typeE = typeof(Apps.Models.SysLog);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.Sys.SysLogModel GetById(string id)
		{
			SysLog entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//SysLog entity = m_Rep.GetById(id);
				Apps.Models.Sys.SysLogModel model = new Apps.Models.Sys.SysLogModel();
							  				model.Id = entity.Id;
				model.Operator = entity.Operator;
				model.Message = entity.Message;
				model.Result = entity.Result;
				model.Type = entity.Type;
				model.Module = entity.Module;
				model.CreateTime = entity.CreateTime;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
