//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.Sys
{
	public class Virtual_SysPositionService
	{

		public Apps.IRepository.IDBSession DBSession{
			 get
			{
				return DBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.Sys.ISysPositionRepository m_Rep{
			 get
			{
				return DBSession.SysPosition;
			}
		}
		

		public virtual List<Apps.Models.Sys.SysPositionModel> GetList(Expression<Func<Apps.Models.SysPosition, bool>> where = null){
		
				IQueryable<SysPosition> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysPositionModel> GetListSort<TKey>(Expression<Func<Apps.Models.SysPosition, bool>> where,Expression<Func<Apps.Models.SysPosition, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<SysPosition> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysPositionModel> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.SysPosition, bool>> where = null)
		{

			IQueryable<SysPosition> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								
								
								
								
								|| a.DepId.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.Sys.SysPositionModel> CreateModelList(ref IQueryable<SysPosition> queryData)
		{

			List<Apps.Models.Sys.SysPositionModel> modelList = (from r in queryData
											  select new Apps.Models.Sys.SysPositionModel
											  {
													Id = r.Id,
													Name = r.Name,
													Remark = r.Remark,
													Sort = r.Sort,
													CreateTime = r.CreateTime,
													Enable = r.Enable,
													MemberCount = r.MemberCount,
													DepId = r.DepId,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.Sys.SysPositionModel model)
		{
				SysPosition entity = m_Rep.GetById(model.Id);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new SysPosition();
			   				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Remark = model.Remark;
				entity.Sort = model.Sort;
				entity.CreateTime = model.CreateTime;
				entity.Enable = model.Enable;
				entity.MemberCount = model.MemberCount;
				entity.DepId = model.DepId;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.Sys.SysPositionModel model,params string[] updateProperties)
		{
				SysPosition entity = m_Rep.GetById(model.Id);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							if (updateProperties.Count() <= 0){
										entity.Id = model.Id;
											entity.Name = model.Name;
											entity.Remark = model.Remark;
											entity.Sort = model.Sort;
											entity.CreateTime = model.CreateTime;
											entity.Enable = model.Enable;
											entity.MemberCount = model.MemberCount;
											entity.DepId = model.DepId;
									}else{
					
						Type type = typeof(Apps.Models.Sys.SysPositionModel);
						Type typeE = typeof(Apps.Models.SysPosition);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.Sys.SysPositionModel GetById(string id)
		{
			SysPosition entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//SysPosition entity = m_Rep.GetById(id);
				Apps.Models.Sys.SysPositionModel model = new Apps.Models.Sys.SysPositionModel();
							  				model.Id = entity.Id;
				model.Name = entity.Name;
				model.Remark = entity.Remark;
				model.Sort = entity.Sort;
				model.CreateTime = entity.CreateTime;
				model.Enable = entity.Enable;
				model.MemberCount = entity.MemberCount;
				model.DepId = entity.DepId;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
