//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.Sys
{
	public class Virtual_SysRightService
	{

		public Apps.IRepository.IDBSession DBSession{
			 get
			{
				return DBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.Sys.ISysRightRepository m_Rep{
			 get
			{
				return DBSession.SysRight;
			}
		}
		

		public virtual List<Apps.Models.Sys.SysRightModel> GetList(Expression<Func<Apps.Models.SysRight, bool>> where = null){
		
				IQueryable<SysRight> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysRightModel> GetListSort<TKey>(Expression<Func<Apps.Models.SysRight, bool>> where,Expression<Func<Apps.Models.SysRight, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<SysRight> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.Sys.SysRightModel> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.SysRight, bool>> where = null)
		{

			IQueryable<SysRight> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.Id.Contains(queryStr)
								|| a.ModuleId.Contains(queryStr)
								|| a.RoleId.Contains(queryStr)
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.Sys.SysRightModel> CreateModelList(ref IQueryable<SysRight> queryData)
		{

			List<Apps.Models.Sys.SysRightModel> modelList = (from r in queryData
											  select new Apps.Models.Sys.SysRightModel
											  {
													Id = r.Id,
													ModuleId = r.ModuleId,
													RoleId = r.RoleId,
													Rightflag = r.Rightflag,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.Sys.SysRightModel model)
		{
				SysRight entity = m_Rep.GetById(model.Id);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new SysRight();
			   				entity.Id = model.Id;
				entity.ModuleId = model.ModuleId;
				entity.RoleId = model.RoleId;
				entity.Rightflag = model.Rightflag;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.Sys.SysRightModel model,params string[] updateProperties)
		{
				SysRight entity = m_Rep.GetById(model.Id);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							if (updateProperties.Count() <= 0){
										entity.Id = model.Id;
											entity.ModuleId = model.ModuleId;
											entity.RoleId = model.RoleId;
											entity.Rightflag = model.Rightflag;
									}else{
					
						Type type = typeof(Apps.Models.Sys.SysRightModel);
						Type typeE = typeof(Apps.Models.SysRight);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.Sys.SysRightModel GetById(string id)
		{
			SysRight entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//SysRight entity = m_Rep.GetById(id);
				Apps.Models.Sys.SysRightModel model = new Apps.Models.Sys.SysRightModel();
							  				model.Id = entity.Id;
				model.ModuleId = entity.ModuleId;
				model.RoleId = entity.RoleId;
				model.Rightflag = entity.Rightflag;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
