//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class Spl_Product
	{
		public Apps.Models.Spl.Spl_ProductModel ToPOCO(){
			return new Apps.Models.Spl.Spl_ProductModel(){
								Id=this.Id,
				Name=this.Name,
				Code=this.Code,
				Price=this.Price,
				CostPrice=this.CostPrice,
				Color=this.Color,
				Number=this.Number,
				CategoryId=this.CategoryId,
				CreateTime=this.CreateTime,
				CreateBy=this.CreateBy,
			};
		}
	}
}
