//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
	public partial class SysSample
	{
		public Apps.Models.Sys.SysSampleModel ToPOCO(){
			return new Apps.Models.Sys.SysSampleModel(){
								Id=this.Id,
				Name=this.Name,
				Age=this.Age,
				Bir=this.Bir,
				Photo=this.Photo,
				Note=this.Note,
				CreateTime=this.CreateTime,
			};
		}
	}
}
