//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
using System.Linq;

namespace Apps.IRepository.Sys
{
	public partial interface ISysUserRepository:IBaseRepository<SysUser>
	{
        IQueryable<SysModule> GetUserPermission(string userId);

        IQueryable<P_Sys_GetUserByDepId_Result> GetUserByDepId(string depId);

        int GetUserCountByDepId(string depId);

        IQueryable<P_Sys_GetRoleByUserId_Result> GetRoleByUserId(string userId);
    }
}
