//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;

namespace Apps.Service.SCV.REPLENISHMENT
{
	public partial class REPLENISHMENT_REQUEST_SERVICE: Virtual_REPLENISHMENT_REQUEST_SERVICE,Apps.IService.SCV.REPLENISHMENT.IREPLENISHMENT_REQUEST_SERVICE
	{
		

	}
}
