//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.Sys
{
	public class Virtual_USER_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.Sys.IUSER_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.USER;
			}
		}
		

		public virtual List<Apps.Models.SCV.Sys.USER_MODEL> GetList(Expression<Func<Apps.Models.USER, bool>> where = null){
		
				IQueryable<Apps.Models.USER> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.USER_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.USER, bool>> where,Expression<Func<Apps.Models.USER, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.USER> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.USER_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.USER, bool>> where = null)
		{

			IQueryable<Apps.Models.USER> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.USER_ID.Contains(queryStr)
								|| a.DESCRIPTION.Contains(queryStr)
								|| a.DEPARTMENT.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								|| a.USER_STAMP.Contains(queryStr)
								
								|| a.DEFAULT_WHS.Contains(queryStr)
								|| a.DEFAULT_RECV_PREF.Contains(queryStr)
								|| a.DEFAULT_SHIP_PREF.Contains(queryStr)
								|| a.DEFAULT_TASK_PREF.Contains(queryStr)
								|| a.ROLE.Contains(queryStr)
								|| a.PERSONAL_DIR.Contains(queryStr)
								|| a.IMAGE_URL.Contains(queryStr)
								|| a.TITLE.Contains(queryStr)
								|| a.GENDER.Contains(queryStr)
								|| a.MOBILE.Contains(queryStr)
								|| a.PHONE.Contains(queryStr)
								|| a.EMAIL.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								
								|| a.CREATE_USER.Contains(queryStr)
								
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.Sys.USER_MODEL> CreateModelList(ref IQueryable<Apps.Models.USER> queryData)
		{

			List<Apps.Models.SCV.Sys.USER_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.Sys.USER_MODEL
											  {
													INTERNAL_USER_NUM = r.INTERNAL_USER_NUM,
													USER_ID = r.USER_ID,
													DESCRIPTION = r.DESCRIPTION,
													DEPARTMENT = r.DEPARTMENT,
													ACTIVE = r.ACTIVE,
													USER_STAMP = r.USER_STAMP,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													DEFAULT_WHS = r.DEFAULT_WHS,
													DEFAULT_RECV_PREF = r.DEFAULT_RECV_PREF,
													DEFAULT_SHIP_PREF = r.DEFAULT_SHIP_PREF,
													DEFAULT_TASK_PREF = r.DEFAULT_TASK_PREF,
													ROLE = r.ROLE,
													PERSONAL_DIR = r.PERSONAL_DIR,
													IMAGE_URL = r.IMAGE_URL,
													TITLE = r.TITLE,
													GENDER = r.GENDER,
													MOBILE = r.MOBILE,
													PHONE = r.PHONE,
													EMAIL = r.EMAIL,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													CREATE_DATE_TIME = r.CREATE_DATE_TIME,
													CREATE_USER = r.CREATE_USER,
													USER_DEF9 = r.USER_DEF9,
													USER_DEF10 = r.USER_DEF10,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.Sys.USER_MODEL model)
		{
				Apps.Models.USER entity = m_Rep.GetById(model.INTERNAL_USER_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.USER();
			   				entity.INTERNAL_USER_NUM = model.INTERNAL_USER_NUM;
				entity.USER_ID = model.USER_ID;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.DEPARTMENT = model.DEPARTMENT;
				entity.ACTIVE = model.ACTIVE;
				entity.USER_STAMP = model.USER_STAMP;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.DEFAULT_WHS = model.DEFAULT_WHS;
				entity.DEFAULT_RECV_PREF = model.DEFAULT_RECV_PREF;
				entity.DEFAULT_SHIP_PREF = model.DEFAULT_SHIP_PREF;
				entity.DEFAULT_TASK_PREF = model.DEFAULT_TASK_PREF;
				entity.ROLE = model.ROLE;
				entity.PERSONAL_DIR = model.PERSONAL_DIR;
				entity.IMAGE_URL = model.IMAGE_URL;
				entity.TITLE = model.TITLE;
				entity.GENDER = model.GENDER;
				entity.MOBILE = model.MOBILE;
				entity.PHONE = model.PHONE;
				entity.EMAIL = model.EMAIL;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.CREATE_DATE_TIME = model.CREATE_DATE_TIME;
				entity.CREATE_USER = model.CREATE_USER;
				entity.USER_DEF9 = model.USER_DEF9;
				entity.USER_DEF10 = model.USER_DEF10;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.Sys.USER_MODEL model,params string[] updateProperties)
		{
				Apps.Models.USER entity = m_Rep.GetById(model.INTERNAL_USER_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_USER_NUM = model.INTERNAL_USER_NUM;
											entity.USER_ID = model.USER_ID;
											entity.DESCRIPTION = model.DESCRIPTION;
											entity.DEPARTMENT = model.DEPARTMENT;
											entity.ACTIVE = model.ACTIVE;
											entity.USER_STAMP = model.USER_STAMP;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.DEFAULT_WHS = model.DEFAULT_WHS;
											entity.DEFAULT_RECV_PREF = model.DEFAULT_RECV_PREF;
											entity.DEFAULT_SHIP_PREF = model.DEFAULT_SHIP_PREF;
											entity.DEFAULT_TASK_PREF = model.DEFAULT_TASK_PREF;
											entity.ROLE = model.ROLE;
											entity.PERSONAL_DIR = model.PERSONAL_DIR;
											entity.IMAGE_URL = model.IMAGE_URL;
											entity.TITLE = model.TITLE;
											entity.GENDER = model.GENDER;
											entity.MOBILE = model.MOBILE;
											entity.PHONE = model.PHONE;
											entity.EMAIL = model.EMAIL;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.CREATE_DATE_TIME = model.CREATE_DATE_TIME;
											entity.CREATE_USER = model.CREATE_USER;
											entity.USER_DEF9 = model.USER_DEF9;
											entity.USER_DEF10 = model.USER_DEF10;
									}else{
					
						Type type = typeof(Apps.Models.SCV.Sys.USER_MODEL);
						Type typeE = typeof(Apps.Models.USER);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.Sys.USER_MODEL GetById(string id)
		{
			Apps.Models.USER entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//USER entity = m_Rep.GetById(id);
				Apps.Models.SCV.Sys.USER_MODEL model = new Apps.Models.SCV.Sys.USER_MODEL();
							  				model.INTERNAL_USER_NUM = entity.INTERNAL_USER_NUM;
				model.USER_ID = entity.USER_ID;
				model.DESCRIPTION = entity.DESCRIPTION;
				model.DEPARTMENT = entity.DEPARTMENT;
				model.ACTIVE = entity.ACTIVE;
				model.USER_STAMP = entity.USER_STAMP;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.DEFAULT_WHS = entity.DEFAULT_WHS;
				model.DEFAULT_RECV_PREF = entity.DEFAULT_RECV_PREF;
				model.DEFAULT_SHIP_PREF = entity.DEFAULT_SHIP_PREF;
				model.DEFAULT_TASK_PREF = entity.DEFAULT_TASK_PREF;
				model.ROLE = entity.ROLE;
				model.PERSONAL_DIR = entity.PERSONAL_DIR;
				model.IMAGE_URL = entity.IMAGE_URL;
				model.TITLE = entity.TITLE;
				model.GENDER = entity.GENDER;
				model.MOBILE = entity.MOBILE;
				model.PHONE = entity.PHONE;
				model.EMAIL = entity.EMAIL;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.CREATE_DATE_TIME = entity.CREATE_DATE_TIME;
				model.CREATE_USER = entity.CREATE_USER;
				model.USER_DEF9 = entity.USER_DEF9;
				model.USER_DEF10 = entity.USER_DEF10;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
