//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.INTERFACE
{
	public class Virtual_INTERFACE_SESSION_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.INTERFACE.IINTERFACE_SESSION_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.INTERFACE_SESSION;
			}
		}
		

		public virtual List<Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL> GetList(Expression<Func<Apps.Models.INTERFACE_SESSION, bool>> where = null){
		
				IQueryable<Apps.Models.INTERFACE_SESSION> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.INTERFACE_SESSION, bool>> where,Expression<Func<Apps.Models.INTERFACE_SESSION, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.INTERFACE_SESSION> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.INTERFACE_SESSION, bool>> where = null)
		{

			IQueryable<Apps.Models.INTERFACE_SESSION> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.WAREHOUSE.Contains(queryStr)
								|| a.COMPANY.Contains(queryStr)
								|| a.USER_ID.Contains(queryStr)
								|| a.APPKEY.Contains(queryStr)
								|| a.PASSWORD.Contains(queryStr)
								|| a.TOKEN.Contains(queryStr)
								|| a.REFRESH_TOKEN.Contains(queryStr)
								|| a.REDIRECT_URL.Contains(queryStr)
								|| a.SANDBOX.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								
								|| a.USER_STAMP.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL> CreateModelList(ref IQueryable<Apps.Models.INTERFACE_SESSION> queryData)
		{

			List<Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL
											  {
													INTERNAL_SESS_NUM = r.INTERNAL_SESS_NUM,
													WAREHOUSE = r.WAREHOUSE,
													COMPANY = r.COMPANY,
													USER_ID = r.USER_ID,
													APPKEY = r.APPKEY,
													PASSWORD = r.PASSWORD,
													TOKEN = r.TOKEN,
													REFRESH_TOKEN = r.REFRESH_TOKEN,
													REDIRECT_URL = r.REDIRECT_URL,
													SANDBOX = r.SANDBOX,
													ACTIVE = r.ACTIVE,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													USER_STAMP = r.USER_STAMP,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL model)
		{
				Apps.Models.INTERFACE_SESSION entity = m_Rep.GetById(model.INTERNAL_SESS_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.INTERFACE_SESSION();
			   				entity.INTERNAL_SESS_NUM = model.INTERNAL_SESS_NUM;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.COMPANY = model.COMPANY;
				entity.USER_ID = model.USER_ID;
				entity.APPKEY = model.APPKEY;
				entity.PASSWORD = model.PASSWORD;
				entity.TOKEN = model.TOKEN;
				entity.REFRESH_TOKEN = model.REFRESH_TOKEN;
				entity.REDIRECT_URL = model.REDIRECT_URL;
				entity.SANDBOX = model.SANDBOX;
				entity.ACTIVE = model.ACTIVE;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.USER_STAMP = model.USER_STAMP;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL model,params string[] updateProperties)
		{
				Apps.Models.INTERFACE_SESSION entity = m_Rep.GetById(model.INTERNAL_SESS_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_SESS_NUM = model.INTERNAL_SESS_NUM;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.COMPANY = model.COMPANY;
											entity.USER_ID = model.USER_ID;
											entity.APPKEY = model.APPKEY;
											entity.PASSWORD = model.PASSWORD;
											entity.TOKEN = model.TOKEN;
											entity.REFRESH_TOKEN = model.REFRESH_TOKEN;
											entity.REDIRECT_URL = model.REDIRECT_URL;
											entity.SANDBOX = model.SANDBOX;
											entity.ACTIVE = model.ACTIVE;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.USER_STAMP = model.USER_STAMP;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
									}else{
					
						Type type = typeof(Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL);
						Type typeE = typeof(Apps.Models.INTERFACE_SESSION);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL GetById(string id)
		{
			Apps.Models.INTERFACE_SESSION entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//INTERFACE_SESSION entity = m_Rep.GetById(id);
				Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL model = new Apps.Models.SCV.INTERFACE.INTERFACE_SESSION_MODEL();
							  				model.INTERNAL_SESS_NUM = entity.INTERNAL_SESS_NUM;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.COMPANY = entity.COMPANY;
				model.USER_ID = entity.USER_ID;
				model.APPKEY = entity.APPKEY;
				model.PASSWORD = entity.PASSWORD;
				model.TOKEN = entity.TOKEN;
				model.REFRESH_TOKEN = entity.REFRESH_TOKEN;
				model.REDIRECT_URL = entity.REDIRECT_URL;
				model.SANDBOX = entity.SANDBOX;
				model.ACTIVE = entity.ACTIVE;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.USER_STAMP = entity.USER_STAMP;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
