//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.Sys
{
	public class Virtual_MESSAGE_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.Sys.IMESSAGE_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.MESSAGE;
			}
		}
		

		public virtual List<Apps.Models.SCV.Sys.MESSAGE_MODEL> GetList(Expression<Func<Apps.Models.MESSAGE, bool>> where = null){
		
				IQueryable<Apps.Models.MESSAGE> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.MESSAGE_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.MESSAGE, bool>> where,Expression<Func<Apps.Models.MESSAGE, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.MESSAGE> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.MESSAGE_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.MESSAGE, bool>> where = null)
		{

			IQueryable<Apps.Models.MESSAGE> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.MESSAGE_ID.Contains(queryStr)
								|| a.MESSAGE_TYPE.Contains(queryStr)
								|| a.SUB_TYPE.Contains(queryStr)
								
								|| a.SRC_END_POINT.Contains(queryStr)
								|| a.DST_END_POINT.Contains(queryStr)
								
								
								|| a.PROCESS_STAMP.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.MESSAGE_BODY.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.Sys.MESSAGE_MODEL> CreateModelList(ref IQueryable<Apps.Models.MESSAGE> queryData)
		{

			List<Apps.Models.SCV.Sys.MESSAGE_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.Sys.MESSAGE_MODEL
											  {
													MESSAGE_ID = r.MESSAGE_ID,
													MESSAGE_TYPE = r.MESSAGE_TYPE,
													SUB_TYPE = r.SUB_TYPE,
													PRIORITY = r.PRIORITY,
													SRC_END_POINT = r.SRC_END_POINT,
													DST_END_POINT = r.DST_END_POINT,
													STATUS = r.STATUS,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													PROCESS_STAMP = r.PROCESS_STAMP,
													ACTIVE = r.ACTIVE,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													MESSAGE_BODY = r.MESSAGE_BODY,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.Sys.MESSAGE_MODEL model)
		{
				Apps.Models.MESSAGE entity = m_Rep.GetById(model.MESSAGE_ID);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.MESSAGE();
			   				entity.MESSAGE_ID = model.MESSAGE_ID;
				entity.MESSAGE_TYPE = model.MESSAGE_TYPE;
				entity.SUB_TYPE = model.SUB_TYPE;
				entity.PRIORITY = model.PRIORITY;
				entity.SRC_END_POINT = model.SRC_END_POINT;
				entity.DST_END_POINT = model.DST_END_POINT;
				entity.STATUS = model.STATUS;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.PROCESS_STAMP = model.PROCESS_STAMP;
				entity.ACTIVE = model.ACTIVE;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.MESSAGE_BODY = model.MESSAGE_BODY;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.Sys.MESSAGE_MODEL model,params string[] updateProperties)
		{
				Apps.Models.MESSAGE entity = m_Rep.GetById(model.MESSAGE_ID);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.MESSAGE_ID = model.MESSAGE_ID;
											entity.MESSAGE_TYPE = model.MESSAGE_TYPE;
											entity.SUB_TYPE = model.SUB_TYPE;
											entity.PRIORITY = model.PRIORITY;
											entity.SRC_END_POINT = model.SRC_END_POINT;
											entity.DST_END_POINT = model.DST_END_POINT;
											entity.STATUS = model.STATUS;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.PROCESS_STAMP = model.PROCESS_STAMP;
											entity.ACTIVE = model.ACTIVE;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.MESSAGE_BODY = model.MESSAGE_BODY;
									}else{
					
						Type type = typeof(Apps.Models.SCV.Sys.MESSAGE_MODEL);
						Type typeE = typeof(Apps.Models.MESSAGE);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.Sys.MESSAGE_MODEL GetById(string id)
		{
			Apps.Models.MESSAGE entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//MESSAGE entity = m_Rep.GetById(id);
				Apps.Models.SCV.Sys.MESSAGE_MODEL model = new Apps.Models.SCV.Sys.MESSAGE_MODEL();
							  				model.MESSAGE_ID = entity.MESSAGE_ID;
				model.MESSAGE_TYPE = entity.MESSAGE_TYPE;
				model.SUB_TYPE = entity.SUB_TYPE;
				model.PRIORITY = entity.PRIORITY;
				model.SRC_END_POINT = entity.SRC_END_POINT;
				model.DST_END_POINT = entity.DST_END_POINT;
				model.STATUS = entity.STATUS;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.PROCESS_STAMP = entity.PROCESS_STAMP;
				model.ACTIVE = entity.ACTIVE;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.MESSAGE_BODY = entity.MESSAGE_BODY;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
