//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.DOWNLOAD
{
	public class Virtual_DOWNLOAD_RECEIPT_DETAIL_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_DETAIL_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.DOWNLOAD_RECEIPT_DETAIL;
			}
		}
		

		public virtual List<Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL> GetList(Expression<Func<Apps.Models.DOWNLOAD_RECEIPT_DETAIL, bool>> where = null){
		
				IQueryable<Apps.Models.DOWNLOAD_RECEIPT_DETAIL> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.DOWNLOAD_RECEIPT_DETAIL, bool>> where,Expression<Func<Apps.Models.DOWNLOAD_RECEIPT_DETAIL, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.DOWNLOAD_RECEIPT_DETAIL> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.DOWNLOAD_RECEIPT_DETAIL, bool>> where = null)
		{

			IQueryable<Apps.Models.DOWNLOAD_RECEIPT_DETAIL> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.INTERFACE_RECORD_ID.Contains(queryStr)
								|| a.INTERFACE_LINK_ID.Contains(queryStr)
								|| a.INTERFACE_ACTION_CODE.Contains(queryStr)
								|| a.INTERFACE_CONDITION.Contains(queryStr)
								|| a.PROCESS_STAMP.Contains(queryStr)
								|| a.RECEIPT_ID.Contains(queryStr)
								|| a.WAREHOUSE.Contains(queryStr)
								|| a.COMPANY.Contains(queryStr)
								|| a.ITEM.Contains(queryStr)
								|| a.ITEM_DESC.Contains(queryStr)
								|| a.ITEM_CLASS.Contains(queryStr)
								|| a.ATTRIBUTE_TRACK.Contains(queryStr)
								
								|| a.ATTRIBUTE1.Contains(queryStr)
								|| a.ATTRIBUTE2.Contains(queryStr)
								|| a.ATTRIBUTE3.Contains(queryStr)
								|| a.ATTRIBUTE4.Contains(queryStr)
								|| a.ATTRIBUTE5.Contains(queryStr)
								|| a.ATTRIBUTE6.Contains(queryStr)
								|| a.ATTRIBUTE7.Contains(queryStr)
								|| a.ATTRIBUTE8.Contains(queryStr)
								
								
								|| a.QUANTITY_UM.Contains(queryStr)
								|| a.ERP_ORDER_ID.Contains(queryStr)
								|| a.ERP_ORDER_LINE_NUM.Contains(queryStr)
								|| a.LOCATING_RULE.Contains(queryStr)
								|| a.USER_STAMP.Contains(queryStr)
								
								|| a.INVENTORY_STS.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								
								
								|| a.ITEM_CATEGORY01.Contains(queryStr)
								|| a.ITEM_CATEGORY02.Contains(queryStr)
								|| a.ITEM_CATEGORY03.Contains(queryStr)
								|| a.ITEM_CATEGORY04.Contains(queryStr)
								|| a.ITEM_CATEGORY05.Contains(queryStr)
								|| a.ITEM_CATEGORY06.Contains(queryStr)
								|| a.ITEM_CATEGORY07.Contains(queryStr)
								|| a.ITEM_CATEGORY08.Contains(queryStr)
								
								|| a.CREATE_USER.Contains(queryStr)
								
								
								|| a.HOST_ITEM.Contains(queryStr)
								|| a.UPLOAD_INTERFACE_REQUIRED.Contains(queryStr)
								|| a.HOST_COMPANY.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL> CreateModelList(ref IQueryable<Apps.Models.DOWNLOAD_RECEIPT_DETAIL> queryData)
		{

			List<Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL
											  {
													INTERFACE_RECORD_ID = r.INTERFACE_RECORD_ID,
													INTERFACE_LINK_ID = r.INTERFACE_LINK_ID,
													INTERFACE_ACTION_CODE = r.INTERFACE_ACTION_CODE,
													INTERFACE_CONDITION = r.INTERFACE_CONDITION,
													PROCESS_STAMP = r.PROCESS_STAMP,
													RECEIPT_ID = r.RECEIPT_ID,
													WAREHOUSE = r.WAREHOUSE,
													COMPANY = r.COMPANY,
													ITEM = r.ITEM,
													ITEM_DESC = r.ITEM_DESC,
													ITEM_CLASS = r.ITEM_CLASS,
													ATTRIBUTE_TRACK = r.ATTRIBUTE_TRACK,
													ATTRIBUTE_NUM = r.ATTRIBUTE_NUM,
													ATTRIBUTE1 = r.ATTRIBUTE1,
													ATTRIBUTE2 = r.ATTRIBUTE2,
													ATTRIBUTE3 = r.ATTRIBUTE3,
													ATTRIBUTE4 = r.ATTRIBUTE4,
													ATTRIBUTE5 = r.ATTRIBUTE5,
													ATTRIBUTE6 = r.ATTRIBUTE6,
													ATTRIBUTE7 = r.ATTRIBUTE7,
													ATTRIBUTE8 = r.ATTRIBUTE8,
													TOTAL_QTY = r.TOTAL_QTY,
													OPEN_QTY = r.OPEN_QTY,
													QUANTITY_UM = r.QUANTITY_UM,
													ERP_ORDER_ID = r.ERP_ORDER_ID,
													ERP_ORDER_LINE_NUM = r.ERP_ORDER_LINE_NUM,
													LOCATING_RULE = r.LOCATING_RULE,
													USER_STAMP = r.USER_STAMP,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													INVENTORY_STS = r.INVENTORY_STS,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													ITEM_LIST_PRICE = r.ITEM_LIST_PRICE,
													ITEM_NET_PRICE = r.ITEM_NET_PRICE,
													ITEM_CATEGORY01 = r.ITEM_CATEGORY01,
													ITEM_CATEGORY02 = r.ITEM_CATEGORY02,
													ITEM_CATEGORY03 = r.ITEM_CATEGORY03,
													ITEM_CATEGORY04 = r.ITEM_CATEGORY04,
													ITEM_CATEGORY05 = r.ITEM_CATEGORY05,
													ITEM_CATEGORY06 = r.ITEM_CATEGORY06,
													ITEM_CATEGORY07 = r.ITEM_CATEGORY07,
													ITEM_CATEGORY08 = r.ITEM_CATEGORY08,
													CREATE_DATE_TIME = r.CREATE_DATE_TIME,
													CREATE_USER = r.CREATE_USER,
													USER_DEF9 = r.USER_DEF9,
													USER_DEF10 = r.USER_DEF10,
													HOST_ITEM = r.HOST_ITEM,
													UPLOAD_INTERFACE_REQUIRED = r.UPLOAD_INTERFACE_REQUIRED,
													HOST_COMPANY = r.HOST_COMPANY,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL model)
		{
				Apps.Models.DOWNLOAD_RECEIPT_DETAIL entity = m_Rep.GetById(model.INTERFACE_RECORD_ID);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.DOWNLOAD_RECEIPT_DETAIL();
			   				entity.INTERFACE_RECORD_ID = model.INTERFACE_RECORD_ID;
				entity.INTERFACE_LINK_ID = model.INTERFACE_LINK_ID;
				entity.INTERFACE_ACTION_CODE = model.INTERFACE_ACTION_CODE;
				entity.INTERFACE_CONDITION = model.INTERFACE_CONDITION;
				entity.PROCESS_STAMP = model.PROCESS_STAMP;
				entity.RECEIPT_ID = model.RECEIPT_ID;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.COMPANY = model.COMPANY;
				entity.ITEM = model.ITEM;
				entity.ITEM_DESC = model.ITEM_DESC;
				entity.ITEM_CLASS = model.ITEM_CLASS;
				entity.ATTRIBUTE_TRACK = model.ATTRIBUTE_TRACK;
				entity.ATTRIBUTE_NUM = model.ATTRIBUTE_NUM;
				entity.ATTRIBUTE1 = model.ATTRIBUTE1;
				entity.ATTRIBUTE2 = model.ATTRIBUTE2;
				entity.ATTRIBUTE3 = model.ATTRIBUTE3;
				entity.ATTRIBUTE4 = model.ATTRIBUTE4;
				entity.ATTRIBUTE5 = model.ATTRIBUTE5;
				entity.ATTRIBUTE6 = model.ATTRIBUTE6;
				entity.ATTRIBUTE7 = model.ATTRIBUTE7;
				entity.ATTRIBUTE8 = model.ATTRIBUTE8;
				entity.TOTAL_QTY = model.TOTAL_QTY;
				entity.OPEN_QTY = model.OPEN_QTY;
				entity.QUANTITY_UM = model.QUANTITY_UM;
				entity.ERP_ORDER_ID = model.ERP_ORDER_ID;
				entity.ERP_ORDER_LINE_NUM = model.ERP_ORDER_LINE_NUM;
				entity.LOCATING_RULE = model.LOCATING_RULE;
				entity.USER_STAMP = model.USER_STAMP;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.INVENTORY_STS = model.INVENTORY_STS;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.ITEM_LIST_PRICE = model.ITEM_LIST_PRICE;
				entity.ITEM_NET_PRICE = model.ITEM_NET_PRICE;
				entity.ITEM_CATEGORY01 = model.ITEM_CATEGORY01;
				entity.ITEM_CATEGORY02 = model.ITEM_CATEGORY02;
				entity.ITEM_CATEGORY03 = model.ITEM_CATEGORY03;
				entity.ITEM_CATEGORY04 = model.ITEM_CATEGORY04;
				entity.ITEM_CATEGORY05 = model.ITEM_CATEGORY05;
				entity.ITEM_CATEGORY06 = model.ITEM_CATEGORY06;
				entity.ITEM_CATEGORY07 = model.ITEM_CATEGORY07;
				entity.ITEM_CATEGORY08 = model.ITEM_CATEGORY08;
				entity.CREATE_DATE_TIME = model.CREATE_DATE_TIME;
				entity.CREATE_USER = model.CREATE_USER;
				entity.USER_DEF9 = model.USER_DEF9;
				entity.USER_DEF10 = model.USER_DEF10;
				entity.HOST_ITEM = model.HOST_ITEM;
				entity.UPLOAD_INTERFACE_REQUIRED = model.UPLOAD_INTERFACE_REQUIRED;
				entity.HOST_COMPANY = model.HOST_COMPANY;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL model,params string[] updateProperties)
		{
				Apps.Models.DOWNLOAD_RECEIPT_DETAIL entity = m_Rep.GetById(model.INTERFACE_RECORD_ID);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERFACE_RECORD_ID = model.INTERFACE_RECORD_ID;
											entity.INTERFACE_LINK_ID = model.INTERFACE_LINK_ID;
											entity.INTERFACE_ACTION_CODE = model.INTERFACE_ACTION_CODE;
											entity.INTERFACE_CONDITION = model.INTERFACE_CONDITION;
											entity.PROCESS_STAMP = model.PROCESS_STAMP;
											entity.RECEIPT_ID = model.RECEIPT_ID;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.COMPANY = model.COMPANY;
											entity.ITEM = model.ITEM;
											entity.ITEM_DESC = model.ITEM_DESC;
											entity.ITEM_CLASS = model.ITEM_CLASS;
											entity.ATTRIBUTE_TRACK = model.ATTRIBUTE_TRACK;
											entity.ATTRIBUTE_NUM = model.ATTRIBUTE_NUM;
											entity.ATTRIBUTE1 = model.ATTRIBUTE1;
											entity.ATTRIBUTE2 = model.ATTRIBUTE2;
											entity.ATTRIBUTE3 = model.ATTRIBUTE3;
											entity.ATTRIBUTE4 = model.ATTRIBUTE4;
											entity.ATTRIBUTE5 = model.ATTRIBUTE5;
											entity.ATTRIBUTE6 = model.ATTRIBUTE6;
											entity.ATTRIBUTE7 = model.ATTRIBUTE7;
											entity.ATTRIBUTE8 = model.ATTRIBUTE8;
											entity.TOTAL_QTY = model.TOTAL_QTY;
											entity.OPEN_QTY = model.OPEN_QTY;
											entity.QUANTITY_UM = model.QUANTITY_UM;
											entity.ERP_ORDER_ID = model.ERP_ORDER_ID;
											entity.ERP_ORDER_LINE_NUM = model.ERP_ORDER_LINE_NUM;
											entity.LOCATING_RULE = model.LOCATING_RULE;
											entity.USER_STAMP = model.USER_STAMP;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.INVENTORY_STS = model.INVENTORY_STS;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.ITEM_LIST_PRICE = model.ITEM_LIST_PRICE;
											entity.ITEM_NET_PRICE = model.ITEM_NET_PRICE;
											entity.ITEM_CATEGORY01 = model.ITEM_CATEGORY01;
											entity.ITEM_CATEGORY02 = model.ITEM_CATEGORY02;
											entity.ITEM_CATEGORY03 = model.ITEM_CATEGORY03;
											entity.ITEM_CATEGORY04 = model.ITEM_CATEGORY04;
											entity.ITEM_CATEGORY05 = model.ITEM_CATEGORY05;
											entity.ITEM_CATEGORY06 = model.ITEM_CATEGORY06;
											entity.ITEM_CATEGORY07 = model.ITEM_CATEGORY07;
											entity.ITEM_CATEGORY08 = model.ITEM_CATEGORY08;
											entity.CREATE_DATE_TIME = model.CREATE_DATE_TIME;
											entity.CREATE_USER = model.CREATE_USER;
											entity.USER_DEF9 = model.USER_DEF9;
											entity.USER_DEF10 = model.USER_DEF10;
											entity.HOST_ITEM = model.HOST_ITEM;
											entity.UPLOAD_INTERFACE_REQUIRED = model.UPLOAD_INTERFACE_REQUIRED;
											entity.HOST_COMPANY = model.HOST_COMPANY;
									}else{
					
						Type type = typeof(Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL);
						Type typeE = typeof(Apps.Models.DOWNLOAD_RECEIPT_DETAIL);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL GetById(string id)
		{
			Apps.Models.DOWNLOAD_RECEIPT_DETAIL entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//DOWNLOAD_RECEIPT_DETAIL entity = m_Rep.GetById(id);
				Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL model = new Apps.Models.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_MODEL();
							  				model.INTERFACE_RECORD_ID = entity.INTERFACE_RECORD_ID;
				model.INTERFACE_LINK_ID = entity.INTERFACE_LINK_ID;
				model.INTERFACE_ACTION_CODE = entity.INTERFACE_ACTION_CODE;
				model.INTERFACE_CONDITION = entity.INTERFACE_CONDITION;
				model.PROCESS_STAMP = entity.PROCESS_STAMP;
				model.RECEIPT_ID = entity.RECEIPT_ID;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.COMPANY = entity.COMPANY;
				model.ITEM = entity.ITEM;
				model.ITEM_DESC = entity.ITEM_DESC;
				model.ITEM_CLASS = entity.ITEM_CLASS;
				model.ATTRIBUTE_TRACK = entity.ATTRIBUTE_TRACK;
				model.ATTRIBUTE_NUM = entity.ATTRIBUTE_NUM;
				model.ATTRIBUTE1 = entity.ATTRIBUTE1;
				model.ATTRIBUTE2 = entity.ATTRIBUTE2;
				model.ATTRIBUTE3 = entity.ATTRIBUTE3;
				model.ATTRIBUTE4 = entity.ATTRIBUTE4;
				model.ATTRIBUTE5 = entity.ATTRIBUTE5;
				model.ATTRIBUTE6 = entity.ATTRIBUTE6;
				model.ATTRIBUTE7 = entity.ATTRIBUTE7;
				model.ATTRIBUTE8 = entity.ATTRIBUTE8;
				model.TOTAL_QTY = entity.TOTAL_QTY;
				model.OPEN_QTY = entity.OPEN_QTY;
				model.QUANTITY_UM = entity.QUANTITY_UM;
				model.ERP_ORDER_ID = entity.ERP_ORDER_ID;
				model.ERP_ORDER_LINE_NUM = entity.ERP_ORDER_LINE_NUM;
				model.LOCATING_RULE = entity.LOCATING_RULE;
				model.USER_STAMP = entity.USER_STAMP;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.INVENTORY_STS = entity.INVENTORY_STS;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.ITEM_LIST_PRICE = entity.ITEM_LIST_PRICE;
				model.ITEM_NET_PRICE = entity.ITEM_NET_PRICE;
				model.ITEM_CATEGORY01 = entity.ITEM_CATEGORY01;
				model.ITEM_CATEGORY02 = entity.ITEM_CATEGORY02;
				model.ITEM_CATEGORY03 = entity.ITEM_CATEGORY03;
				model.ITEM_CATEGORY04 = entity.ITEM_CATEGORY04;
				model.ITEM_CATEGORY05 = entity.ITEM_CATEGORY05;
				model.ITEM_CATEGORY06 = entity.ITEM_CATEGORY06;
				model.ITEM_CATEGORY07 = entity.ITEM_CATEGORY07;
				model.ITEM_CATEGORY08 = entity.ITEM_CATEGORY08;
				model.CREATE_DATE_TIME = entity.CREATE_DATE_TIME;
				model.CREATE_USER = entity.CREATE_USER;
				model.USER_DEF9 = entity.USER_DEF9;
				model.USER_DEF10 = entity.USER_DEF10;
				model.HOST_ITEM = entity.HOST_ITEM;
				model.UPLOAD_INTERFACE_REQUIRED = entity.UPLOAD_INTERFACE_REQUIRED;
				model.HOST_COMPANY = entity.HOST_COMPANY;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
