//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.TRANSFER
{
	public class Virtual_TRANSFER_ORDER_DETAIL_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_DETAIL_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.TRANSFER_ORDER_DETAIL;
			}
		}
		

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL> GetList(Expression<Func<Apps.Models.TRANSFER_ORDER_DETAIL, bool>> where = null){
		
				IQueryable<Apps.Models.TRANSFER_ORDER_DETAIL> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.TRANSFER_ORDER_DETAIL, bool>> where,Expression<Func<Apps.Models.TRANSFER_ORDER_DETAIL, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.TRANSFER_ORDER_DETAIL> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.TRANSFER_ORDER_DETAIL, bool>> where = null)
		{

			IQueryable<Apps.Models.TRANSFER_ORDER_DETAIL> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								
								,a=>a.TRANSFER_ID.Contains(queryStr)
								
								|| a.WAREHOUSE.Contains(queryStr)
								|| a.FROM_LOC.Contains(queryStr)
								|| a.TO_LOC.Contains(queryStr)
								|| a.COMPANY.Contains(queryStr)
								|| a.ITEM.Contains(queryStr)
								|| a.ITEM_DESC.Contains(queryStr)
								|| a.FROM_LPN.Contains(queryStr)
								|| a.TO_LPN.Contains(queryStr)
								
								
								
								|| a.QUANTITY_UM.Contains(queryStr)
								
								
								
								|| a.INVENTORY_STS.Contains(queryStr)
								|| a.LOCATING_RULE.Contains(queryStr)
								|| a.CREATED_USER.Contains(queryStr)
								
								|| a.LAST_MODIFIED_USER.Contains(queryStr)
								
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								|| a.CART_ID.Contains(queryStr)
								|| a.CART_POS.Contains(queryStr)
								
								|| a.ATTRIBUTE1.Contains(queryStr)
								|| a.ATTRIBUTE2.Contains(queryStr)
								|| a.ATTRIBUTE3.Contains(queryStr)
								|| a.ATTRIBUTE4.Contains(queryStr)
								|| a.ATTRIBUTE5.Contains(queryStr)
								|| a.ATTRIBUTE6.Contains(queryStr)
								|| a.ATTRIBUTE7.Contains(queryStr)
								|| a.ATTRIBUTE8.Contains(queryStr)
								|| a.PARENT_LPN.Contains(queryStr)
								|| a.REFERENCE_ID.Contains(queryStr)
								
								|| a.REFERENCE_NUM_TYPE.Contains(queryStr)
								
								|| a.PROCESS_STAMP.Contains(queryStr)
								|| a.UPLOAD_INTERFACE_FLAG.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL> CreateModelList(ref IQueryable<Apps.Models.TRANSFER_ORDER_DETAIL> queryData)
		{

			List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL
											  {
													INTERNAL_TRANSFER_LINE_NUM = r.INTERNAL_TRANSFER_LINE_NUM,
													INTERNAL_TRANSFER_NUM = r.INTERNAL_TRANSFER_NUM,
													TRANSFER_ID = r.TRANSFER_ID,
													LINE_NUM = r.LINE_NUM,
													WAREHOUSE = r.WAREHOUSE,
													FROM_LOC = r.FROM_LOC,
													TO_LOC = r.TO_LOC,
													COMPANY = r.COMPANY,
													ITEM = r.ITEM,
													ITEM_DESC = r.ITEM_DESC,
													FROM_LPN = r.FROM_LPN,
													TO_LPN = r.TO_LPN,
													TOTAL_QTY = r.TOTAL_QTY,
													FROM_QTY = r.FROM_QTY,
													TO_QTY = r.TO_QTY,
													QUANTITY_UM = r.QUANTITY_UM,
													BEGIN_DATE_TIME = r.BEGIN_DATE_TIME,
													END_DATE_TIME = r.END_DATE_TIME,
													ATTRIBUTE_NUM = r.ATTRIBUTE_NUM,
													INVENTORY_STS = r.INVENTORY_STS,
													LOCATING_RULE = r.LOCATING_RULE,
													CREATED_USER = r.CREATED_USER,
													CREATED_DATE_TIME = r.CREATED_DATE_TIME,
													LAST_MODIFIED_USER = r.LAST_MODIFIED_USER,
													LAST_MODIFIED_DATE_TIME = r.LAST_MODIFIED_DATE_TIME,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													CART_ID = r.CART_ID,
													CART_POS = r.CART_POS,
													STATUS = r.STATUS,
													ATTRIBUTE1 = r.ATTRIBUTE1,
													ATTRIBUTE2 = r.ATTRIBUTE2,
													ATTRIBUTE3 = r.ATTRIBUTE3,
													ATTRIBUTE4 = r.ATTRIBUTE4,
													ATTRIBUTE5 = r.ATTRIBUTE5,
													ATTRIBUTE6 = r.ATTRIBUTE6,
													ATTRIBUTE7 = r.ATTRIBUTE7,
													ATTRIBUTE8 = r.ATTRIBUTE8,
													PARENT_LPN = r.PARENT_LPN,
													REFERENCE_ID = r.REFERENCE_ID,
													REFERENCE_NUM = r.REFERENCE_NUM,
													REFERENCE_NUM_TYPE = r.REFERENCE_NUM_TYPE,
													REFERENCE_LINE_NUM = r.REFERENCE_LINE_NUM,
													PROCESS_STAMP = r.PROCESS_STAMP,
													UPLOAD_INTERFACE_FLAG = r.UPLOAD_INTERFACE_FLAG,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL model)
		{
				Apps.Models.TRANSFER_ORDER_DETAIL entity = m_Rep.GetById(model.INTERNAL_TRANSFER_LINE_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.TRANSFER_ORDER_DETAIL();
			   				entity.INTERNAL_TRANSFER_LINE_NUM = model.INTERNAL_TRANSFER_LINE_NUM;
				entity.INTERNAL_TRANSFER_NUM = model.INTERNAL_TRANSFER_NUM;
				entity.TRANSFER_ID = model.TRANSFER_ID;
				entity.LINE_NUM = model.LINE_NUM;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.FROM_LOC = model.FROM_LOC;
				entity.TO_LOC = model.TO_LOC;
				entity.COMPANY = model.COMPANY;
				entity.ITEM = model.ITEM;
				entity.ITEM_DESC = model.ITEM_DESC;
				entity.FROM_LPN = model.FROM_LPN;
				entity.TO_LPN = model.TO_LPN;
				entity.TOTAL_QTY = model.TOTAL_QTY;
				entity.FROM_QTY = model.FROM_QTY;
				entity.TO_QTY = model.TO_QTY;
				entity.QUANTITY_UM = model.QUANTITY_UM;
				entity.BEGIN_DATE_TIME = model.BEGIN_DATE_TIME;
				entity.END_DATE_TIME = model.END_DATE_TIME;
				entity.ATTRIBUTE_NUM = model.ATTRIBUTE_NUM;
				entity.INVENTORY_STS = model.INVENTORY_STS;
				entity.LOCATING_RULE = model.LOCATING_RULE;
				entity.CREATED_USER = model.CREATED_USER;
				entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
				entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
				entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.CART_ID = model.CART_ID;
				entity.CART_POS = model.CART_POS;
				entity.STATUS = model.STATUS;
				entity.ATTRIBUTE1 = model.ATTRIBUTE1;
				entity.ATTRIBUTE2 = model.ATTRIBUTE2;
				entity.ATTRIBUTE3 = model.ATTRIBUTE3;
				entity.ATTRIBUTE4 = model.ATTRIBUTE4;
				entity.ATTRIBUTE5 = model.ATTRIBUTE5;
				entity.ATTRIBUTE6 = model.ATTRIBUTE6;
				entity.ATTRIBUTE7 = model.ATTRIBUTE7;
				entity.ATTRIBUTE8 = model.ATTRIBUTE8;
				entity.PARENT_LPN = model.PARENT_LPN;
				entity.REFERENCE_ID = model.REFERENCE_ID;
				entity.REFERENCE_NUM = model.REFERENCE_NUM;
				entity.REFERENCE_NUM_TYPE = model.REFERENCE_NUM_TYPE;
				entity.REFERENCE_LINE_NUM = model.REFERENCE_LINE_NUM;
				entity.PROCESS_STAMP = model.PROCESS_STAMP;
				entity.UPLOAD_INTERFACE_FLAG = model.UPLOAD_INTERFACE_FLAG;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL model,params string[] updateProperties)
		{
				Apps.Models.TRANSFER_ORDER_DETAIL entity = m_Rep.GetById(model.INTERNAL_TRANSFER_LINE_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_TRANSFER_LINE_NUM = model.INTERNAL_TRANSFER_LINE_NUM;
											entity.INTERNAL_TRANSFER_NUM = model.INTERNAL_TRANSFER_NUM;
											entity.TRANSFER_ID = model.TRANSFER_ID;
											entity.LINE_NUM = model.LINE_NUM;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.FROM_LOC = model.FROM_LOC;
											entity.TO_LOC = model.TO_LOC;
											entity.COMPANY = model.COMPANY;
											entity.ITEM = model.ITEM;
											entity.ITEM_DESC = model.ITEM_DESC;
											entity.FROM_LPN = model.FROM_LPN;
											entity.TO_LPN = model.TO_LPN;
											entity.TOTAL_QTY = model.TOTAL_QTY;
											entity.FROM_QTY = model.FROM_QTY;
											entity.TO_QTY = model.TO_QTY;
											entity.QUANTITY_UM = model.QUANTITY_UM;
											entity.BEGIN_DATE_TIME = model.BEGIN_DATE_TIME;
											entity.END_DATE_TIME = model.END_DATE_TIME;
											entity.ATTRIBUTE_NUM = model.ATTRIBUTE_NUM;
											entity.INVENTORY_STS = model.INVENTORY_STS;
											entity.LOCATING_RULE = model.LOCATING_RULE;
											entity.CREATED_USER = model.CREATED_USER;
											entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
											entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
											entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.CART_ID = model.CART_ID;
											entity.CART_POS = model.CART_POS;
											entity.STATUS = model.STATUS;
											entity.ATTRIBUTE1 = model.ATTRIBUTE1;
											entity.ATTRIBUTE2 = model.ATTRIBUTE2;
											entity.ATTRIBUTE3 = model.ATTRIBUTE3;
											entity.ATTRIBUTE4 = model.ATTRIBUTE4;
											entity.ATTRIBUTE5 = model.ATTRIBUTE5;
											entity.ATTRIBUTE6 = model.ATTRIBUTE6;
											entity.ATTRIBUTE7 = model.ATTRIBUTE7;
											entity.ATTRIBUTE8 = model.ATTRIBUTE8;
											entity.PARENT_LPN = model.PARENT_LPN;
											entity.REFERENCE_ID = model.REFERENCE_ID;
											entity.REFERENCE_NUM = model.REFERENCE_NUM;
											entity.REFERENCE_NUM_TYPE = model.REFERENCE_NUM_TYPE;
											entity.REFERENCE_LINE_NUM = model.REFERENCE_LINE_NUM;
											entity.PROCESS_STAMP = model.PROCESS_STAMP;
											entity.UPLOAD_INTERFACE_FLAG = model.UPLOAD_INTERFACE_FLAG;
									}else{
					
						Type type = typeof(Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL);
						Type typeE = typeof(Apps.Models.TRANSFER_ORDER_DETAIL);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL GetById(string id)
		{
			Apps.Models.TRANSFER_ORDER_DETAIL entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//TRANSFER_ORDER_DETAIL entity = m_Rep.GetById(id);
				Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL model = new Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_MODEL();
							  				model.INTERNAL_TRANSFER_LINE_NUM = entity.INTERNAL_TRANSFER_LINE_NUM;
				model.INTERNAL_TRANSFER_NUM = entity.INTERNAL_TRANSFER_NUM;
				model.TRANSFER_ID = entity.TRANSFER_ID;
				model.LINE_NUM = entity.LINE_NUM;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.FROM_LOC = entity.FROM_LOC;
				model.TO_LOC = entity.TO_LOC;
				model.COMPANY = entity.COMPANY;
				model.ITEM = entity.ITEM;
				model.ITEM_DESC = entity.ITEM_DESC;
				model.FROM_LPN = entity.FROM_LPN;
				model.TO_LPN = entity.TO_LPN;
				model.TOTAL_QTY = entity.TOTAL_QTY;
				model.FROM_QTY = entity.FROM_QTY;
				model.TO_QTY = entity.TO_QTY;
				model.QUANTITY_UM = entity.QUANTITY_UM;
				model.BEGIN_DATE_TIME = entity.BEGIN_DATE_TIME;
				model.END_DATE_TIME = entity.END_DATE_TIME;
				model.ATTRIBUTE_NUM = entity.ATTRIBUTE_NUM;
				model.INVENTORY_STS = entity.INVENTORY_STS;
				model.LOCATING_RULE = entity.LOCATING_RULE;
				model.CREATED_USER = entity.CREATED_USER;
				model.CREATED_DATE_TIME = entity.CREATED_DATE_TIME;
				model.LAST_MODIFIED_USER = entity.LAST_MODIFIED_USER;
				model.LAST_MODIFIED_DATE_TIME = entity.LAST_MODIFIED_DATE_TIME;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.CART_ID = entity.CART_ID;
				model.CART_POS = entity.CART_POS;
				model.STATUS = entity.STATUS;
				model.ATTRIBUTE1 = entity.ATTRIBUTE1;
				model.ATTRIBUTE2 = entity.ATTRIBUTE2;
				model.ATTRIBUTE3 = entity.ATTRIBUTE3;
				model.ATTRIBUTE4 = entity.ATTRIBUTE4;
				model.ATTRIBUTE5 = entity.ATTRIBUTE5;
				model.ATTRIBUTE6 = entity.ATTRIBUTE6;
				model.ATTRIBUTE7 = entity.ATTRIBUTE7;
				model.ATTRIBUTE8 = entity.ATTRIBUTE8;
				model.PARENT_LPN = entity.PARENT_LPN;
				model.REFERENCE_ID = entity.REFERENCE_ID;
				model.REFERENCE_NUM = entity.REFERENCE_NUM;
				model.REFERENCE_NUM_TYPE = entity.REFERENCE_NUM_TYPE;
				model.REFERENCE_LINE_NUM = entity.REFERENCE_LINE_NUM;
				model.PROCESS_STAMP = entity.PROCESS_STAMP;
				model.UPLOAD_INTERFACE_FLAG = entity.UPLOAD_INTERFACE_FLAG;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
