//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.DYNAMIC
{
	public class Virtual_DYNAMIC_CALLING_DETAIL_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.DYNAMIC.IDYNAMIC_CALLING_DETAIL_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.DYNAMIC_CALLING_DETAIL;
			}
		}
		

		public virtual List<Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL> GetList(Expression<Func<Apps.Models.DYNAMIC_CALLING_DETAIL, bool>> where = null){
		
				IQueryable<Apps.Models.DYNAMIC_CALLING_DETAIL> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.DYNAMIC_CALLING_DETAIL, bool>> where,Expression<Func<Apps.Models.DYNAMIC_CALLING_DETAIL, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.DYNAMIC_CALLING_DETAIL> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.DYNAMIC_CALLING_DETAIL, bool>> where = null)
		{

			IQueryable<Apps.Models.DYNAMIC_CALLING_DETAIL> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.RECORD_TYPE.Contains(queryStr)
								|| a.IDENTIFIER.Contains(queryStr)
								|| a.DESCRIPTION.Contains(queryStr)
								|| a.ASSEMBLY.Contains(queryStr)
								|| a.NAMESPACE.Contains(queryStr)
								|| a.CLASS.Contains(queryStr)
								|| a.METHOD.Contains(queryStr)
								|| a.SYSTEM_CREATED.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								
								
								|| a.USER_STAMP.Contains(queryStr)
								
								
								|| a.URI.Contains(queryStr)
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL> CreateModelList(ref IQueryable<Apps.Models.DYNAMIC_CALLING_DETAIL> queryData)
		{

			List<Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL
											  {
													RECORD_TYPE = r.RECORD_TYPE,
													IDENTIFIER = r.IDENTIFIER,
													DESCRIPTION = r.DESCRIPTION,
													ASSEMBLY = r.ASSEMBLY,
													NAMESPACE = r.NAMESPACE,
													CLASS = r.CLASS,
													METHOD = r.METHOD,
													SYSTEM_CREATED = r.SYSTEM_CREATED,
													ACTIVE = r.ACTIVE,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													USER_STAMP = r.USER_STAMP,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													INTERNAL_NUM = r.INTERNAL_NUM,
													URI = r.URI,
													ENDPOINT_TYPE = r.ENDPOINT_TYPE,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL model)
		{
				Apps.Models.DYNAMIC_CALLING_DETAIL entity = m_Rep.GetById(model.RECORD_TYPE);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.DYNAMIC_CALLING_DETAIL();
			   				entity.RECORD_TYPE = model.RECORD_TYPE;
				entity.IDENTIFIER = model.IDENTIFIER;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.ASSEMBLY = model.ASSEMBLY;
				entity.NAMESPACE = model.NAMESPACE;
				entity.CLASS = model.CLASS;
				entity.METHOD = model.METHOD;
				entity.SYSTEM_CREATED = model.SYSTEM_CREATED;
				entity.ACTIVE = model.ACTIVE;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.USER_STAMP = model.USER_STAMP;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.INTERNAL_NUM = model.INTERNAL_NUM;
				entity.URI = model.URI;
				entity.ENDPOINT_TYPE = model.ENDPOINT_TYPE;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL model,params string[] updateProperties)
		{
				Apps.Models.DYNAMIC_CALLING_DETAIL entity = m_Rep.GetById(model.RECORD_TYPE);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.RECORD_TYPE = model.RECORD_TYPE;
											entity.IDENTIFIER = model.IDENTIFIER;
											entity.DESCRIPTION = model.DESCRIPTION;
											entity.ASSEMBLY = model.ASSEMBLY;
											entity.NAMESPACE = model.NAMESPACE;
											entity.CLASS = model.CLASS;
											entity.METHOD = model.METHOD;
											entity.SYSTEM_CREATED = model.SYSTEM_CREATED;
											entity.ACTIVE = model.ACTIVE;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.USER_STAMP = model.USER_STAMP;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.INTERNAL_NUM = model.INTERNAL_NUM;
											entity.URI = model.URI;
											entity.ENDPOINT_TYPE = model.ENDPOINT_TYPE;
									}else{
					
						Type type = typeof(Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL);
						Type typeE = typeof(Apps.Models.DYNAMIC_CALLING_DETAIL);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL GetById(string id)
		{
			Apps.Models.DYNAMIC_CALLING_DETAIL entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//DYNAMIC_CALLING_DETAIL entity = m_Rep.GetById(id);
				Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL model = new Apps.Models.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_MODEL();
							  				model.RECORD_TYPE = entity.RECORD_TYPE;
				model.IDENTIFIER = entity.IDENTIFIER;
				model.DESCRIPTION = entity.DESCRIPTION;
				model.ASSEMBLY = entity.ASSEMBLY;
				model.NAMESPACE = entity.NAMESPACE;
				model.CLASS = entity.CLASS;
				model.METHOD = entity.METHOD;
				model.SYSTEM_CREATED = entity.SYSTEM_CREATED;
				model.ACTIVE = entity.ACTIVE;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.USER_STAMP = entity.USER_STAMP;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.INTERNAL_NUM = entity.INTERNAL_NUM;
				model.URI = entity.URI;
				model.ENDPOINT_TYPE = entity.ENDPOINT_TYPE;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
