//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.TRANSFER
{
	public class Virtual_TRANSFER_ORDER_HEADER_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_HEADER_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.TRANSFER_ORDER_HEADER;
			}
		}
		

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL> GetList(Expression<Func<Apps.Models.TRANSFER_ORDER_HEADER, bool>> where = null){
		
				IQueryable<Apps.Models.TRANSFER_ORDER_HEADER> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.TRANSFER_ORDER_HEADER, bool>> where,Expression<Func<Apps.Models.TRANSFER_ORDER_HEADER, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.TRANSFER_ORDER_HEADER> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.TRANSFER_ORDER_HEADER, bool>> where = null)
		{

			IQueryable<Apps.Models.TRANSFER_ORDER_HEADER> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.TRANSFER_ID.Contains(queryStr)
								
								|| a.CART_ID.Contains(queryStr)
								
								
								|| a.CREATED_USER.Contains(queryStr)
								
								|| a.LAST_MODIFIED_USER.Contains(queryStr)
								
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								|| a.WAREHOUSE.Contains(queryStr)
								|| a.COMPANY.Contains(queryStr)
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL> CreateModelList(ref IQueryable<Apps.Models.TRANSFER_ORDER_HEADER> queryData)
		{

			List<Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL
											  {
													INTERNAL_TRANSFER_NUM = r.INTERNAL_TRANSFER_NUM,
													TRANSFER_ID = r.TRANSFER_ID,
													LEADING_STS = r.LEADING_STS,
													CART_ID = r.CART_ID,
													BEGIN_DATE_TIME = r.BEGIN_DATE_TIME,
													END_DATE_TIME = r.END_DATE_TIME,
													CREATED_USER = r.CREATED_USER,
													CREATED_DATE_TIME = r.CREATED_DATE_TIME,
													LAST_MODIFIED_USER = r.LAST_MODIFIED_USER,
													LAST_MODIFIED_DATE_TIME = r.LAST_MODIFIED_DATE_TIME,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													WAREHOUSE = r.WAREHOUSE,
													COMPANY = r.COMPANY,
													TRAILING_STS = r.TRAILING_STS,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL model)
		{
				Apps.Models.TRANSFER_ORDER_HEADER entity = m_Rep.GetById(model.INTERNAL_TRANSFER_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.TRANSFER_ORDER_HEADER();
			   				entity.INTERNAL_TRANSFER_NUM = model.INTERNAL_TRANSFER_NUM;
				entity.TRANSFER_ID = model.TRANSFER_ID;
				entity.LEADING_STS = model.LEADING_STS;
				entity.CART_ID = model.CART_ID;
				entity.BEGIN_DATE_TIME = model.BEGIN_DATE_TIME;
				entity.END_DATE_TIME = model.END_DATE_TIME;
				entity.CREATED_USER = model.CREATED_USER;
				entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
				entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
				entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.COMPANY = model.COMPANY;
				entity.TRAILING_STS = model.TRAILING_STS;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL model,params string[] updateProperties)
		{
				Apps.Models.TRANSFER_ORDER_HEADER entity = m_Rep.GetById(model.INTERNAL_TRANSFER_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_TRANSFER_NUM = model.INTERNAL_TRANSFER_NUM;
											entity.TRANSFER_ID = model.TRANSFER_ID;
											entity.LEADING_STS = model.LEADING_STS;
											entity.CART_ID = model.CART_ID;
											entity.BEGIN_DATE_TIME = model.BEGIN_DATE_TIME;
											entity.END_DATE_TIME = model.END_DATE_TIME;
											entity.CREATED_USER = model.CREATED_USER;
											entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
											entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
											entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.COMPANY = model.COMPANY;
											entity.TRAILING_STS = model.TRAILING_STS;
									}else{
					
						Type type = typeof(Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL);
						Type typeE = typeof(Apps.Models.TRANSFER_ORDER_HEADER);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL GetById(string id)
		{
			Apps.Models.TRANSFER_ORDER_HEADER entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//TRANSFER_ORDER_HEADER entity = m_Rep.GetById(id);
				Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL model = new Apps.Models.SCV.TRANSFER.TRANSFER_ORDER_HEADER_MODEL();
							  				model.INTERNAL_TRANSFER_NUM = entity.INTERNAL_TRANSFER_NUM;
				model.TRANSFER_ID = entity.TRANSFER_ID;
				model.LEADING_STS = entity.LEADING_STS;
				model.CART_ID = entity.CART_ID;
				model.BEGIN_DATE_TIME = entity.BEGIN_DATE_TIME;
				model.END_DATE_TIME = entity.END_DATE_TIME;
				model.CREATED_USER = entity.CREATED_USER;
				model.CREATED_DATE_TIME = entity.CREATED_DATE_TIME;
				model.LAST_MODIFIED_USER = entity.LAST_MODIFIED_USER;
				model.LAST_MODIFIED_DATE_TIME = entity.LAST_MODIFIED_DATE_TIME;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.COMPANY = entity.COMPANY;
				model.TRAILING_STS = entity.TRAILING_STS;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
