//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.REPLENISHMENT
{
	public class Virtual_REPLENISHMENT_MASTER_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.REPLENISHMENT.IREPLENISHMENT_MASTER_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.REPLENISHMENT_MASTER;
			}
		}
		

		public virtual List<Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL> GetList(Expression<Func<Apps.Models.REPLENISHMENT_MASTER, bool>> where = null){
		
				IQueryable<Apps.Models.REPLENISHMENT_MASTER> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.REPLENISHMENT_MASTER, bool>> where,Expression<Func<Apps.Models.REPLENISHMENT_MASTER, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.REPLENISHMENT_MASTER> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.REPLENISHMENT_MASTER, bool>> where = null)
		{

			IQueryable<Apps.Models.REPLENISHMENT_MASTER> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.MASTER_NAME.Contains(queryStr)
								|| a.DESCRIPTION.Contains(queryStr)
								|| a.ITEM_SEL.Contains(queryStr)
								|| a.LOCATION_SEL.Contains(queryStr)
								|| a.ALLOCATION_RULE.Contains(queryStr)
								|| a.LOCATING_RULE.Contains(queryStr)
								|| a.REPLENISH_MODE.Contains(queryStr)
								|| a.REPLENISH_UM.Contains(queryStr)
								|| a.STRATEGY.Contains(queryStr)
								|| a.IN_PROCESS.Contains(queryStr)
								
								
								
								
								
								
								|| a.ACTIVE.Contains(queryStr)
								|| a.USER_STAMP.Contains(queryStr)
								
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL> CreateModelList(ref IQueryable<Apps.Models.REPLENISHMENT_MASTER> queryData)
		{

			List<Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL
											  {
													INTERNAL_NUM = r.INTERNAL_NUM,
													MASTER_NAME = r.MASTER_NAME,
													DESCRIPTION = r.DESCRIPTION,
													ITEM_SEL = r.ITEM_SEL,
													LOCATION_SEL = r.LOCATION_SEL,
													ALLOCATION_RULE = r.ALLOCATION_RULE,
													LOCATING_RULE = r.LOCATING_RULE,
													REPLENISH_MODE = r.REPLENISH_MODE,
													REPLENISH_UM = r.REPLENISH_UM,
													STRATEGY = r.STRATEGY,
													IN_PROCESS = r.IN_PROCESS,
													PRIORITY = r.PRIORITY,
													MAX_ITEMS = r.MAX_ITEMS,
													MAX_QTY = r.MAX_QTY,
													MAX_LINES = r.MAX_LINES,
													MAX_WEIGHT = r.MAX_WEIGHT,
													MAX_VOLUME = r.MAX_VOLUME,
													ACTIVE = r.ACTIVE,
													USER_STAMP = r.USER_STAMP,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL model)
		{
				Apps.Models.REPLENISHMENT_MASTER entity = m_Rep.GetById(model.INTERNAL_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.REPLENISHMENT_MASTER();
			   				entity.INTERNAL_NUM = model.INTERNAL_NUM;
				entity.MASTER_NAME = model.MASTER_NAME;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.ITEM_SEL = model.ITEM_SEL;
				entity.LOCATION_SEL = model.LOCATION_SEL;
				entity.ALLOCATION_RULE = model.ALLOCATION_RULE;
				entity.LOCATING_RULE = model.LOCATING_RULE;
				entity.REPLENISH_MODE = model.REPLENISH_MODE;
				entity.REPLENISH_UM = model.REPLENISH_UM;
				entity.STRATEGY = model.STRATEGY;
				entity.IN_PROCESS = model.IN_PROCESS;
				entity.PRIORITY = model.PRIORITY;
				entity.MAX_ITEMS = model.MAX_ITEMS;
				entity.MAX_QTY = model.MAX_QTY;
				entity.MAX_LINES = model.MAX_LINES;
				entity.MAX_WEIGHT = model.MAX_WEIGHT;
				entity.MAX_VOLUME = model.MAX_VOLUME;
				entity.ACTIVE = model.ACTIVE;
				entity.USER_STAMP = model.USER_STAMP;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL model,params string[] updateProperties)
		{
				Apps.Models.REPLENISHMENT_MASTER entity = m_Rep.GetById(model.INTERNAL_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_NUM = model.INTERNAL_NUM;
											entity.MASTER_NAME = model.MASTER_NAME;
											entity.DESCRIPTION = model.DESCRIPTION;
											entity.ITEM_SEL = model.ITEM_SEL;
											entity.LOCATION_SEL = model.LOCATION_SEL;
											entity.ALLOCATION_RULE = model.ALLOCATION_RULE;
											entity.LOCATING_RULE = model.LOCATING_RULE;
											entity.REPLENISH_MODE = model.REPLENISH_MODE;
											entity.REPLENISH_UM = model.REPLENISH_UM;
											entity.STRATEGY = model.STRATEGY;
											entity.IN_PROCESS = model.IN_PROCESS;
											entity.PRIORITY = model.PRIORITY;
											entity.MAX_ITEMS = model.MAX_ITEMS;
											entity.MAX_QTY = model.MAX_QTY;
											entity.MAX_LINES = model.MAX_LINES;
											entity.MAX_WEIGHT = model.MAX_WEIGHT;
											entity.MAX_VOLUME = model.MAX_VOLUME;
											entity.ACTIVE = model.ACTIVE;
											entity.USER_STAMP = model.USER_STAMP;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
									}else{
					
						Type type = typeof(Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL);
						Type typeE = typeof(Apps.Models.REPLENISHMENT_MASTER);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL GetById(string id)
		{
			Apps.Models.REPLENISHMENT_MASTER entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//REPLENISHMENT_MASTER entity = m_Rep.GetById(id);
				Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL model = new Apps.Models.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_MODEL();
							  				model.INTERNAL_NUM = entity.INTERNAL_NUM;
				model.MASTER_NAME = entity.MASTER_NAME;
				model.DESCRIPTION = entity.DESCRIPTION;
				model.ITEM_SEL = entity.ITEM_SEL;
				model.LOCATION_SEL = entity.LOCATION_SEL;
				model.ALLOCATION_RULE = entity.ALLOCATION_RULE;
				model.LOCATING_RULE = entity.LOCATING_RULE;
				model.REPLENISH_MODE = entity.REPLENISH_MODE;
				model.REPLENISH_UM = entity.REPLENISH_UM;
				model.STRATEGY = entity.STRATEGY;
				model.IN_PROCESS = entity.IN_PROCESS;
				model.PRIORITY = entity.PRIORITY;
				model.MAX_ITEMS = entity.MAX_ITEMS;
				model.MAX_QTY = entity.MAX_QTY;
				model.MAX_LINES = entity.MAX_LINES;
				model.MAX_WEIGHT = entity.MAX_WEIGHT;
				model.MAX_VOLUME = entity.MAX_VOLUME;
				model.ACTIVE = entity.ACTIVE;
				model.USER_STAMP = entity.USER_STAMP;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
