//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.SHIPPING
{
	public class Virtual_SHIPPING_CONTAINER_HIS_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.SHIPPING.ISHIPPING_CONTAINER_HIS_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.SHIPPING_CONTAINER_HIS;
			}
		}
		

		public virtual List<Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL> GetList(Expression<Func<Apps.Models.SHIPPING_CONTAINER_HIS, bool>> where = null){
		
				IQueryable<Apps.Models.SHIPPING_CONTAINER_HIS> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.SHIPPING_CONTAINER_HIS, bool>> where,Expression<Func<Apps.Models.SHIPPING_CONTAINER_HIS, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.SHIPPING_CONTAINER_HIS> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.SHIPPING_CONTAINER_HIS, bool>> where = null)
		{

			IQueryable<Apps.Models.SHIPPING_CONTAINER_HIS> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.ID.Contains(queryStr)
								
								|| a.CONTAINER_ID.Contains(queryStr)
								
								|| a.WEIGHT_NUM.Contains(queryStr)
								|| a.UPDATE_USER.Contains(queryStr)
								
								|| a.UPDATE_USERNAME.Contains(queryStr)
								|| a.UPDATE_USERTRUENAME.Contains(queryStr)
								|| a.TRACKING_NUMBER.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL> CreateModelList(ref IQueryable<Apps.Models.SHIPPING_CONTAINER_HIS> queryData)
		{

			List<Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL
											  {
													ID = r.ID,
													INTERNAL_CONTAINER_NUM = r.INTERNAL_CONTAINER_NUM,
													CONTAINER_ID = r.CONTAINER_ID,
													WEIGHT = r.WEIGHT,
													WEIGHT_NUM = r.WEIGHT_NUM,
													UPDATE_USER = r.UPDATE_USER,
													UPDATE_DATATIME = r.UPDATE_DATATIME,
													UPDATE_USERNAME = r.UPDATE_USERNAME,
													UPDATE_USERTRUENAME = r.UPDATE_USERTRUENAME,
													TRACKING_NUMBER = r.TRACKING_NUMBER,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL model)
		{
				Apps.Models.SHIPPING_CONTAINER_HIS entity = m_Rep.GetById(model.ID);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.SHIPPING_CONTAINER_HIS();
			   				entity.ID = model.ID;
				entity.INTERNAL_CONTAINER_NUM = model.INTERNAL_CONTAINER_NUM;
				entity.CONTAINER_ID = model.CONTAINER_ID;
				entity.WEIGHT = model.WEIGHT;
				entity.WEIGHT_NUM = model.WEIGHT_NUM;
				entity.UPDATE_USER = model.UPDATE_USER;
				entity.UPDATE_DATATIME = model.UPDATE_DATATIME;
				entity.UPDATE_USERNAME = model.UPDATE_USERNAME;
				entity.UPDATE_USERTRUENAME = model.UPDATE_USERTRUENAME;
				entity.TRACKING_NUMBER = model.TRACKING_NUMBER;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL model,params string[] updateProperties)
		{
				Apps.Models.SHIPPING_CONTAINER_HIS entity = m_Rep.GetById(model.ID);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.ID = model.ID;
											entity.INTERNAL_CONTAINER_NUM = model.INTERNAL_CONTAINER_NUM;
											entity.CONTAINER_ID = model.CONTAINER_ID;
											entity.WEIGHT = model.WEIGHT;
											entity.WEIGHT_NUM = model.WEIGHT_NUM;
											entity.UPDATE_USER = model.UPDATE_USER;
											entity.UPDATE_DATATIME = model.UPDATE_DATATIME;
											entity.UPDATE_USERNAME = model.UPDATE_USERNAME;
											entity.UPDATE_USERTRUENAME = model.UPDATE_USERTRUENAME;
											entity.TRACKING_NUMBER = model.TRACKING_NUMBER;
									}else{
					
						Type type = typeof(Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL);
						Type typeE = typeof(Apps.Models.SHIPPING_CONTAINER_HIS);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL GetById(string id)
		{
			Apps.Models.SHIPPING_CONTAINER_HIS entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//SHIPPING_CONTAINER_HIS entity = m_Rep.GetById(id);
				Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL model = new Apps.Models.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_MODEL();
							  				model.ID = entity.ID;
				model.INTERNAL_CONTAINER_NUM = entity.INTERNAL_CONTAINER_NUM;
				model.CONTAINER_ID = entity.CONTAINER_ID;
				model.WEIGHT = entity.WEIGHT;
				model.WEIGHT_NUM = entity.WEIGHT_NUM;
				model.UPDATE_USER = entity.UPDATE_USER;
				model.UPDATE_DATATIME = entity.UPDATE_DATATIME;
				model.UPDATE_USERNAME = entity.UPDATE_USERNAME;
				model.UPDATE_USERTRUENAME = entity.UPDATE_USERTRUENAME;
				model.TRACKING_NUMBER = entity.TRACKING_NUMBER;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
