//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.RETURNED
{
	public class Virtual_RETURNED_PACKAGE_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.RETURNED.IRETURNED_PACKAGE_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.RETURNED_PACKAGE;
			}
		}
		

		public virtual List<Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL> GetList(Expression<Func<Apps.Models.RETURNED_PACKAGE, bool>> where = null){
		
				IQueryable<Apps.Models.RETURNED_PACKAGE> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.RETURNED_PACKAGE, bool>> where,Expression<Func<Apps.Models.RETURNED_PACKAGE, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.RETURNED_PACKAGE> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.RETURNED_PACKAGE, bool>> where = null)
		{

			IQueryable<Apps.Models.RETURNED_PACKAGE> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.PACKAGE_ID.Contains(queryStr)
								
								|| a.CART_ID.Contains(queryStr)
								|| a.CART_POS.Contains(queryStr)
								|| a.RETURN_TRACKING_NUMBER.Contains(queryStr)
								|| a.SHIP_TRACKING_NUMBER.Contains(queryStr)
								|| a.RECEIPT_ID.Contains(queryStr)
								|| a.SHIPMENT_ID.Contains(queryStr)
								|| a.SHIP_FROM.Contains(queryStr)
								|| a.SHIP_FROM_PHONE_NUM.Contains(queryStr)
								|| a.RETURN_REASON.Contains(queryStr)
								|| a.CREATED_USER.Contains(queryStr)
								
								|| a.LAST_MODIFIED_USER.Contains(queryStr)
								
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL> CreateModelList(ref IQueryable<Apps.Models.RETURNED_PACKAGE> queryData)
		{

			List<Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL
											  {
													INTERNAL_PACKAGE_NUM = r.INTERNAL_PACKAGE_NUM,
													PACKAGE_ID = r.PACKAGE_ID,
													STATUS = r.STATUS,
													CART_ID = r.CART_ID,
													CART_POS = r.CART_POS,
													RETURN_TRACKING_NUMBER = r.RETURN_TRACKING_NUMBER,
													SHIP_TRACKING_NUMBER = r.SHIP_TRACKING_NUMBER,
													RECEIPT_ID = r.RECEIPT_ID,
													SHIPMENT_ID = r.SHIPMENT_ID,
													SHIP_FROM = r.SHIP_FROM,
													SHIP_FROM_PHONE_NUM = r.SHIP_FROM_PHONE_NUM,
													RETURN_REASON = r.RETURN_REASON,
													CREATED_USER = r.CREATED_USER,
													CREATED_DATE_TIME = r.CREATED_DATE_TIME,
													LAST_MODIFIED_USER = r.LAST_MODIFIED_USER,
													LAST_MODIFIED_DATE_TIME = r.LAST_MODIFIED_DATE_TIME,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL model)
		{
				Apps.Models.RETURNED_PACKAGE entity = m_Rep.GetById(model.INTERNAL_PACKAGE_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.RETURNED_PACKAGE();
			   				entity.INTERNAL_PACKAGE_NUM = model.INTERNAL_PACKAGE_NUM;
				entity.PACKAGE_ID = model.PACKAGE_ID;
				entity.STATUS = model.STATUS;
				entity.CART_ID = model.CART_ID;
				entity.CART_POS = model.CART_POS;
				entity.RETURN_TRACKING_NUMBER = model.RETURN_TRACKING_NUMBER;
				entity.SHIP_TRACKING_NUMBER = model.SHIP_TRACKING_NUMBER;
				entity.RECEIPT_ID = model.RECEIPT_ID;
				entity.SHIPMENT_ID = model.SHIPMENT_ID;
				entity.SHIP_FROM = model.SHIP_FROM;
				entity.SHIP_FROM_PHONE_NUM = model.SHIP_FROM_PHONE_NUM;
				entity.RETURN_REASON = model.RETURN_REASON;
				entity.CREATED_USER = model.CREATED_USER;
				entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
				entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
				entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL model,params string[] updateProperties)
		{
				Apps.Models.RETURNED_PACKAGE entity = m_Rep.GetById(model.INTERNAL_PACKAGE_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_PACKAGE_NUM = model.INTERNAL_PACKAGE_NUM;
											entity.PACKAGE_ID = model.PACKAGE_ID;
											entity.STATUS = model.STATUS;
											entity.CART_ID = model.CART_ID;
											entity.CART_POS = model.CART_POS;
											entity.RETURN_TRACKING_NUMBER = model.RETURN_TRACKING_NUMBER;
											entity.SHIP_TRACKING_NUMBER = model.SHIP_TRACKING_NUMBER;
											entity.RECEIPT_ID = model.RECEIPT_ID;
											entity.SHIPMENT_ID = model.SHIPMENT_ID;
											entity.SHIP_FROM = model.SHIP_FROM;
											entity.SHIP_FROM_PHONE_NUM = model.SHIP_FROM_PHONE_NUM;
											entity.RETURN_REASON = model.RETURN_REASON;
											entity.CREATED_USER = model.CREATED_USER;
											entity.CREATED_DATE_TIME = model.CREATED_DATE_TIME;
											entity.LAST_MODIFIED_USER = model.LAST_MODIFIED_USER;
											entity.LAST_MODIFIED_DATE_TIME = model.LAST_MODIFIED_DATE_TIME;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
									}else{
					
						Type type = typeof(Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL);
						Type typeE = typeof(Apps.Models.RETURNED_PACKAGE);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL GetById(string id)
		{
			Apps.Models.RETURNED_PACKAGE entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//RETURNED_PACKAGE entity = m_Rep.GetById(id);
				Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL model = new Apps.Models.SCV.RETURNED.RETURNED_PACKAGE_MODEL();
							  				model.INTERNAL_PACKAGE_NUM = entity.INTERNAL_PACKAGE_NUM;
				model.PACKAGE_ID = entity.PACKAGE_ID;
				model.STATUS = entity.STATUS;
				model.CART_ID = entity.CART_ID;
				model.CART_POS = entity.CART_POS;
				model.RETURN_TRACKING_NUMBER = entity.RETURN_TRACKING_NUMBER;
				model.SHIP_TRACKING_NUMBER = entity.SHIP_TRACKING_NUMBER;
				model.RECEIPT_ID = entity.RECEIPT_ID;
				model.SHIPMENT_ID = entity.SHIPMENT_ID;
				model.SHIP_FROM = entity.SHIP_FROM;
				model.SHIP_FROM_PHONE_NUM = entity.SHIP_FROM_PHONE_NUM;
				model.RETURN_REASON = entity.RETURN_REASON;
				model.CREATED_USER = entity.CREATED_USER;
				model.CREATED_DATE_TIME = entity.CREATED_DATE_TIME;
				model.LAST_MODIFIED_USER = entity.LAST_MODIFIED_USER;
				model.LAST_MODIFIED_DATE_TIME = entity.LAST_MODIFIED_DATE_TIME;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
