//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.AUDIT
{
	public class Virtual_AUDIT_LOG_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.AUDIT.IAUDIT_LOG_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.AUDIT_LOG;
			}
		}
		

		public virtual List<Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL> GetList(Expression<Func<Apps.Models.AUDIT_LOG, bool>> where = null){
		
				IQueryable<Apps.Models.AUDIT_LOG> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.AUDIT_LOG, bool>> where,Expression<Func<Apps.Models.AUDIT_LOG, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.AUDIT_LOG> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.AUDIT_LOG, bool>> where = null)
		{

			IQueryable<Apps.Models.AUDIT_LOG> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.WAREHOUSE.Contains(queryStr)
								|| a.MESSAGE.Contains(queryStr)
								
								|| a.USER_STAMP.Contains(queryStr)
								|| a.VALUE.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL> CreateModelList(ref IQueryable<Apps.Models.AUDIT_LOG> queryData)
		{

			List<Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL
											  {
													INTERNAL_ID = r.INTERNAL_ID,
													WAREHOUSE = r.WAREHOUSE,
													MESSAGE = r.MESSAGE,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													USER_STAMP = r.USER_STAMP,
													VALUE = r.VALUE,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL model)
		{
				Apps.Models.AUDIT_LOG entity = m_Rep.GetById(model.INTERNAL_ID);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.AUDIT_LOG();
			   				entity.INTERNAL_ID = model.INTERNAL_ID;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.MESSAGE = model.MESSAGE;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.USER_STAMP = model.USER_STAMP;
				entity.VALUE = model.VALUE;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL model,params string[] updateProperties)
		{
				Apps.Models.AUDIT_LOG entity = m_Rep.GetById(model.INTERNAL_ID);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_ID = model.INTERNAL_ID;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.MESSAGE = model.MESSAGE;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.USER_STAMP = model.USER_STAMP;
											entity.VALUE = model.VALUE;
									}else{
					
						Type type = typeof(Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL);
						Type typeE = typeof(Apps.Models.AUDIT_LOG);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL GetById(string id)
		{
			Apps.Models.AUDIT_LOG entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//AUDIT_LOG entity = m_Rep.GetById(id);
				Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL model = new Apps.Models.SCV.AUDIT.AUDIT_LOG_MODEL();
							  				model.INTERNAL_ID = entity.INTERNAL_ID;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.MESSAGE = entity.MESSAGE;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.USER_STAMP = entity.USER_STAMP;
				model.VALUE = entity.VALUE;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
