//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.AR
{
	public class Virtual_AR_UPLOAD_INVENTORY_TRANS_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.AR.IAR_UPLOAD_INVENTORY_TRANS_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.AR_UPLOAD_INVENTORY_TRANS;
			}
		}
		

		public virtual List<Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL> GetList(Expression<Func<Apps.Models.AR_UPLOAD_INVENTORY_TRANS, bool>> where = null){
		
				IQueryable<Apps.Models.AR_UPLOAD_INVENTORY_TRANS> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.AR_UPLOAD_INVENTORY_TRANS, bool>> where,Expression<Func<Apps.Models.AR_UPLOAD_INVENTORY_TRANS, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.AR_UPLOAD_INVENTORY_TRANS> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.AR_UPLOAD_INVENTORY_TRANS, bool>> where = null)
		{

			IQueryable<Apps.Models.AR_UPLOAD_INVENTORY_TRANS> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.INTERFACE_ACTION_CODE.Contains(queryStr)
								|| a.INTERFACE_CONDITION.Contains(queryStr)
								|| a.PROCESS_STAMP.Contains(queryStr)
								|| a.INTERFACE_ERROR.Contains(queryStr)
								|| a.COMPANY.Contains(queryStr)
								|| a.ITEM.Contains(queryStr)
								|| a.LOCATION.Contains(queryStr)
								|| a.ATTRIBUTE1.Contains(queryStr)
								|| a.ATTRIBUTE2.Contains(queryStr)
								|| a.ATTRIBUTE3.Contains(queryStr)
								|| a.ATTRIBUTE4.Contains(queryStr)
								|| a.ATTRIBUTE5.Contains(queryStr)
								|| a.ATTRIBUTE6.Contains(queryStr)
								|| a.ATTRIBUTE7.Contains(queryStr)
								|| a.ATTRIBUTE8.Contains(queryStr)
								
								|| a.QUANTITY_UM.Contains(queryStr)
								|| a.REFERENCE_ID.Contains(queryStr)
								
								|| a.REFERENCE_TYPE.Contains(queryStr)
								|| a.REFERENCE_NUM_TYPE.Contains(queryStr)
								|| a.TRANSACTION_TYPE.Contains(queryStr)
								|| a.USER_STAMP.Contains(queryStr)
								|| a.WAREHOUSE.Contains(queryStr)
								|| a.ZONE.Contains(queryStr)
								|| a.USER_DEF1.Contains(queryStr)
								|| a.USER_DEF2.Contains(queryStr)
								|| a.USER_DEF3.Contains(queryStr)
								|| a.USER_DEF4.Contains(queryStr)
								|| a.USER_DEF5.Contains(queryStr)
								|| a.USER_DEF6.Contains(queryStr)
								|| a.USER_DEF7.Contains(queryStr)
								|| a.USER_DEF8.Contains(queryStr)
								
								
								|| a.DIRECTION.Contains(queryStr)
								|| a.LPN.Contains(queryStr)
								|| a.BEFORE_INVENTORY_STS.Contains(queryStr)
								|| a.AFTER_INVENTORY_STS.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL> CreateModelList(ref IQueryable<Apps.Models.AR_UPLOAD_INVENTORY_TRANS> queryData)
		{

			List<Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL
											  {
													INTERFACE_RECORD_ID = r.INTERFACE_RECORD_ID,
													INTERFACE_ACTION_CODE = r.INTERFACE_ACTION_CODE,
													INTERFACE_CONDITION = r.INTERFACE_CONDITION,
													PROCESS_STAMP = r.PROCESS_STAMP,
													INTERFACE_ERROR = r.INTERFACE_ERROR,
													COMPANY = r.COMPANY,
													ITEM = r.ITEM,
													LOCATION = r.LOCATION,
													ATTRIBUTE1 = r.ATTRIBUTE1,
													ATTRIBUTE2 = r.ATTRIBUTE2,
													ATTRIBUTE3 = r.ATTRIBUTE3,
													ATTRIBUTE4 = r.ATTRIBUTE4,
													ATTRIBUTE5 = r.ATTRIBUTE5,
													ATTRIBUTE6 = r.ATTRIBUTE6,
													ATTRIBUTE7 = r.ATTRIBUTE7,
													ATTRIBUTE8 = r.ATTRIBUTE8,
													QUANTITY = r.QUANTITY,
													QUANTITY_UM = r.QUANTITY_UM,
													REFERENCE_ID = r.REFERENCE_ID,
													REFERENCE_LINE_NUM = r.REFERENCE_LINE_NUM,
													REFERENCE_TYPE = r.REFERENCE_TYPE,
													REFERENCE_NUM_TYPE = r.REFERENCE_NUM_TYPE,
													TRANSACTION_TYPE = r.TRANSACTION_TYPE,
													USER_STAMP = r.USER_STAMP,
													WAREHOUSE = r.WAREHOUSE,
													ZONE = r.ZONE,
													USER_DEF1 = r.USER_DEF1,
													USER_DEF2 = r.USER_DEF2,
													USER_DEF3 = r.USER_DEF3,
													USER_DEF4 = r.USER_DEF4,
													USER_DEF5 = r.USER_DEF5,
													USER_DEF6 = r.USER_DEF6,
													USER_DEF7 = r.USER_DEF7,
													USER_DEF8 = r.USER_DEF8,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
													ACTIVITY_DATE_TIME = r.ACTIVITY_DATE_TIME,
													DIRECTION = r.DIRECTION,
													LPN = r.LPN,
													BEFORE_INVENTORY_STS = r.BEFORE_INVENTORY_STS,
													AFTER_INVENTORY_STS = r.AFTER_INVENTORY_STS,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL model)
		{
				Apps.Models.AR_UPLOAD_INVENTORY_TRANS entity = m_Rep.GetById(model.INTERFACE_RECORD_ID);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.AR_UPLOAD_INVENTORY_TRANS();
			   				entity.INTERFACE_RECORD_ID = model.INTERFACE_RECORD_ID;
				entity.INTERFACE_ACTION_CODE = model.INTERFACE_ACTION_CODE;
				entity.INTERFACE_CONDITION = model.INTERFACE_CONDITION;
				entity.PROCESS_STAMP = model.PROCESS_STAMP;
				entity.INTERFACE_ERROR = model.INTERFACE_ERROR;
				entity.COMPANY = model.COMPANY;
				entity.ITEM = model.ITEM;
				entity.LOCATION = model.LOCATION;
				entity.ATTRIBUTE1 = model.ATTRIBUTE1;
				entity.ATTRIBUTE2 = model.ATTRIBUTE2;
				entity.ATTRIBUTE3 = model.ATTRIBUTE3;
				entity.ATTRIBUTE4 = model.ATTRIBUTE4;
				entity.ATTRIBUTE5 = model.ATTRIBUTE5;
				entity.ATTRIBUTE6 = model.ATTRIBUTE6;
				entity.ATTRIBUTE7 = model.ATTRIBUTE7;
				entity.ATTRIBUTE8 = model.ATTRIBUTE8;
				entity.QUANTITY = model.QUANTITY;
				entity.QUANTITY_UM = model.QUANTITY_UM;
				entity.REFERENCE_ID = model.REFERENCE_ID;
				entity.REFERENCE_LINE_NUM = model.REFERENCE_LINE_NUM;
				entity.REFERENCE_TYPE = model.REFERENCE_TYPE;
				entity.REFERENCE_NUM_TYPE = model.REFERENCE_NUM_TYPE;
				entity.TRANSACTION_TYPE = model.TRANSACTION_TYPE;
				entity.USER_STAMP = model.USER_STAMP;
				entity.WAREHOUSE = model.WAREHOUSE;
				entity.ZONE = model.ZONE;
				entity.USER_DEF1 = model.USER_DEF1;
				entity.USER_DEF2 = model.USER_DEF2;
				entity.USER_DEF3 = model.USER_DEF3;
				entity.USER_DEF4 = model.USER_DEF4;
				entity.USER_DEF5 = model.USER_DEF5;
				entity.USER_DEF6 = model.USER_DEF6;
				entity.USER_DEF7 = model.USER_DEF7;
				entity.USER_DEF8 = model.USER_DEF8;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
				entity.ACTIVITY_DATE_TIME = model.ACTIVITY_DATE_TIME;
				entity.DIRECTION = model.DIRECTION;
				entity.LPN = model.LPN;
				entity.BEFORE_INVENTORY_STS = model.BEFORE_INVENTORY_STS;
				entity.AFTER_INVENTORY_STS = model.AFTER_INVENTORY_STS;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL model,params string[] updateProperties)
		{
				Apps.Models.AR_UPLOAD_INVENTORY_TRANS entity = m_Rep.GetById(model.INTERFACE_RECORD_ID);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERFACE_RECORD_ID = model.INTERFACE_RECORD_ID;
											entity.INTERFACE_ACTION_CODE = model.INTERFACE_ACTION_CODE;
											entity.INTERFACE_CONDITION = model.INTERFACE_CONDITION;
											entity.PROCESS_STAMP = model.PROCESS_STAMP;
											entity.INTERFACE_ERROR = model.INTERFACE_ERROR;
											entity.COMPANY = model.COMPANY;
											entity.ITEM = model.ITEM;
											entity.LOCATION = model.LOCATION;
											entity.ATTRIBUTE1 = model.ATTRIBUTE1;
											entity.ATTRIBUTE2 = model.ATTRIBUTE2;
											entity.ATTRIBUTE3 = model.ATTRIBUTE3;
											entity.ATTRIBUTE4 = model.ATTRIBUTE4;
											entity.ATTRIBUTE5 = model.ATTRIBUTE5;
											entity.ATTRIBUTE6 = model.ATTRIBUTE6;
											entity.ATTRIBUTE7 = model.ATTRIBUTE7;
											entity.ATTRIBUTE8 = model.ATTRIBUTE8;
											entity.QUANTITY = model.QUANTITY;
											entity.QUANTITY_UM = model.QUANTITY_UM;
											entity.REFERENCE_ID = model.REFERENCE_ID;
											entity.REFERENCE_LINE_NUM = model.REFERENCE_LINE_NUM;
											entity.REFERENCE_TYPE = model.REFERENCE_TYPE;
											entity.REFERENCE_NUM_TYPE = model.REFERENCE_NUM_TYPE;
											entity.TRANSACTION_TYPE = model.TRANSACTION_TYPE;
											entity.USER_STAMP = model.USER_STAMP;
											entity.WAREHOUSE = model.WAREHOUSE;
											entity.ZONE = model.ZONE;
											entity.USER_DEF1 = model.USER_DEF1;
											entity.USER_DEF2 = model.USER_DEF2;
											entity.USER_DEF3 = model.USER_DEF3;
											entity.USER_DEF4 = model.USER_DEF4;
											entity.USER_DEF5 = model.USER_DEF5;
											entity.USER_DEF6 = model.USER_DEF6;
											entity.USER_DEF7 = model.USER_DEF7;
											entity.USER_DEF8 = model.USER_DEF8;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
											entity.ACTIVITY_DATE_TIME = model.ACTIVITY_DATE_TIME;
											entity.DIRECTION = model.DIRECTION;
											entity.LPN = model.LPN;
											entity.BEFORE_INVENTORY_STS = model.BEFORE_INVENTORY_STS;
											entity.AFTER_INVENTORY_STS = model.AFTER_INVENTORY_STS;
									}else{
					
						Type type = typeof(Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL);
						Type typeE = typeof(Apps.Models.AR_UPLOAD_INVENTORY_TRANS);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL GetById(string id)
		{
			Apps.Models.AR_UPLOAD_INVENTORY_TRANS entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//AR_UPLOAD_INVENTORY_TRANS entity = m_Rep.GetById(id);
				Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL model = new Apps.Models.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_MODEL();
							  				model.INTERFACE_RECORD_ID = entity.INTERFACE_RECORD_ID;
				model.INTERFACE_ACTION_CODE = entity.INTERFACE_ACTION_CODE;
				model.INTERFACE_CONDITION = entity.INTERFACE_CONDITION;
				model.PROCESS_STAMP = entity.PROCESS_STAMP;
				model.INTERFACE_ERROR = entity.INTERFACE_ERROR;
				model.COMPANY = entity.COMPANY;
				model.ITEM = entity.ITEM;
				model.LOCATION = entity.LOCATION;
				model.ATTRIBUTE1 = entity.ATTRIBUTE1;
				model.ATTRIBUTE2 = entity.ATTRIBUTE2;
				model.ATTRIBUTE3 = entity.ATTRIBUTE3;
				model.ATTRIBUTE4 = entity.ATTRIBUTE4;
				model.ATTRIBUTE5 = entity.ATTRIBUTE5;
				model.ATTRIBUTE6 = entity.ATTRIBUTE6;
				model.ATTRIBUTE7 = entity.ATTRIBUTE7;
				model.ATTRIBUTE8 = entity.ATTRIBUTE8;
				model.QUANTITY = entity.QUANTITY;
				model.QUANTITY_UM = entity.QUANTITY_UM;
				model.REFERENCE_ID = entity.REFERENCE_ID;
				model.REFERENCE_LINE_NUM = entity.REFERENCE_LINE_NUM;
				model.REFERENCE_TYPE = entity.REFERENCE_TYPE;
				model.REFERENCE_NUM_TYPE = entity.REFERENCE_NUM_TYPE;
				model.TRANSACTION_TYPE = entity.TRANSACTION_TYPE;
				model.USER_STAMP = entity.USER_STAMP;
				model.WAREHOUSE = entity.WAREHOUSE;
				model.ZONE = entity.ZONE;
				model.USER_DEF1 = entity.USER_DEF1;
				model.USER_DEF2 = entity.USER_DEF2;
				model.USER_DEF3 = entity.USER_DEF3;
				model.USER_DEF4 = entity.USER_DEF4;
				model.USER_DEF5 = entity.USER_DEF5;
				model.USER_DEF6 = entity.USER_DEF6;
				model.USER_DEF7 = entity.USER_DEF7;
				model.USER_DEF8 = entity.USER_DEF8;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
				model.ACTIVITY_DATE_TIME = entity.ACTIVITY_DATE_TIME;
				model.DIRECTION = entity.DIRECTION;
				model.LPN = entity.LPN;
				model.BEFORE_INVENTORY_STS = entity.BEFORE_INVENTORY_STS;
				model.AFTER_INVENTORY_STS = entity.AFTER_INVENTORY_STS;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
