//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.Sys
{
	public class Virtual_CUSTOMER_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.Sys.ICUSTOMER_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.CUSTOMER;
			}
		}
		

		public virtual List<Apps.Models.SCV.Sys.CUSTOMER_MODEL> GetList(Expression<Func<Apps.Models.CUSTOMER, bool>> where = null){
		
				IQueryable<Apps.Models.CUSTOMER> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.CUSTOMER_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.CUSTOMER, bool>> where,Expression<Func<Apps.Models.CUSTOMER, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.CUSTOMER> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.Sys.CUSTOMER_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.CUSTOMER, bool>> where = null)
		{

			IQueryable<Apps.Models.CUSTOMER> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								
								,a=>a.CUSTOMER_ID.Contains(queryStr)
								|| a.NAME.Contains(queryStr)
								|| a.ADDRESS1.Contains(queryStr)
								|| a.ADDRESS2.Contains(queryStr)
								|| a.CITY.Contains(queryStr)
								|| a.STATE.Contains(queryStr)
								|| a.COUNTRY.Contains(queryStr)
								|| a.POSTAL_CODE.Contains(queryStr)
								|| a.PARENT.Contains(queryStr)
								|| a.ATTENTION_TO.Contains(queryStr)
								|| a.PHONE_NUM.Contains(queryStr)
								|| a.FAX_NUM.Contains(queryStr)
								|| a.EMAIL.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								|| a.CARRIER.Contains(queryStr)
								|| a.USER_STAMP.Contains(queryStr)
								
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.Sys.CUSTOMER_MODEL> CreateModelList(ref IQueryable<Apps.Models.CUSTOMER> queryData)
		{

			List<Apps.Models.SCV.Sys.CUSTOMER_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.Sys.CUSTOMER_MODEL
											  {
													INTERNAL_CUSTOMER_NUM = r.INTERNAL_CUSTOMER_NUM,
													CUSTOMER_ID = r.CUSTOMER_ID,
													NAME = r.NAME,
													ADDRESS1 = r.ADDRESS1,
													ADDRESS2 = r.ADDRESS2,
													CITY = r.CITY,
													STATE = r.STATE,
													COUNTRY = r.COUNTRY,
													POSTAL_CODE = r.POSTAL_CODE,
													PARENT = r.PARENT,
													ATTENTION_TO = r.ATTENTION_TO,
													PHONE_NUM = r.PHONE_NUM,
													FAX_NUM = r.FAX_NUM,
													EMAIL = r.EMAIL,
													ACTIVE = r.ACTIVE,
													CARRIER = r.CARRIER,
													USER_STAMP = r.USER_STAMP,
													DATE_TIME_STAMP = r.DATE_TIME_STAMP,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.Sys.CUSTOMER_MODEL model)
		{
				Apps.Models.CUSTOMER entity = m_Rep.GetById(model.INTERNAL_CUSTOMER_NUM);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.CUSTOMER();
			   				entity.INTERNAL_CUSTOMER_NUM = model.INTERNAL_CUSTOMER_NUM;
				entity.CUSTOMER_ID = model.CUSTOMER_ID;
				entity.NAME = model.NAME;
				entity.ADDRESS1 = model.ADDRESS1;
				entity.ADDRESS2 = model.ADDRESS2;
				entity.CITY = model.CITY;
				entity.STATE = model.STATE;
				entity.COUNTRY = model.COUNTRY;
				entity.POSTAL_CODE = model.POSTAL_CODE;
				entity.PARENT = model.PARENT;
				entity.ATTENTION_TO = model.ATTENTION_TO;
				entity.PHONE_NUM = model.PHONE_NUM;
				entity.FAX_NUM = model.FAX_NUM;
				entity.EMAIL = model.EMAIL;
				entity.ACTIVE = model.ACTIVE;
				entity.CARRIER = model.CARRIER;
				entity.USER_STAMP = model.USER_STAMP;
				entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.Sys.CUSTOMER_MODEL model,params string[] updateProperties)
		{
				Apps.Models.CUSTOMER entity = m_Rep.GetById(model.INTERNAL_CUSTOMER_NUM);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.INTERNAL_CUSTOMER_NUM = model.INTERNAL_CUSTOMER_NUM;
											entity.CUSTOMER_ID = model.CUSTOMER_ID;
											entity.NAME = model.NAME;
											entity.ADDRESS1 = model.ADDRESS1;
											entity.ADDRESS2 = model.ADDRESS2;
											entity.CITY = model.CITY;
											entity.STATE = model.STATE;
											entity.COUNTRY = model.COUNTRY;
											entity.POSTAL_CODE = model.POSTAL_CODE;
											entity.PARENT = model.PARENT;
											entity.ATTENTION_TO = model.ATTENTION_TO;
											entity.PHONE_NUM = model.PHONE_NUM;
											entity.FAX_NUM = model.FAX_NUM;
											entity.EMAIL = model.EMAIL;
											entity.ACTIVE = model.ACTIVE;
											entity.CARRIER = model.CARRIER;
											entity.USER_STAMP = model.USER_STAMP;
											entity.DATE_TIME_STAMP = model.DATE_TIME_STAMP;
									}else{
					
						Type type = typeof(Apps.Models.SCV.Sys.CUSTOMER_MODEL);
						Type typeE = typeof(Apps.Models.CUSTOMER);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.Sys.CUSTOMER_MODEL GetById(string id)
		{
			Apps.Models.CUSTOMER entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//CUSTOMER entity = m_Rep.GetById(id);
				Apps.Models.SCV.Sys.CUSTOMER_MODEL model = new Apps.Models.SCV.Sys.CUSTOMER_MODEL();
							  				model.INTERNAL_CUSTOMER_NUM = entity.INTERNAL_CUSTOMER_NUM;
				model.CUSTOMER_ID = entity.CUSTOMER_ID;
				model.NAME = entity.NAME;
				model.ADDRESS1 = entity.ADDRESS1;
				model.ADDRESS2 = entity.ADDRESS2;
				model.CITY = entity.CITY;
				model.STATE = entity.STATE;
				model.COUNTRY = entity.COUNTRY;
				model.POSTAL_CODE = entity.POSTAL_CODE;
				model.PARENT = entity.PARENT;
				model.ATTENTION_TO = entity.ATTENTION_TO;
				model.PHONE_NUM = entity.PHONE_NUM;
				model.FAX_NUM = entity.FAX_NUM;
				model.EMAIL = entity.EMAIL;
				model.ACTIVE = entity.ACTIVE;
				model.CARRIER = entity.CARRIER;
				model.USER_STAMP = entity.USER_STAMP;
				model.DATE_TIME_STAMP = entity.DATE_TIME_STAMP;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
