//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.Locale;
using System.Linq.Expressions;
namespace Apps.Service.SCV.WAVE
{
	public class Virtual_WAVE_FLOW_HEADER_SERVICE
	{

		public Apps.IRepository.SCV.ISCVDBSession SCVDBSession{
			 get
			{
				return Service.SCV.SCVDBSessionFactory.GetDBSession();
			}
		}
	   
		public Apps.IRepository.SCV.WAVE.IWAVE_FLOW_HEADER_REPOSITORY m_Rep{
			 get
			{
				return SCVDBSession.WAVE_FLOW_HEADER;
			}
		}
		

		public virtual List<Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL> GetList(Expression<Func<Apps.Models.WAVE_FLOW_HEADER, bool>> where = null){
		
				IQueryable<Apps.Models.WAVE_FLOW_HEADER> queryData = m_Rep.GetList(where);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL> GetListSort<TKey>(Expression<Func<Apps.Models.WAVE_FLOW_HEADER, bool>> where,Expression<Func<Apps.Models.WAVE_FLOW_HEADER, TKey>>orderBy, bool isAsc = true){
		
				IQueryable<Apps.Models.WAVE_FLOW_HEADER> queryData = m_Rep.GetListSort(where, orderBy, isAsc);
				return CreateModelList(ref queryData);
		}

		public virtual List<Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL> GetList(ref GridPager pager, string queryStr,Expression<Func<Apps.Models.WAVE_FLOW_HEADER, bool>> where = null)
		{

			IQueryable<Apps.Models.WAVE_FLOW_HEADER> queryData;
			
			if (!string.IsNullOrWhiteSpace(queryStr))
			{
				queryData = m_Rep.GetList(where
								,a=>a.WAVE_FLOW.Contains(queryStr)
								|| a.DESCRIPTION.Contains(queryStr)
								|| a.ACTIVE.Contains(queryStr)
								
								|| a.CREATE_TASK.Contains(queryStr)
								);
			}else{
				queryData = m_Rep.GetList(where);
			}
			
		  
			pager.totalRows = queryData.Count();
			//排序
			queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
			return CreateModelList(ref queryData);
		}
		public virtual List<Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL> CreateModelList(ref IQueryable<Apps.Models.WAVE_FLOW_HEADER> queryData)
		{

			List<Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL> modelList = (from r in queryData
											  select new Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL
											  {
													WAVE_FLOW = r.WAVE_FLOW,
													DESCRIPTION = r.DESCRIPTION,
													ACTIVE = r.ACTIVE,
													OBJECT_ID = r.OBJECT_ID,
													CREATE_TASK = r.CREATE_TASK,
          
											  }).ToList();

			return modelList;
		}

		public virtual void Create(ref ValidationErrors errors, Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL model)
		{
				Apps.Models.WAVE_FLOW_HEADER entity = m_Rep.GetById(model.WAVE_FLOW);
				if (entity != null)
				{
					errors.Add(Resource.PrimaryRepeat);
					return;
				}
				entity = new Apps.Models.WAVE_FLOW_HEADER();
			   				entity.WAVE_FLOW = model.WAVE_FLOW;
				entity.DESCRIPTION = model.DESCRIPTION;
				entity.ACTIVE = model.ACTIVE;
				entity.OBJECT_ID = model.OBJECT_ID;
				entity.CREATE_TASK = model.CREATE_TASK;
  
				m_Rep.Create(entity);
		}



		 public virtual void RemoveById(ref ValidationErrors errors, string id)
		{
			
				m_Rep.RemoveById(id);
			
		}

		public virtual void RemoveByIds(ref ValidationErrors errors, string[] deleteCollection)
		{
				if (deleteCollection != null)
				{
				   //事务批量删除
				   // using (TransactionScope transactionScope = new TransactionScope())
				   // {
				   //     if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
				   //     {
				   //         transactionScope.Complete();
				   //         return true;
				   //     }
				   //    else
				   //     {
				   //         Transaction.Current.Rollback();
				   //         return false;
				   //     }
				   // }
				   m_Rep.RemoveById(deleteCollection);
				}
		}

		
	   

		public virtual void Modify(ref ValidationErrors errors, Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL model,params string[] updateProperties)
		{
				Apps.Models.WAVE_FLOW_HEADER entity = m_Rep.GetById(model.WAVE_FLOW);
				if (entity == null)
				{
					errors.Add(Resource.Disable);
					return;
				}
							  				if (updateProperties.Count() <= 0){
										entity.WAVE_FLOW = model.WAVE_FLOW;
											entity.DESCRIPTION = model.DESCRIPTION;
											entity.ACTIVE = model.ACTIVE;
											entity.OBJECT_ID = model.OBJECT_ID;
											entity.CREATE_TASK = model.CREATE_TASK;
									}else{
					
						Type type = typeof(Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL);
						Type typeE = typeof(Apps.Models.WAVE_FLOW_HEADER);
						foreach (var item in updateProperties) {
						System.Reflection.PropertyInfo pi = type.GetProperty(item);
						System.Reflection.PropertyInfo piE = typeE.GetProperty(item);
						piE.SetValue(entity,pi.GetValue(model),null);
				}
				}
				 

				m_Rep.Modify(entity,updateProperties);
		}

	  

		public virtual Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL GetById(string id)
		{
			Apps.Models.WAVE_FLOW_HEADER entity = m_Rep.GetById(id);
			if (entity!=null)
			{
				//WAVE_FLOW_HEADER entity = m_Rep.GetById(id);
				Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL model = new Apps.Models.SCV.WAVE.WAVE_FLOW_HEADER_MODEL();
							  				model.WAVE_FLOW = entity.WAVE_FLOW;
				model.DESCRIPTION = entity.DESCRIPTION;
				model.ACTIVE = entity.ACTIVE;
				model.OBJECT_ID = entity.OBJECT_ID;
				model.CREATE_TASK = entity.CREATE_TASK;
 
				return model;
			}
			else
			{
				return null;
			}
		}

	 

	}
}
