//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.IRepository.SCV.CART;
using System;
namespace Apps.Repository.SCV.CART
{
	public partial class CART_DETAIL_REPOSITORY:SCVBaseRepository<Apps.Models.CART_DETAIL>,ICART_DETAIL_REPOSITORY
	{
		
	}
}
