
 //------------------------------------------------------------------------------
// <auto-generated>
// 数据仓储接口，作用：
// 1.调用EF容器 批量 执行 sql语句
// 2.方便通过 子接口属性直接 获取 对应数据表的操作接口对象
// </auto-generated>
//------------------------------------------------------------------------------



namespace Apps.Repository.SCV
{
    using System;
    public partial class SCVDBSession:Apps.IRepository.SCV.ISCVDBSession
    {
    	Apps.IRepository.SCV.ALLOCATION.IALLOCATION_RULE_DETAIL_REPOSITORY _ALLOCATION_RULE_DETAIL;
    	public Apps.IRepository.SCV.ALLOCATION.IALLOCATION_RULE_DETAIL_REPOSITORY ALLOCATION_RULE_DETAIL 
    	{ 
    		get
    		{
    			if (_ALLOCATION_RULE_DETAIL == null)
    				_ALLOCATION_RULE_DETAIL = new Apps.Repository.SCV.ALLOCATION.ALLOCATION_RULE_DETAIL_REPOSITORY();
    			return _ALLOCATION_RULE_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.ALLOCATION.IALLOCATION_RULE_HEADER_REPOSITORY _ALLOCATION_RULE_HEADER;
    	public Apps.IRepository.SCV.ALLOCATION.IALLOCATION_RULE_HEADER_REPOSITORY ALLOCATION_RULE_HEADER 
    	{ 
    		get
    		{
    			if (_ALLOCATION_RULE_HEADER == null)
    				_ALLOCATION_RULE_HEADER = new Apps.Repository.SCV.ALLOCATION.ALLOCATION_RULE_HEADER_REPOSITORY();
    			return _ALLOCATION_RULE_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IAPPOINTMENT_REPOSITORY _APPOINTMENT;
    	public Apps.IRepository.SCV.Sys.IAPPOINTMENT_REPOSITORY APPOINTMENT 
    	{ 
    		get
    		{
    			if (_APPOINTMENT == null)
    				_APPOINTMENT = new Apps.Repository.SCV.Sys.APPOINTMENT_REPOSITORY();
    			return _APPOINTMENT;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_RECEIPT_CONTAINER_REPOSITORY _AR_RECEIPT_CONTAINER;
    	public Apps.IRepository.SCV.AR.IAR_RECEIPT_CONTAINER_REPOSITORY AR_RECEIPT_CONTAINER 
    	{ 
    		get
    		{
    			if (_AR_RECEIPT_CONTAINER == null)
    				_AR_RECEIPT_CONTAINER = new Apps.Repository.SCV.AR.AR_RECEIPT_CONTAINER_REPOSITORY();
    			return _AR_RECEIPT_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_RECEIPT_DETAIL_REPOSITORY _AR_RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_RECEIPT_DETAIL_REPOSITORY AR_RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_RECEIPT_DETAIL == null)
    				_AR_RECEIPT_DETAIL = new Apps.Repository.SCV.AR.AR_RECEIPT_DETAIL_REPOSITORY();
    			return _AR_RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_RECEIPT_HEADER_REPOSITORY _AR_RECEIPT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_RECEIPT_HEADER_REPOSITORY AR_RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_RECEIPT_HEADER == null)
    				_AR_RECEIPT_HEADER = new Apps.Repository.SCV.AR.AR_RECEIPT_HEADER_REPOSITORY();
    			return _AR_RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_TASK_DETAIL_REPOSITORY _AR_TASK_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_TASK_DETAIL_REPOSITORY AR_TASK_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_TASK_DETAIL == null)
    				_AR_TASK_DETAIL = new Apps.Repository.SCV.AR.AR_TASK_DETAIL_REPOSITORY();
    			return _AR_TASK_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_TASK_HEADER_REPOSITORY _AR_TASK_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_TASK_HEADER_REPOSITORY AR_TASK_HEADER 
    	{ 
    		get
    		{
    			if (_AR_TASK_HEADER == null)
    				_AR_TASK_HEADER = new Apps.Repository.SCV.AR.AR_TASK_HEADER_REPOSITORY();
    			return _AR_TASK_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_TRANSACTION_HISTORY_REPOSITORY _AR_TRANSACTION_HISTORY;
    	public Apps.IRepository.SCV.AR.IAR_TRANSACTION_HISTORY_REPOSITORY AR_TRANSACTION_HISTORY 
    	{ 
    		get
    		{
    			if (_AR_TRANSACTION_HISTORY == null)
    				_AR_TRANSACTION_HISTORY = new Apps.Repository.SCV.AR.AR_TRANSACTION_HISTORY_REPOSITORY();
    			return _AR_TRANSACTION_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IAREAS_REPOSITORY _AREAS;
    	public Apps.IRepository.SCV.Sys.IAREAS_REPOSITORY AREAS 
    	{ 
    		get
    		{
    			if (_AREAS == null)
    				_AREAS = new Apps.Repository.SCV.Sys.AREAS_REPOSITORY();
    			return _AREAS;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IATTRIBUTE_REPOSITORY _ATTRIBUTE;
    	public Apps.IRepository.SCV.Sys.IATTRIBUTE_REPOSITORY ATTRIBUTE 
    	{ 
    		get
    		{
    			if (_ATTRIBUTE == null)
    				_ATTRIBUTE = new Apps.Repository.SCV.Sys.ATTRIBUTE_REPOSITORY();
    			return _ATTRIBUTE;
    		}
    	}
    
    	Apps.IRepository.SCV.ATTRIBUTE.IATTRIBUTE_TEMPLATE_REPOSITORY _ATTRIBUTE_TEMPLATE;
    	public Apps.IRepository.SCV.ATTRIBUTE.IATTRIBUTE_TEMPLATE_REPOSITORY ATTRIBUTE_TEMPLATE 
    	{ 
    		get
    		{
    			if (_ATTRIBUTE_TEMPLATE == null)
    				_ATTRIBUTE_TEMPLATE = new Apps.Repository.SCV.ATTRIBUTE.ATTRIBUTE_TEMPLATE_REPOSITORY();
    			return _ATTRIBUTE_TEMPLATE;
    		}
    	}
    
    	Apps.IRepository.SCV.AUDIT.IAUDIT_LOG_REPOSITORY _AUDIT_LOG;
    	public Apps.IRepository.SCV.AUDIT.IAUDIT_LOG_REPOSITORY AUDIT_LOG 
    	{ 
    		get
    		{
    			if (_AUDIT_LOG == null)
    				_AUDIT_LOG = new Apps.Repository.SCV.AUDIT.AUDIT_LOG_REPOSITORY();
    			return _AUDIT_LOG;
    		}
    	}
    
    	Apps.IRepository.SCV.BOM.IBOM_DETAIL_REPOSITORY _BOM_DETAIL;
    	public Apps.IRepository.SCV.BOM.IBOM_DETAIL_REPOSITORY BOM_DETAIL 
    	{ 
    		get
    		{
    			if (_BOM_DETAIL == null)
    				_BOM_DETAIL = new Apps.Repository.SCV.BOM.BOM_DETAIL_REPOSITORY();
    			return _BOM_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.BOM.IBOM_HEADER_REPOSITORY _BOM_HEADER;
    	public Apps.IRepository.SCV.BOM.IBOM_HEADER_REPOSITORY BOM_HEADER 
    	{ 
    		get
    		{
    			if (_BOM_HEADER == null)
    				_BOM_HEADER = new Apps.Repository.SCV.BOM.BOM_HEADER_REPOSITORY();
    			return _BOM_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.CART.ICART_DETAIL_REPOSITORY _CART_DETAIL;
    	public Apps.IRepository.SCV.CART.ICART_DETAIL_REPOSITORY CART_DETAIL 
    	{ 
    		get
    		{
    			if (_CART_DETAIL == null)
    				_CART_DETAIL = new Apps.Repository.SCV.CART.CART_DETAIL_REPOSITORY();
    			return _CART_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.CART.ICART_HEADER_REPOSITORY _CART_HEADER;
    	public Apps.IRepository.SCV.CART.ICART_HEADER_REPOSITORY CART_HEADER 
    	{ 
    		get
    		{
    			if (_CART_HEADER == null)
    				_CART_HEADER = new Apps.Repository.SCV.CART.CART_HEADER_REPOSITORY();
    			return _CART_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.ICOMPANY_REPOSITORY _COMPANY;
    	public Apps.IRepository.SCV.Sys.ICOMPANY_REPOSITORY COMPANY 
    	{ 
    		get
    		{
    			if (_COMPANY == null)
    				_COMPANY = new Apps.Repository.SCV.Sys.COMPANY_REPOSITORY();
    			return _COMPANY;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.ICOMPANYSTATE_REPOSITORY _COMPANYSTATE;
    	public Apps.IRepository.SCV.Sys.ICOMPANYSTATE_REPOSITORY COMPANYSTATE 
    	{ 
    		get
    		{
    			if (_COMPANYSTATE == null)
    				_COMPANYSTATE = new Apps.Repository.SCV.Sys.COMPANYSTATE_REPOSITORY();
    			return _COMPANYSTATE;
    		}
    	}
    
    	Apps.IRepository.SCV.CONFIG.ICONFIG_VALUE_REPOSITORY _CONFIG_VALUE;
    	public Apps.IRepository.SCV.CONFIG.ICONFIG_VALUE_REPOSITORY CONFIG_VALUE 
    	{ 
    		get
    		{
    			if (_CONFIG_VALUE == null)
    				_CONFIG_VALUE = new Apps.Repository.SCV.CONFIG.CONFIG_VALUE_REPOSITORY();
    			return _CONFIG_VALUE;
    		}
    	}
    
    	Apps.IRepository.SCV.CONTAINER.ICONTAINER_TYPE_REPOSITORY _CONTAINER_TYPE;
    	public Apps.IRepository.SCV.CONTAINER.ICONTAINER_TYPE_REPOSITORY CONTAINER_TYPE 
    	{ 
    		get
    		{
    			if (_CONTAINER_TYPE == null)
    				_CONTAINER_TYPE = new Apps.Repository.SCV.CONTAINER.CONTAINER_TYPE_REPOSITORY();
    			return _CONTAINER_TYPE;
    		}
    	}
    
    	Apps.IRepository.SCV.CUSTOM.ICUSTOM_RESOURCE_REPOSITORY _CUSTOM_RESOURCE;
    	public Apps.IRepository.SCV.CUSTOM.ICUSTOM_RESOURCE_REPOSITORY CUSTOM_RESOURCE 
    	{ 
    		get
    		{
    			if (_CUSTOM_RESOURCE == null)
    				_CUSTOM_RESOURCE = new Apps.Repository.SCV.CUSTOM.CUSTOM_RESOURCE_REPOSITORY();
    			return _CUSTOM_RESOURCE;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.ICUSTOMER_REPOSITORY _CUSTOMER;
    	public Apps.IRepository.SCV.Sys.ICUSTOMER_REPOSITORY CUSTOMER 
    	{ 
    		get
    		{
    			if (_CUSTOMER == null)
    				_CUSTOMER = new Apps.Repository.SCV.Sys.CUSTOMER_REPOSITORY();
    			return _CUSTOMER;
    		}
    	}
    
    	Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_DETAIL_REPOSITORY _CYCLE_COUNT_DETAIL;
    	public Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_DETAIL_REPOSITORY CYCLE_COUNT_DETAIL 
    	{ 
    		get
    		{
    			if (_CYCLE_COUNT_DETAIL == null)
    				_CYCLE_COUNT_DETAIL = new Apps.Repository.SCV.CYCLE.CYCLE_COUNT_DETAIL_REPOSITORY();
    			return _CYCLE_COUNT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_HEADER_REPOSITORY _CYCLE_COUNT_HEADER;
    	public Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_HEADER_REPOSITORY CYCLE_COUNT_HEADER 
    	{ 
    		get
    		{
    			if (_CYCLE_COUNT_HEADER == null)
    				_CYCLE_COUNT_HEADER = new Apps.Repository.SCV.CYCLE.CYCLE_COUNT_HEADER_REPOSITORY();
    			return _CYCLE_COUNT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_MASTER_REPOSITORY _CYCLE_COUNT_MASTER;
    	public Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_MASTER_REPOSITORY CYCLE_COUNT_MASTER 
    	{ 
    		get
    		{
    			if (_CYCLE_COUNT_MASTER == null)
    				_CYCLE_COUNT_MASTER = new Apps.Repository.SCV.CYCLE.CYCLE_COUNT_MASTER_REPOSITORY();
    			return _CYCLE_COUNT_MASTER;
    		}
    	}
    
    	Apps.IRepository.SCV.DOCUMENT.IDOCUMENT_ROUTING_REPOSITORY _DOCUMENT_ROUTING;
    	public Apps.IRepository.SCV.DOCUMENT.IDOCUMENT_ROUTING_REPOSITORY DOCUMENT_ROUTING 
    	{ 
    		get
    		{
    			if (_DOCUMENT_ROUTING == null)
    				_DOCUMENT_ROUTING = new Apps.Repository.SCV.DOCUMENT.DOCUMENT_ROUTING_REPOSITORY();
    			return _DOCUMENT_ROUTING;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_COMPANY_REPOSITORY _DOWNLOAD_COMPANY;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_COMPANY_REPOSITORY DOWNLOAD_COMPANY 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_COMPANY == null)
    				_DOWNLOAD_COMPANY = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_COMPANY_REPOSITORY();
    			return _DOWNLOAD_COMPANY;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_REPOSITORY _DOWNLOAD_ITEM;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_REPOSITORY DOWNLOAD_ITEM 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_ITEM == null)
    				_DOWNLOAD_ITEM = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_ITEM_REPOSITORY();
    			return _DOWNLOAD_ITEM;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_BARCODE_REPOSITORY _DOWNLOAD_ITEM_BARCODE;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_BARCODE_REPOSITORY DOWNLOAD_ITEM_BARCODE 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_ITEM_BARCODE == null)
    				_DOWNLOAD_ITEM_BARCODE = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_ITEM_BARCODE_REPOSITORY();
    			return _DOWNLOAD_ITEM_BARCODE;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY _DOWNLOAD_ITEM_UNIT_OF_MEASURE;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY DOWNLOAD_ITEM_UNIT_OF_MEASURE 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_ITEM_UNIT_OF_MEASURE == null)
    				_DOWNLOAD_ITEM_UNIT_OF_MEASURE = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY();
    			return _DOWNLOAD_ITEM_UNIT_OF_MEASURE;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEMS_REPOSITORY _DOWNLOAD_ITEMS;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_ITEMS_REPOSITORY DOWNLOAD_ITEMS 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_ITEMS == null)
    				_DOWNLOAD_ITEMS = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_ITEMS_REPOSITORY();
    			return _DOWNLOAD_ITEMS;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_DETAIL_REPOSITORY _DOWNLOAD_RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_DETAIL_REPOSITORY DOWNLOAD_RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_RECEIPT_DETAIL == null)
    				_DOWNLOAD_RECEIPT_DETAIL = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_DETAIL_REPOSITORY();
    			return _DOWNLOAD_RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_HEADER_REPOSITORY _DOWNLOAD_RECEIPT_HEADER;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_HEADER_REPOSITORY DOWNLOAD_RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_RECEIPT_HEADER == null)
    				_DOWNLOAD_RECEIPT_HEADER = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_HEADER_REPOSITORY();
    			return _DOWNLOAD_RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPTS_REPOSITORY _DOWNLOAD_RECEIPTS;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPTS_REPOSITORY DOWNLOAD_RECEIPTS 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_RECEIPTS == null)
    				_DOWNLOAD_RECEIPTS = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_RECEIPTS_REPOSITORY();
    			return _DOWNLOAD_RECEIPTS;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_DETAIL_REPOSITORY _DOWNLOAD_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_DETAIL_REPOSITORY DOWNLOAD_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_SHIPMENT_DETAIL == null)
    				_DOWNLOAD_SHIPMENT_DETAIL = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_SHIPMENT_DETAIL_REPOSITORY();
    			return _DOWNLOAD_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_HEADER_REPOSITORY _DOWNLOAD_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_HEADER_REPOSITORY DOWNLOAD_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_SHIPMENT_HEADER == null)
    				_DOWNLOAD_SHIPMENT_HEADER = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_SHIPMENT_HEADER_REPOSITORY();
    			return _DOWNLOAD_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENTS_REPOSITORY _DOWNLOAD_SHIPMENTS;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENTS_REPOSITORY DOWNLOAD_SHIPMENTS 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_SHIPMENTS == null)
    				_DOWNLOAD_SHIPMENTS = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_SHIPMENTS_REPOSITORY();
    			return _DOWNLOAD_SHIPMENTS;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENTS_UPDATE_REPOSITORY _DOWNLOAD_SHIPMENTS_UPDATE;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENTS_UPDATE_REPOSITORY DOWNLOAD_SHIPMENTS_UPDATE 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_SHIPMENTS_UPDATE == null)
    				_DOWNLOAD_SHIPMENTS_UPDATE = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_SHIPMENTS_UPDATE_REPOSITORY();
    			return _DOWNLOAD_SHIPMENTS_UPDATE;
    		}
    	}
    
    	Apps.IRepository.SCV.DYNAMIC.IDYNAMIC_CALLING_DETAIL_REPOSITORY _DYNAMIC_CALLING_DETAIL;
    	public Apps.IRepository.SCV.DYNAMIC.IDYNAMIC_CALLING_DETAIL_REPOSITORY DYNAMIC_CALLING_DETAIL 
    	{ 
    		get
    		{
    			if (_DYNAMIC_CALLING_DETAIL == null)
    				_DYNAMIC_CALLING_DETAIL = new Apps.Repository.SCV.DYNAMIC.DYNAMIC_CALLING_DETAIL_REPOSITORY();
    			return _DYNAMIC_CALLING_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.DYNAMIC.IDYNAMIC_CALLING_HEADER_REPOSITORY _DYNAMIC_CALLING_HEADER;
    	public Apps.IRepository.SCV.DYNAMIC.IDYNAMIC_CALLING_HEADER_REPOSITORY DYNAMIC_CALLING_HEADER 
    	{ 
    		get
    		{
    			if (_DYNAMIC_CALLING_HEADER == null)
    				_DYNAMIC_CALLING_HEADER = new Apps.Repository.SCV.DYNAMIC.DYNAMIC_CALLING_HEADER_REPOSITORY();
    			return _DYNAMIC_CALLING_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.EX.IEX_MENU_REPOSITORY _EX_MENU;
    	public Apps.IRepository.SCV.EX.IEX_MENU_REPOSITORY EX_MENU 
    	{ 
    		get
    		{
    			if (_EX_MENU == null)
    				_EX_MENU = new Apps.Repository.SCV.EX.EX_MENU_REPOSITORY();
    			return _EX_MENU;
    		}
    	}
    
    	Apps.IRepository.SCV.FILTER.IFILTER_CONFIG_DETAIL_REPOSITORY _FILTER_CONFIG_DETAIL;
    	public Apps.IRepository.SCV.FILTER.IFILTER_CONFIG_DETAIL_REPOSITORY FILTER_CONFIG_DETAIL 
    	{ 
    		get
    		{
    			if (_FILTER_CONFIG_DETAIL == null)
    				_FILTER_CONFIG_DETAIL = new Apps.Repository.SCV.FILTER.FILTER_CONFIG_DETAIL_REPOSITORY();
    			return _FILTER_CONFIG_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.FILTER.IFILTER_GROUP_BY_REPOSITORY _FILTER_GROUP_BY;
    	public Apps.IRepository.SCV.FILTER.IFILTER_GROUP_BY_REPOSITORY FILTER_GROUP_BY 
    	{ 
    		get
    		{
    			if (_FILTER_GROUP_BY == null)
    				_FILTER_GROUP_BY = new Apps.Repository.SCV.FILTER.FILTER_GROUP_BY_REPOSITORY();
    			return _FILTER_GROUP_BY;
    		}
    	}
    
    	Apps.IRepository.SCV.FILTER.IFILTER_ORDER_BY_REPOSITORY _FILTER_ORDER_BY;
    	public Apps.IRepository.SCV.FILTER.IFILTER_ORDER_BY_REPOSITORY FILTER_ORDER_BY 
    	{ 
    		get
    		{
    			if (_FILTER_ORDER_BY == null)
    				_FILTER_ORDER_BY = new Apps.Repository.SCV.FILTER.FILTER_ORDER_BY_REPOSITORY();
    			return _FILTER_ORDER_BY;
    		}
    	}
    
    	Apps.IRepository.SCV.FILTER.IFILTER_STATEMENT_REPOSITORY _FILTER_STATEMENT;
    	public Apps.IRepository.SCV.FILTER.IFILTER_STATEMENT_REPOSITORY FILTER_STATEMENT 
    	{ 
    		get
    		{
    			if (_FILTER_STATEMENT == null)
    				_FILTER_STATEMENT = new Apps.Repository.SCV.FILTER.FILTER_STATEMENT_REPOSITORY();
    			return _FILTER_STATEMENT;
    		}
    	}
    
    	Apps.IRepository.SCV.GENERIC.IGENERIC_CONFIG_DETAIL_REPOSITORY _GENERIC_CONFIG_DETAIL;
    	public Apps.IRepository.SCV.GENERIC.IGENERIC_CONFIG_DETAIL_REPOSITORY GENERIC_CONFIG_DETAIL 
    	{ 
    		get
    		{
    			if (_GENERIC_CONFIG_DETAIL == null)
    				_GENERIC_CONFIG_DETAIL = new Apps.Repository.SCV.GENERIC.GENERIC_CONFIG_DETAIL_REPOSITORY();
    			return _GENERIC_CONFIG_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.GENERIC.IGENERIC_CONFIG_HEADER_REPOSITORY _GENERIC_CONFIG_HEADER;
    	public Apps.IRepository.SCV.GENERIC.IGENERIC_CONFIG_HEADER_REPOSITORY GENERIC_CONFIG_HEADER 
    	{ 
    		get
    		{
    			if (_GENERIC_CONFIG_HEADER == null)
    				_GENERIC_CONFIG_HEADER = new Apps.Repository.SCV.GENERIC.GENERIC_CONFIG_HEADER_REPOSITORY();
    			return _GENERIC_CONFIG_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.INTERFACE.IINTERFACE_FAILURE_REPOSITORY _INTERFACE_FAILURE;
    	public Apps.IRepository.SCV.INTERFACE.IINTERFACE_FAILURE_REPOSITORY INTERFACE_FAILURE 
    	{ 
    		get
    		{
    			if (_INTERFACE_FAILURE == null)
    				_INTERFACE_FAILURE = new Apps.Repository.SCV.INTERFACE.INTERFACE_FAILURE_REPOSITORY();
    			return _INTERFACE_FAILURE;
    		}
    	}
    
    	Apps.IRepository.SCV.INTERFACE.IINTERFACE_PROCESS_REPOSITORY _INTERFACE_PROCESS;
    	public Apps.IRepository.SCV.INTERFACE.IINTERFACE_PROCESS_REPOSITORY INTERFACE_PROCESS 
    	{ 
    		get
    		{
    			if (_INTERFACE_PROCESS == null)
    				_INTERFACE_PROCESS = new Apps.Repository.SCV.INTERFACE.INTERFACE_PROCESS_REPOSITORY();
    			return _INTERFACE_PROCESS;
    		}
    	}
    
    	Apps.IRepository.SCV.INTERFACE.IINTERFACE_SESSION_REPOSITORY _INTERFACE_SESSION;
    	public Apps.IRepository.SCV.INTERFACE.IINTERFACE_SESSION_REPOSITORY INTERFACE_SESSION 
    	{ 
    		get
    		{
    			if (_INTERFACE_SESSION == null)
    				_INTERFACE_SESSION = new Apps.Repository.SCV.INTERFACE.INTERFACE_SESSION_REPOSITORY();
    			return _INTERFACE_SESSION;
    		}
    	}
    
    	Apps.IRepository.SCV.INTERFACE.IINTERFACE_TABLE_STATISTIC_REPOSITORY _INTERFACE_TABLE_STATISTIC;
    	public Apps.IRepository.SCV.INTERFACE.IINTERFACE_TABLE_STATISTIC_REPOSITORY INTERFACE_TABLE_STATISTIC 
    	{ 
    		get
    		{
    			if (_INTERFACE_TABLE_STATISTIC == null)
    				_INTERFACE_TABLE_STATISTIC = new Apps.Repository.SCV.INTERFACE.INTERFACE_TABLE_STATISTIC_REPOSITORY();
    			return _INTERFACE_TABLE_STATISTIC;
    		}
    	}
    
    	Apps.IRepository.SCV.INVENTORY.IINVENTORY_TRANSACTION_REPOSITORY _INVENTORY_TRANSACTION;
    	public Apps.IRepository.SCV.INVENTORY.IINVENTORY_TRANSACTION_REPOSITORY INVENTORY_TRANSACTION 
    	{ 
    		get
    		{
    			if (_INVENTORY_TRANSACTION == null)
    				_INVENTORY_TRANSACTION = new Apps.Repository.SCV.INVENTORY.INVENTORY_TRANSACTION_REPOSITORY();
    			return _INVENTORY_TRANSACTION;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IITEM_REPOSITORY _ITEM;
    	public Apps.IRepository.SCV.Sys.IITEM_REPOSITORY ITEM 
    	{ 
    		get
    		{
    			if (_ITEM == null)
    				_ITEM = new Apps.Repository.SCV.Sys.ITEM_REPOSITORY();
    			return _ITEM;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_BARCODE_REPOSITORY _ITEM_BARCODE;
    	public Apps.IRepository.SCV.ITEM.IITEM_BARCODE_REPOSITORY ITEM_BARCODE 
    	{ 
    		get
    		{
    			if (_ITEM_BARCODE == null)
    				_ITEM_BARCODE = new Apps.Repository.SCV.ITEM.ITEM_BARCODE_REPOSITORY();
    			return _ITEM_BARCODE;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_BEIYONG_REPOSITORY _ITEM_BEIYONG;
    	public Apps.IRepository.SCV.ITEM.IITEM_BEIYONG_REPOSITORY ITEM_BEIYONG 
    	{ 
    		get
    		{
    			if (_ITEM_BEIYONG == null)
    				_ITEM_BEIYONG = new Apps.Repository.SCV.ITEM.ITEM_BEIYONG_REPOSITORY();
    			return _ITEM_BEIYONG;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_BEIYONG1_REPOSITORY _ITEM_BEIYONG1;
    	public Apps.IRepository.SCV.ITEM.IITEM_BEIYONG1_REPOSITORY ITEM_BEIYONG1 
    	{ 
    		get
    		{
    			if (_ITEM_BEIYONG1 == null)
    				_ITEM_BEIYONG1 = new Apps.Repository.SCV.ITEM.ITEM_BEIYONG1_REPOSITORY();
    			return _ITEM_BEIYONG1;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_LOCATION_CAPACITY_REPOSITORY _ITEM_LOCATION_CAPACITY;
    	public Apps.IRepository.SCV.ITEM.IITEM_LOCATION_CAPACITY_REPOSITORY ITEM_LOCATION_CAPACITY 
    	{ 
    		get
    		{
    			if (_ITEM_LOCATION_CAPACITY == null)
    				_ITEM_LOCATION_CAPACITY = new Apps.Repository.SCV.ITEM.ITEM_LOCATION_CAPACITY_REPOSITORY();
    			return _ITEM_LOCATION_CAPACITY;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_UNIT_OF_MEASURE_REPOSITORY _ITEM_UNIT_OF_MEASURE;
    	public Apps.IRepository.SCV.ITEM.IITEM_UNIT_OF_MEASURE_REPOSITORY ITEM_UNIT_OF_MEASURE 
    	{ 
    		get
    		{
    			if (_ITEM_UNIT_OF_MEASURE == null)
    				_ITEM_UNIT_OF_MEASURE = new Apps.Repository.SCV.ITEM.ITEM_UNIT_OF_MEASURE_REPOSITORY();
    			return _ITEM_UNIT_OF_MEASURE;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_WEIGHT_HIS_REPOSITORY _ITEM_WEIGHT_HIS;
    	public Apps.IRepository.SCV.ITEM.IITEM_WEIGHT_HIS_REPOSITORY ITEM_WEIGHT_HIS 
    	{ 
    		get
    		{
    			if (_ITEM_WEIGHT_HIS == null)
    				_ITEM_WEIGHT_HIS = new Apps.Repository.SCV.ITEM.ITEM_WEIGHT_HIS_REPOSITORY();
    			return _ITEM_WEIGHT_HIS;
    		}
    	}
    
    	Apps.IRepository.SCV.ITEM.IITEM_ZONE_CAPACITY_REPOSITORY _ITEM_ZONE_CAPACITY;
    	public Apps.IRepository.SCV.ITEM.IITEM_ZONE_CAPACITY_REPOSITORY ITEM_ZONE_CAPACITY 
    	{ 
    		get
    		{
    			if (_ITEM_ZONE_CAPACITY == null)
    				_ITEM_ZONE_CAPACITY = new Apps.Repository.SCV.ITEM.ITEM_ZONE_CAPACITY_REPOSITORY();
    			return _ITEM_ZONE_CAPACITY;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATING.ILOCATING_RULE_DETAIL_REPOSITORY _LOCATING_RULE_DETAIL;
    	public Apps.IRepository.SCV.LOCATING.ILOCATING_RULE_DETAIL_REPOSITORY LOCATING_RULE_DETAIL 
    	{ 
    		get
    		{
    			if (_LOCATING_RULE_DETAIL == null)
    				_LOCATING_RULE_DETAIL = new Apps.Repository.SCV.LOCATING.LOCATING_RULE_DETAIL_REPOSITORY();
    			return _LOCATING_RULE_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATING.ILOCATING_RULE_HEADER_REPOSITORY _LOCATING_RULE_HEADER;
    	public Apps.IRepository.SCV.LOCATING.ILOCATING_RULE_HEADER_REPOSITORY LOCATING_RULE_HEADER 
    	{ 
    		get
    		{
    			if (_LOCATING_RULE_HEADER == null)
    				_LOCATING_RULE_HEADER = new Apps.Repository.SCV.LOCATING.LOCATING_RULE_HEADER_REPOSITORY();
    			return _LOCATING_RULE_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.ILOCATION_REPOSITORY _LOCATION;
    	public Apps.IRepository.SCV.Sys.ILOCATION_REPOSITORY LOCATION 
    	{ 
    		get
    		{
    			if (_LOCATION == null)
    				_LOCATION = new Apps.Repository.SCV.Sys.LOCATION_REPOSITORY();
    			return _LOCATION;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATION.ILOCATION_CARRIER_REPOSITORY _LOCATION_CARRIER;
    	public Apps.IRepository.SCV.LOCATION.ILOCATION_CARRIER_REPOSITORY LOCATION_CARRIER 
    	{ 
    		get
    		{
    			if (_LOCATION_CARRIER == null)
    				_LOCATION_CARRIER = new Apps.Repository.SCV.LOCATION.LOCATION_CARRIER_REPOSITORY();
    			return _LOCATION_CARRIER;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_REPOSITORY _LOCATION_INVENTORY;
    	public Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_REPOSITORY LOCATION_INVENTORY 
    	{ 
    		get
    		{
    			if (_LOCATION_INVENTORY == null)
    				_LOCATION_INVENTORY = new Apps.Repository.SCV.LOCATION.LOCATION_INVENTORY_REPOSITORY();
    			return _LOCATION_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATION.ILOCATION_SELECTION_REPOSITORY _LOCATION_SELECTION;
    	public Apps.IRepository.SCV.LOCATION.ILOCATION_SELECTION_REPOSITORY LOCATION_SELECTION 
    	{ 
    		get
    		{
    			if (_LOCATION_SELECTION == null)
    				_LOCATION_SELECTION = new Apps.Repository.SCV.LOCATION.LOCATION_SELECTION_REPOSITORY();
    			return _LOCATION_SELECTION;
    		}
    	}
    
    	Apps.IRepository.SCV.MISC.IMISC_INVENTORY_HANDLING_REPOSITORY _MISC_INVENTORY_HANDLING;
    	public Apps.IRepository.SCV.MISC.IMISC_INVENTORY_HANDLING_REPOSITORY MISC_INVENTORY_HANDLING 
    	{ 
    		get
    		{
    			if (_MISC_INVENTORY_HANDLING == null)
    				_MISC_INVENTORY_HANDLING = new Apps.Repository.SCV.MISC.MISC_INVENTORY_HANDLING_REPOSITORY();
    			return _MISC_INVENTORY_HANDLING;
    		}
    	}
    
    	Apps.IRepository.SCV.NEXT.INEXT_NUMBER_REPOSITORY _NEXT_NUMBER;
    	public Apps.IRepository.SCV.NEXT.INEXT_NUMBER_REPOSITORY NEXT_NUMBER 
    	{ 
    		get
    		{
    			if (_NEXT_NUMBER == null)
    				_NEXT_NUMBER = new Apps.Repository.SCV.NEXT.NEXT_NUMBER_REPOSITORY();
    			return _NEXT_NUMBER;
    		}
    	}
    
    	Apps.IRepository.SCV.PACKING.IPACKING_CLASS_REPOSITORY _PACKING_CLASS;
    	public Apps.IRepository.SCV.PACKING.IPACKING_CLASS_REPOSITORY PACKING_CLASS 
    	{ 
    		get
    		{
    			if (_PACKING_CLASS == null)
    				_PACKING_CLASS = new Apps.Repository.SCV.PACKING.PACKING_CLASS_REPOSITORY();
    			return _PACKING_CLASS;
    		}
    	}
    
    	Apps.IRepository.SCV.PACKING.IPACKING_PREFERENCE_REPOSITORY _PACKING_PREFERENCE;
    	public Apps.IRepository.SCV.PACKING.IPACKING_PREFERENCE_REPOSITORY PACKING_PREFERENCE 
    	{ 
    		get
    		{
    			if (_PACKING_PREFERENCE == null)
    				_PACKING_PREFERENCE = new Apps.Repository.SCV.PACKING.PACKING_PREFERENCE_REPOSITORY();
    			return _PACKING_PREFERENCE;
    		}
    	}
    
    	Apps.IRepository.SCV.PROCESS.IPROCESS_HISTORY_REPOSITORY _PROCESS_HISTORY;
    	public Apps.IRepository.SCV.PROCESS.IPROCESS_HISTORY_REPOSITORY PROCESS_HISTORY 
    	{ 
    		get
    		{
    			if (_PROCESS_HISTORY == null)
    				_PROCESS_HISTORY = new Apps.Repository.SCV.PROCESS.PROCESS_HISTORY_REPOSITORY();
    			return _PROCESS_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.PURCHASE.IPURCHASE_ORDER_DETAIL_REPOSITORY _PURCHASE_ORDER_DETAIL;
    	public Apps.IRepository.SCV.PURCHASE.IPURCHASE_ORDER_DETAIL_REPOSITORY PURCHASE_ORDER_DETAIL 
    	{ 
    		get
    		{
    			if (_PURCHASE_ORDER_DETAIL == null)
    				_PURCHASE_ORDER_DETAIL = new Apps.Repository.SCV.PURCHASE.PURCHASE_ORDER_DETAIL_REPOSITORY();
    			return _PURCHASE_ORDER_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.PURCHASE.IPURCHASE_ORDER_HEADER_REPOSITORY _PURCHASE_ORDER_HEADER;
    	public Apps.IRepository.SCV.PURCHASE.IPURCHASE_ORDER_HEADER_REPOSITORY PURCHASE_ORDER_HEADER 
    	{ 
    		get
    		{
    			if (_PURCHASE_ORDER_HEADER == null)
    				_PURCHASE_ORDER_HEADER = new Apps.Repository.SCV.PURCHASE.PURCHASE_ORDER_HEADER_REPOSITORY();
    			return _PURCHASE_ORDER_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.QUEUE.IQUEUE_TASK_IN_CONFIRM_REPOSITORY _QUEUE_TASK_IN_CONFIRM;
    	public Apps.IRepository.SCV.QUEUE.IQUEUE_TASK_IN_CONFIRM_REPOSITORY QUEUE_TASK_IN_CONFIRM 
    	{ 
    		get
    		{
    			if (_QUEUE_TASK_IN_CONFIRM == null)
    				_QUEUE_TASK_IN_CONFIRM = new Apps.Repository.SCV.QUEUE.QUEUE_TASK_IN_CONFIRM_REPOSITORY();
    			return _QUEUE_TASK_IN_CONFIRM;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_CONTAINER_REPOSITORY _RECEIPT_CONTAINER;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_CONTAINER_REPOSITORY RECEIPT_CONTAINER 
    	{ 
    		get
    		{
    			if (_RECEIPT_CONTAINER == null)
    				_RECEIPT_CONTAINER = new Apps.Repository.SCV.RECEIPT.RECEIPT_CONTAINER_REPOSITORY();
    			return _RECEIPT_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_DETAIL_REPOSITORY _RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_DETAIL_REPOSITORY RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_RECEIPT_DETAIL == null)
    				_RECEIPT_DETAIL = new Apps.Repository.SCV.RECEIPT.RECEIPT_DETAIL_REPOSITORY();
    			return _RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_HEADER_REPOSITORY _RECEIPT_HEADER;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_HEADER_REPOSITORY RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_RECEIPT_HEADER == null)
    				_RECEIPT_HEADER = new Apps.Repository.SCV.RECEIPT.RECEIPT_HEADER_REPOSITORY();
    			return _RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_HEADER_TEMP_REPOSITORY _RECEIPT_HEADER_TEMP;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_HEADER_TEMP_REPOSITORY RECEIPT_HEADER_TEMP 
    	{ 
    		get
    		{
    			if (_RECEIPT_HEADER_TEMP == null)
    				_RECEIPT_HEADER_TEMP = new Apps.Repository.SCV.RECEIPT.RECEIPT_HEADER_TEMP_REPOSITORY();
    			return _RECEIPT_HEADER_TEMP;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_LOCATE_REQUEST_REPOSITORY _RECEIPT_LOCATE_REQUEST;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_LOCATE_REQUEST_REPOSITORY RECEIPT_LOCATE_REQUEST 
    	{ 
    		get
    		{
    			if (_RECEIPT_LOCATE_REQUEST == null)
    				_RECEIPT_LOCATE_REQUEST = new Apps.Repository.SCV.RECEIPT.RECEIPT_LOCATE_REQUEST_REPOSITORY();
    			return _RECEIPT_LOCATE_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIVING.IRECEIVING_PREFERENCE_REPOSITORY _RECEIVING_PREFERENCE;
    	public Apps.IRepository.SCV.RECEIVING.IRECEIVING_PREFERENCE_REPOSITORY RECEIVING_PREFERENCE 
    	{ 
    		get
    		{
    			if (_RECEIVING_PREFERENCE == null)
    				_RECEIVING_PREFERENCE = new Apps.Repository.SCV.RECEIVING.RECEIVING_PREFERENCE_REPOSITORY();
    			return _RECEIVING_PREFERENCE;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IREPLENISHMENT_REPOSITORY _REPLENISHMENT;
    	public Apps.IRepository.SCV.Sys.IREPLENISHMENT_REPOSITORY REPLENISHMENT 
    	{ 
    		get
    		{
    			if (_REPLENISHMENT == null)
    				_REPLENISHMENT = new Apps.Repository.SCV.Sys.REPLENISHMENT_REPOSITORY();
    			return _REPLENISHMENT;
    		}
    	}
    
    	Apps.IRepository.SCV.REPLENISHMENT.IREPLENISHMENT_MASTER_REPOSITORY _REPLENISHMENT_MASTER;
    	public Apps.IRepository.SCV.REPLENISHMENT.IREPLENISHMENT_MASTER_REPOSITORY REPLENISHMENT_MASTER 
    	{ 
    		get
    		{
    			if (_REPLENISHMENT_MASTER == null)
    				_REPLENISHMENT_MASTER = new Apps.Repository.SCV.REPLENISHMENT.REPLENISHMENT_MASTER_REPOSITORY();
    			return _REPLENISHMENT_MASTER;
    		}
    	}
    
    	Apps.IRepository.SCV.REPLENISHMENT.IREPLENISHMENT_REQUEST_REPOSITORY _REPLENISHMENT_REQUEST;
    	public Apps.IRepository.SCV.REPLENISHMENT.IREPLENISHMENT_REQUEST_REPOSITORY REPLENISHMENT_REQUEST 
    	{ 
    		get
    		{
    			if (_REPLENISHMENT_REQUEST == null)
    				_REPLENISHMENT_REQUEST = new Apps.Repository.SCV.REPLENISHMENT.REPLENISHMENT_REQUEST_REPOSITORY();
    			return _REPLENISHMENT_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.REPORT.IREPORT_CONNECTION_REPOSITORY _REPORT_CONNECTION;
    	public Apps.IRepository.SCV.REPORT.IREPORT_CONNECTION_REPOSITORY REPORT_CONNECTION 
    	{ 
    		get
    		{
    			if (_REPORT_CONNECTION == null)
    				_REPORT_CONNECTION = new Apps.Repository.SCV.REPORT.REPORT_CONNECTION_REPOSITORY();
    			return _REPORT_CONNECTION;
    		}
    	}
    
    	Apps.IRepository.SCV.RETURNED.IRETURNED_PACKAGE_REPOSITORY _RETURNED_PACKAGE;
    	public Apps.IRepository.SCV.RETURNED.IRETURNED_PACKAGE_REPOSITORY RETURNED_PACKAGE 
    	{ 
    		get
    		{
    			if (_RETURNED_PACKAGE == null)
    				_RETURNED_PACKAGE = new Apps.Repository.SCV.RETURNED.RETURNED_PACKAGE_REPOSITORY();
    			return _RETURNED_PACKAGE;
    		}
    	}
    
    	Apps.IRepository.SCV.RULE.IRULE_ASSIGNMENT_DETAIL_REPOSITORY _RULE_ASSIGNMENT_DETAIL;
    	public Apps.IRepository.SCV.RULE.IRULE_ASSIGNMENT_DETAIL_REPOSITORY RULE_ASSIGNMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_RULE_ASSIGNMENT_DETAIL == null)
    				_RULE_ASSIGNMENT_DETAIL = new Apps.Repository.SCV.RULE.RULE_ASSIGNMENT_DETAIL_REPOSITORY();
    			return _RULE_ASSIGNMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.RULE.IRULE_ASSIGNMENT_HEADER_REPOSITORY _RULE_ASSIGNMENT_HEADER;
    	public Apps.IRepository.SCV.RULE.IRULE_ASSIGNMENT_HEADER_REPOSITORY RULE_ASSIGNMENT_HEADER 
    	{ 
    		get
    		{
    			if (_RULE_ASSIGNMENT_HEADER == null)
    				_RULE_ASSIGNMENT_HEADER = new Apps.Repository.SCV.RULE.RULE_ASSIGNMENT_HEADER_REPOSITORY();
    			return _RULE_ASSIGNMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_REPOSITORY _SCHEDULE_JOB;
    	public Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_REPOSITORY SCHEDULE_JOB 
    	{ 
    		get
    		{
    			if (_SCHEDULE_JOB == null)
    				_SCHEDULE_JOB = new Apps.Repository.SCV.SCHEDULE.SCHEDULE_JOB_REPOSITORY();
    			return _SCHEDULE_JOB;
    		}
    	}
    
    	Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_HISTORY_REPOSITORY _SCHEDULE_JOB_HISTORY;
    	public Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_HISTORY_REPOSITORY SCHEDULE_JOB_HISTORY 
    	{ 
    		get
    		{
    			if (_SCHEDULE_JOB_HISTORY == null)
    				_SCHEDULE_JOB_HISTORY = new Apps.Repository.SCV.SCHEDULE.SCHEDULE_JOB_HISTORY_REPOSITORY();
    			return _SCHEDULE_JOB_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_TYPE_REPOSITORY _SCHEDULE_JOB_TYPE;
    	public Apps.IRepository.SCV.SCHEDULE.ISCHEDULE_JOB_TYPE_REPOSITORY SCHEDULE_JOB_TYPE 
    	{ 
    		get
    		{
    			if (_SCHEDULE_JOB_TYPE == null)
    				_SCHEDULE_JOB_TYPE = new Apps.Repository.SCV.SCHEDULE.SCHEDULE_JOB_TYPE_REPOSITORY();
    			return _SCHEDULE_JOB_TYPE;
    		}
    	}
    
    	Apps.IRepository.SCV.SECURITY.ISECURITY_FUNCTION_REPOSITORY _SECURITY_FUNCTION;
    	public Apps.IRepository.SCV.SECURITY.ISECURITY_FUNCTION_REPOSITORY SECURITY_FUNCTION 
    	{ 
    		get
    		{
    			if (_SECURITY_FUNCTION == null)
    				_SECURITY_FUNCTION = new Apps.Repository.SCV.SECURITY.SECURITY_FUNCTION_REPOSITORY();
    			return _SECURITY_FUNCTION;
    		}
    	}
    
    	Apps.IRepository.SCV.SECURITY.ISECURITY_ROLE_DETAIL_REPOSITORY _SECURITY_ROLE_DETAIL;
    	public Apps.IRepository.SCV.SECURITY.ISECURITY_ROLE_DETAIL_REPOSITORY SECURITY_ROLE_DETAIL 
    	{ 
    		get
    		{
    			if (_SECURITY_ROLE_DETAIL == null)
    				_SECURITY_ROLE_DETAIL = new Apps.Repository.SCV.SECURITY.SECURITY_ROLE_DETAIL_REPOSITORY();
    			return _SECURITY_ROLE_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.SECURITY.ISECURITY_ROLE_HEADER_REPOSITORY _SECURITY_ROLE_HEADER;
    	public Apps.IRepository.SCV.SECURITY.ISECURITY_ROLE_HEADER_REPOSITORY SECURITY_ROLE_HEADER 
    	{ 
    		get
    		{
    			if (_SECURITY_ROLE_HEADER == null)
    				_SECURITY_ROLE_HEADER = new Apps.Repository.SCV.SECURITY.SECURITY_ROLE_HEADER_REPOSITORY();
    			return _SECURITY_ROLE_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.SERIAL.ISERIAL_NUMBER_REPOSITORY _SERIAL_NUMBER;
    	public Apps.IRepository.SCV.SERIAL.ISERIAL_NUMBER_REPOSITORY SERIAL_NUMBER 
    	{ 
    		get
    		{
    			if (_SERIAL_NUMBER == null)
    				_SERIAL_NUMBER = new Apps.Repository.SCV.SERIAL.SERIAL_NUMBER_REPOSITORY();
    			return _SERIAL_NUMBER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_ALLOC_REQUEST_REPOSITORY _SHIPMENT_ALLOC_REQUEST;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_ALLOC_REQUEST_REPOSITORY SHIPMENT_ALLOC_REQUEST 
    	{ 
    		get
    		{
    			if (_SHIPMENT_ALLOC_REQUEST == null)
    				_SHIPMENT_ALLOC_REQUEST = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_ALLOC_REQUEST_REPOSITORY();
    			return _SHIPMENT_ALLOC_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_CARRIER_EDITRULE_REPOSITORY _SHIPMENT_CARRIER_EDITRULE;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_CARRIER_EDITRULE_REPOSITORY SHIPMENT_CARRIER_EDITRULE 
    	{ 
    		get
    		{
    			if (_SHIPMENT_CARRIER_EDITRULE == null)
    				_SHIPMENT_CARRIER_EDITRULE = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_CARRIER_EDITRULE_REPOSITORY();
    			return _SHIPMENT_CARRIER_EDITRULE;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_DETAIL_REPOSITORY _SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_DETAIL_REPOSITORY SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_SHIPMENT_DETAIL == null)
    				_SHIPMENT_DETAIL = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_DETAIL_REPOSITORY();
    			return _SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_EXPRESS_REPOSITORY _SHIPMENT_EXPRESS;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_EXPRESS_REPOSITORY SHIPMENT_EXPRESS 
    	{ 
    		get
    		{
    			if (_SHIPMENT_EXPRESS == null)
    				_SHIPMENT_EXPRESS = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_EXPRESS_REPOSITORY();
    			return _SHIPMENT_EXPRESS;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_REPOSITORY _SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_REPOSITORY SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_SHIPMENT_HEADER == null)
    				_SHIPMENT_HEADER = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_HEADER_REPOSITORY();
    			return _SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_TEMP_REPOSITORY _SHIPMENT_HEADER_TEMP;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_TEMP_REPOSITORY SHIPMENT_HEADER_TEMP 
    	{ 
    		get
    		{
    			if (_SHIPMENT_HEADER_TEMP == null)
    				_SHIPMENT_HEADER_TEMP = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_HEADER_TEMP_REPOSITORY();
    			return _SHIPMENT_HEADER_TEMP;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_TEMP1_REPOSITORY _SHIPMENT_HEADER_TEMP1;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HEADER_TEMP1_REPOSITORY SHIPMENT_HEADER_TEMP1 
    	{ 
    		get
    		{
    			if (_SHIPMENT_HEADER_TEMP1 == null)
    				_SHIPMENT_HEADER_TEMP1 = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_HEADER_TEMP1_REPOSITORY();
    			return _SHIPMENT_HEADER_TEMP1;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_INVOICE_REPOSITORY _SHIPMENT_INVOICE;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_INVOICE_REPOSITORY SHIPMENT_INVOICE 
    	{ 
    		get
    		{
    			if (_SHIPMENT_INVOICE == null)
    				_SHIPMENT_INVOICE = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_INVOICE_REPOSITORY();
    			return _SHIPMENT_INVOICE;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_SERIAL_NUMBER_REPOSITORY _SHIPMENT_SERIAL_NUMBER;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_SERIAL_NUMBER_REPOSITORY SHIPMENT_SERIAL_NUMBER 
    	{ 
    		get
    		{
    			if (_SHIPMENT_SERIAL_NUMBER == null)
    				_SHIPMENT_SERIAL_NUMBER = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_SERIAL_NUMBER_REPOSITORY();
    			return _SHIPMENT_SERIAL_NUMBER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_TRACKING_NUMBER_REPOSITORY _SHIPMENT_TRACKING_NUMBER;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_TRACKING_NUMBER_REPOSITORY SHIPMENT_TRACKING_NUMBER 
    	{ 
    		get
    		{
    			if (_SHIPMENT_TRACKING_NUMBER == null)
    				_SHIPMENT_TRACKING_NUMBER = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_TRACKING_NUMBER_REPOSITORY();
    			return _SHIPMENT_TRACKING_NUMBER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPPING.ISHIPPING_CART_DETAIL_REPOSITORY _SHIPPING_CART_DETAIL;
    	public Apps.IRepository.SCV.SHIPPING.ISHIPPING_CART_DETAIL_REPOSITORY SHIPPING_CART_DETAIL 
    	{ 
    		get
    		{
    			if (_SHIPPING_CART_DETAIL == null)
    				_SHIPPING_CART_DETAIL = new Apps.Repository.SCV.SHIPPING.SHIPPING_CART_DETAIL_REPOSITORY();
    			return _SHIPPING_CART_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPPING.ISHIPPING_CART_HEADER_REPOSITORY _SHIPPING_CART_HEADER;
    	public Apps.IRepository.SCV.SHIPPING.ISHIPPING_CART_HEADER_REPOSITORY SHIPPING_CART_HEADER 
    	{ 
    		get
    		{
    			if (_SHIPPING_CART_HEADER == null)
    				_SHIPPING_CART_HEADER = new Apps.Repository.SCV.SHIPPING.SHIPPING_CART_HEADER_REPOSITORY();
    			return _SHIPPING_CART_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPPING.ISHIPPING_CONTAINER_REPOSITORY _SHIPPING_CONTAINER;
    	public Apps.IRepository.SCV.SHIPPING.ISHIPPING_CONTAINER_REPOSITORY SHIPPING_CONTAINER 
    	{ 
    		get
    		{
    			if (_SHIPPING_CONTAINER == null)
    				_SHIPPING_CONTAINER = new Apps.Repository.SCV.SHIPPING.SHIPPING_CONTAINER_REPOSITORY();
    			return _SHIPPING_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPPING.ISHIPPING_CONTAINER_HIS_REPOSITORY _SHIPPING_CONTAINER_HIS;
    	public Apps.IRepository.SCV.SHIPPING.ISHIPPING_CONTAINER_HIS_REPOSITORY SHIPPING_CONTAINER_HIS 
    	{ 
    		get
    		{
    			if (_SHIPPING_CONTAINER_HIS == null)
    				_SHIPPING_CONTAINER_HIS = new Apps.Repository.SCV.SHIPPING.SHIPPING_CONTAINER_HIS_REPOSITORY();
    			return _SHIPPING_CONTAINER_HIS;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPPING.ISHIPPING_LOAD_REPOSITORY _SHIPPING_LOAD;
    	public Apps.IRepository.SCV.SHIPPING.ISHIPPING_LOAD_REPOSITORY SHIPPING_LOAD 
    	{ 
    		get
    		{
    			if (_SHIPPING_LOAD == null)
    				_SHIPPING_LOAD = new Apps.Repository.SCV.SHIPPING.SHIPPING_LOAD_REPOSITORY();
    			return _SHIPPING_LOAD;
    		}
    	}
    
    	Apps.IRepository.SCV.STATISTICS.ISTATISTICS_REPORT_REPOSITORY _STATISTICS_REPORT;
    	public Apps.IRepository.SCV.STATISTICS.ISTATISTICS_REPORT_REPOSITORY STATISTICS_REPORT 
    	{ 
    		get
    		{
    			if (_STATISTICS_REPORT == null)
    				_STATISTICS_REPORT = new Apps.Repository.SCV.STATISTICS.STATISTICS_REPORT_REPOSITORY();
    			return _STATISTICS_REPORT;
    		}
    	}
    
    	Apps.IRepository.SCV.STATUS.ISTATUS_FLOW_DETAIL_REPOSITORY _STATUS_FLOW_DETAIL;
    	public Apps.IRepository.SCV.STATUS.ISTATUS_FLOW_DETAIL_REPOSITORY STATUS_FLOW_DETAIL 
    	{ 
    		get
    		{
    			if (_STATUS_FLOW_DETAIL == null)
    				_STATUS_FLOW_DETAIL = new Apps.Repository.SCV.STATUS.STATUS_FLOW_DETAIL_REPOSITORY();
    			return _STATUS_FLOW_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.STATUS.ISTATUS_FLOW_HEADER_REPOSITORY _STATUS_FLOW_HEADER;
    	public Apps.IRepository.SCV.STATUS.ISTATUS_FLOW_HEADER_REPOSITORY STATUS_FLOW_HEADER 
    	{ 
    		get
    		{
    			if (_STATUS_FLOW_HEADER == null)
    				_STATUS_FLOW_HEADER = new Apps.Repository.SCV.STATUS.STATUS_FLOW_HEADER_REPOSITORY();
    			return _STATUS_FLOW_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_CREATION_MASTER_REPOSITORY _TASK_CREATION_MASTER;
    	public Apps.IRepository.SCV.TASK.ITASK_CREATION_MASTER_REPOSITORY TASK_CREATION_MASTER 
    	{ 
    		get
    		{
    			if (_TASK_CREATION_MASTER == null)
    				_TASK_CREATION_MASTER = new Apps.Repository.SCV.TASK.TASK_CREATION_MASTER_REPOSITORY();
    			return _TASK_CREATION_MASTER;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_DETAIL_REPOSITORY _TASK_DETAIL;
    	public Apps.IRepository.SCV.TASK.ITASK_DETAIL_REPOSITORY TASK_DETAIL 
    	{ 
    		get
    		{
    			if (_TASK_DETAIL == null)
    				_TASK_DETAIL = new Apps.Repository.SCV.TASK.TASK_DETAIL_REPOSITORY();
    			return _TASK_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_HANDLING_OPTION_REPOSITORY _TASK_HANDLING_OPTION;
    	public Apps.IRepository.SCV.TASK.ITASK_HANDLING_OPTION_REPOSITORY TASK_HANDLING_OPTION 
    	{ 
    		get
    		{
    			if (_TASK_HANDLING_OPTION == null)
    				_TASK_HANDLING_OPTION = new Apps.Repository.SCV.TASK.TASK_HANDLING_OPTION_REPOSITORY();
    			return _TASK_HANDLING_OPTION;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_HEADER_REPOSITORY _TASK_HEADER;
    	public Apps.IRepository.SCV.TASK.ITASK_HEADER_REPOSITORY TASK_HEADER 
    	{ 
    		get
    		{
    			if (_TASK_HEADER == null)
    				_TASK_HEADER = new Apps.Repository.SCV.TASK.TASK_HEADER_REPOSITORY();
    			return _TASK_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_PREF_USER_AUTH_REPOSITORY _TASK_PREF_USER_AUTH;
    	public Apps.IRepository.SCV.TASK.ITASK_PREF_USER_AUTH_REPOSITORY TASK_PREF_USER_AUTH 
    	{ 
    		get
    		{
    			if (_TASK_PREF_USER_AUTH == null)
    				_TASK_PREF_USER_AUTH = new Apps.Repository.SCV.TASK.TASK_PREF_USER_AUTH_REPOSITORY();
    			return _TASK_PREF_USER_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.TASK.ITASK_PREFERENCE_REPOSITORY _TASK_PREFERENCE;
    	public Apps.IRepository.SCV.TASK.ITASK_PREFERENCE_REPOSITORY TASK_PREFERENCE 
    	{ 
    		get
    		{
    			if (_TASK_PREFERENCE == null)
    				_TASK_PREFERENCE = new Apps.Repository.SCV.TASK.TASK_PREFERENCE_REPOSITORY();
    			return _TASK_PREFERENCE;
    		}
    	}
    
    	Apps.IRepository.SCV.TRANSACTION.ITRANSACTION_HISTORY_REPOSITORY _TRANSACTION_HISTORY;
    	public Apps.IRepository.SCV.TRANSACTION.ITRANSACTION_HISTORY_REPOSITORY TRANSACTION_HISTORY 
    	{ 
    		get
    		{
    			if (_TRANSACTION_HISTORY == null)
    				_TRANSACTION_HISTORY = new Apps.Repository.SCV.TRANSACTION.TRANSACTION_HISTORY_REPOSITORY();
    			return _TRANSACTION_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.TRANSFER.ITRANSFER_LOCATE_REQUEST_REPOSITORY _TRANSFER_LOCATE_REQUEST;
    	public Apps.IRepository.SCV.TRANSFER.ITRANSFER_LOCATE_REQUEST_REPOSITORY TRANSFER_LOCATE_REQUEST 
    	{ 
    		get
    		{
    			if (_TRANSFER_LOCATE_REQUEST == null)
    				_TRANSFER_LOCATE_REQUEST = new Apps.Repository.SCV.TRANSFER.TRANSFER_LOCATE_REQUEST_REPOSITORY();
    			return _TRANSFER_LOCATE_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_DETAIL_REPOSITORY _TRANSFER_ORDER_DETAIL;
    	public Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_DETAIL_REPOSITORY TRANSFER_ORDER_DETAIL 
    	{ 
    		get
    		{
    			if (_TRANSFER_ORDER_DETAIL == null)
    				_TRANSFER_ORDER_DETAIL = new Apps.Repository.SCV.TRANSFER.TRANSFER_ORDER_DETAIL_REPOSITORY();
    			return _TRANSFER_ORDER_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_HEADER_REPOSITORY _TRANSFER_ORDER_HEADER;
    	public Apps.IRepository.SCV.TRANSFER.ITRANSFER_ORDER_HEADER_REPOSITORY TRANSFER_ORDER_HEADER 
    	{ 
    		get
    		{
    			if (_TRANSFER_ORDER_HEADER == null)
    				_TRANSFER_ORDER_HEADER = new Apps.Repository.SCV.TRANSFER.TRANSFER_ORDER_HEADER_REPOSITORY();
    			return _TRANSFER_ORDER_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_INVENTORY_REPOSITORY _UPLOAD_INVENTORY;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_INVENTORY_REPOSITORY UPLOAD_INVENTORY 
    	{ 
    		get
    		{
    			if (_UPLOAD_INVENTORY == null)
    				_UPLOAD_INVENTORY = new Apps.Repository.SCV.UPLOAD.UPLOAD_INVENTORY_REPOSITORY();
    			return _UPLOAD_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_INVENTORY_TRANS_REPOSITORY _UPLOAD_INVENTORY_TRANS;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_INVENTORY_TRANS_REPOSITORY UPLOAD_INVENTORY_TRANS 
    	{ 
    		get
    		{
    			if (_UPLOAD_INVENTORY_TRANS == null)
    				_UPLOAD_INVENTORY_TRANS = new Apps.Repository.SCV.UPLOAD.UPLOAD_INVENTORY_TRANS_REPOSITORY();
    			return _UPLOAD_INVENTORY_TRANS;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_LOCATION_INVENTORY_REPOSITORY _UPLOAD_LOCATION_INVENTORY;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_LOCATION_INVENTORY_REPOSITORY UPLOAD_LOCATION_INVENTORY 
    	{ 
    		get
    		{
    			if (_UPLOAD_LOCATION_INVENTORY == null)
    				_UPLOAD_LOCATION_INVENTORY = new Apps.Repository.SCV.UPLOAD.UPLOAD_LOCATION_INVENTORY_REPOSITORY();
    			return _UPLOAD_LOCATION_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_OBJECT_REPOSITORY _UPLOAD_OBJECT;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_OBJECT_REPOSITORY UPLOAD_OBJECT 
    	{ 
    		get
    		{
    			if (_UPLOAD_OBJECT == null)
    				_UPLOAD_OBJECT = new Apps.Repository.SCV.UPLOAD.UPLOAD_OBJECT_REPOSITORY();
    			return _UPLOAD_OBJECT;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_ORDER_STATUS_REPOSITORY _UPLOAD_ORDER_STATUS;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_ORDER_STATUS_REPOSITORY UPLOAD_ORDER_STATUS 
    	{ 
    		get
    		{
    			if (_UPLOAD_ORDER_STATUS == null)
    				_UPLOAD_ORDER_STATUS = new Apps.Repository.SCV.UPLOAD.UPLOAD_ORDER_STATUS_REPOSITORY();
    			return _UPLOAD_ORDER_STATUS;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_CONTAINER_REPOSITORY _UPLOAD_RECEIPT_CONTAINER;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_CONTAINER_REPOSITORY UPLOAD_RECEIPT_CONTAINER 
    	{ 
    		get
    		{
    			if (_UPLOAD_RECEIPT_CONTAINER == null)
    				_UPLOAD_RECEIPT_CONTAINER = new Apps.Repository.SCV.UPLOAD.UPLOAD_RECEIPT_CONTAINER_REPOSITORY();
    			return _UPLOAD_RECEIPT_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_DETAIL_REPOSITORY _UPLOAD_RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_DETAIL_REPOSITORY UPLOAD_RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_UPLOAD_RECEIPT_DETAIL == null)
    				_UPLOAD_RECEIPT_DETAIL = new Apps.Repository.SCV.UPLOAD.UPLOAD_RECEIPT_DETAIL_REPOSITORY();
    			return _UPLOAD_RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_HEADER_REPOSITORY _UPLOAD_RECEIPT_HEADER;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPT_HEADER_REPOSITORY UPLOAD_RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_UPLOAD_RECEIPT_HEADER == null)
    				_UPLOAD_RECEIPT_HEADER = new Apps.Repository.SCV.UPLOAD.UPLOAD_RECEIPT_HEADER_REPOSITORY();
    			return _UPLOAD_RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPTS_REPOSITORY _UPLOAD_RECEIPTS;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_RECEIPTS_REPOSITORY UPLOAD_RECEIPTS 
    	{ 
    		get
    		{
    			if (_UPLOAD_RECEIPTS == null)
    				_UPLOAD_RECEIPTS = new Apps.Repository.SCV.UPLOAD.UPLOAD_RECEIPTS_REPOSITORY();
    			return _UPLOAD_RECEIPTS;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_DETAIL_REPOSITORY _UPLOAD_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_DETAIL_REPOSITORY UPLOAD_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_UPLOAD_SHIPMENT_DETAIL == null)
    				_UPLOAD_SHIPMENT_DETAIL = new Apps.Repository.SCV.UPLOAD.UPLOAD_SHIPMENT_DETAIL_REPOSITORY();
    			return _UPLOAD_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_HEADER_REPOSITORY _UPLOAD_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_HEADER_REPOSITORY UPLOAD_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_UPLOAD_SHIPMENT_HEADER == null)
    				_UPLOAD_SHIPMENT_HEADER = new Apps.Repository.SCV.UPLOAD.UPLOAD_SHIPMENT_HEADER_REPOSITORY();
    			return _UPLOAD_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPPING_CONTAINER_REPOSITORY _UPLOAD_SHIPPING_CONTAINER;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPPING_CONTAINER_REPOSITORY UPLOAD_SHIPPING_CONTAINER 
    	{ 
    		get
    		{
    			if (_UPLOAD_SHIPPING_CONTAINER == null)
    				_UPLOAD_SHIPPING_CONTAINER = new Apps.Repository.SCV.UPLOAD.UPLOAD_SHIPPING_CONTAINER_REPOSITORY();
    			return _UPLOAD_SHIPPING_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IUSER_REPOSITORY _USER;
    	public Apps.IRepository.SCV.Sys.IUSER_REPOSITORY USER 
    	{ 
    		get
    		{
    			if (_USER == null)
    				_USER = new Apps.Repository.SCV.Sys.USER_REPOSITORY();
    			return _USER;
    		}
    	}
    
    	Apps.IRepository.SCV.USER.IUSER_COMPANY_AUTH_REPOSITORY _USER_COMPANY_AUTH;
    	public Apps.IRepository.SCV.USER.IUSER_COMPANY_AUTH_REPOSITORY USER_COMPANY_AUTH 
    	{ 
    		get
    		{
    			if (_USER_COMPANY_AUTH == null)
    				_USER_COMPANY_AUTH = new Apps.Repository.SCV.USER.USER_COMPANY_AUTH_REPOSITORY();
    			return _USER_COMPANY_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.USER.IUSER_WAREHOUSE_AUTH_REPOSITORY _USER_WAREHOUSE_AUTH;
    	public Apps.IRepository.SCV.USER.IUSER_WAREHOUSE_AUTH_REPOSITORY USER_WAREHOUSE_AUTH 
    	{ 
    		get
    		{
    			if (_USER_WAREHOUSE_AUTH == null)
    				_USER_WAREHOUSE_AUTH = new Apps.Repository.SCV.USER.USER_WAREHOUSE_AUTH_REPOSITORY();
    			return _USER_WAREHOUSE_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.USER.IUSER_ZONE_AUTH_REPOSITORY _USER_ZONE_AUTH;
    	public Apps.IRepository.SCV.USER.IUSER_ZONE_AUTH_REPOSITORY USER_ZONE_AUTH 
    	{ 
    		get
    		{
    			if (_USER_ZONE_AUTH == null)
    				_USER_ZONE_AUTH = new Apps.Repository.SCV.USER.USER_ZONE_AUTH_REPOSITORY();
    			return _USER_ZONE_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IVENDOR_REPOSITORY _VENDOR;
    	public Apps.IRepository.SCV.Sys.IVENDOR_REPOSITORY VENDOR 
    	{ 
    		get
    		{
    			if (_VENDOR == null)
    				_VENDOR = new Apps.Repository.SCV.Sys.VENDOR_REPOSITORY();
    			return _VENDOR;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IVIEWER_REPOSITORY _VIEWER;
    	public Apps.IRepository.SCV.Sys.IVIEWER_REPOSITORY VIEWER 
    	{ 
    		get
    		{
    			if (_VIEWER == null)
    				_VIEWER = new Apps.Repository.SCV.Sys.VIEWER_REPOSITORY();
    			return _VIEWER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IWAREHOUSE_REPOSITORY _WAREHOUSE;
    	public Apps.IRepository.SCV.Sys.IWAREHOUSE_REPOSITORY WAREHOUSE 
    	{ 
    		get
    		{
    			if (_WAREHOUSE == null)
    				_WAREHOUSE = new Apps.Repository.SCV.Sys.WAREHOUSE_REPOSITORY();
    			return _WAREHOUSE;
    		}
    	}
    
    	Apps.IRepository.SCV.WAREHOUSE.IWAREHOUSE_ACTIVITY_REPOSITORY _WAREHOUSE_ACTIVITY;
    	public Apps.IRepository.SCV.WAREHOUSE.IWAREHOUSE_ACTIVITY_REPOSITORY WAREHOUSE_ACTIVITY 
    	{ 
    		get
    		{
    			if (_WAREHOUSE_ACTIVITY == null)
    				_WAREHOUSE_ACTIVITY = new Apps.Repository.SCV.WAREHOUSE.WAREHOUSE_ACTIVITY_REPOSITORY();
    			return _WAREHOUSE_ACTIVITY;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IWAVE_REPOSITORY _WAVE;
    	public Apps.IRepository.SCV.Sys.IWAVE_REPOSITORY WAVE 
    	{ 
    		get
    		{
    			if (_WAVE == null)
    				_WAVE = new Apps.Repository.SCV.Sys.WAVE_REPOSITORY();
    			return _WAVE;
    		}
    	}
    
    	Apps.IRepository.SCV.WAVE.IWAVE_FLOW_DETAIL_REPOSITORY _WAVE_FLOW_DETAIL;
    	public Apps.IRepository.SCV.WAVE.IWAVE_FLOW_DETAIL_REPOSITORY WAVE_FLOW_DETAIL 
    	{ 
    		get
    		{
    			if (_WAVE_FLOW_DETAIL == null)
    				_WAVE_FLOW_DETAIL = new Apps.Repository.SCV.WAVE.WAVE_FLOW_DETAIL_REPOSITORY();
    			return _WAVE_FLOW_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.WAVE.IWAVE_FLOW_HEADER_REPOSITORY _WAVE_FLOW_HEADER;
    	public Apps.IRepository.SCV.WAVE.IWAVE_FLOW_HEADER_REPOSITORY WAVE_FLOW_HEADER 
    	{ 
    		get
    		{
    			if (_WAVE_FLOW_HEADER == null)
    				_WAVE_FLOW_HEADER = new Apps.Repository.SCV.WAVE.WAVE_FLOW_HEADER_REPOSITORY();
    			return _WAVE_FLOW_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.WAVE.IWAVE_MASTER_REPOSITORY _WAVE_MASTER;
    	public Apps.IRepository.SCV.WAVE.IWAVE_MASTER_REPOSITORY WAVE_MASTER 
    	{ 
    		get
    		{
    			if (_WAVE_MASTER == null)
    				_WAVE_MASTER = new Apps.Repository.SCV.WAVE.WAVE_MASTER_REPOSITORY();
    			return _WAVE_MASTER;
    		}
    	}
    
    	Apps.IRepository.SCV.WAYBILL.IWAYBILL_INFO_REPOSITORY _WAYBILL_INFO;
    	public Apps.IRepository.SCV.WAYBILL.IWAYBILL_INFO_REPOSITORY WAYBILL_INFO 
    	{ 
    		get
    		{
    			if (_WAYBILL_INFO == null)
    				_WAYBILL_INFO = new Apps.Repository.SCV.WAYBILL.WAYBILL_INFO_REPOSITORY();
    			return _WAYBILL_INFO;
    		}
    	}
    
    	Apps.IRepository.SCV.WORK.IWORK_OPTION_REPOSITORY _WORK_OPTION;
    	public Apps.IRepository.SCV.WORK.IWORK_OPTION_REPOSITORY WORK_OPTION 
    	{ 
    		get
    		{
    			if (_WORK_OPTION == null)
    				_WORK_OPTION = new Apps.Repository.SCV.WORK.WORK_OPTION_REPOSITORY();
    			return _WORK_OPTION;
    		}
    	}
    
    	Apps.IRepository.SCV.WORK.IWORK_ORDER_DETAIL_REPOSITORY _WORK_ORDER_DETAIL;
    	public Apps.IRepository.SCV.WORK.IWORK_ORDER_DETAIL_REPOSITORY WORK_ORDER_DETAIL 
    	{ 
    		get
    		{
    			if (_WORK_ORDER_DETAIL == null)
    				_WORK_ORDER_DETAIL = new Apps.Repository.SCV.WORK.WORK_ORDER_DETAIL_REPOSITORY();
    			return _WORK_ORDER_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.WORK.IWORK_ORDER_HEADER_REPOSITORY _WORK_ORDER_HEADER;
    	public Apps.IRepository.SCV.WORK.IWORK_ORDER_HEADER_REPOSITORY WORK_ORDER_HEADER 
    	{ 
    		get
    		{
    			if (_WORK_ORDER_HEADER == null)
    				_WORK_ORDER_HEADER = new Apps.Repository.SCV.WORK.WORK_ORDER_HEADER_REPOSITORY();
    			return _WORK_ORDER_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IZONE_REPOSITORY _ZONE;
    	public Apps.IRepository.SCV.Sys.IZONE_REPOSITORY ZONE 
    	{ 
    		get
    		{
    			if (_ZONE == null)
    				_ZONE = new Apps.Repository.SCV.Sys.ZONE_REPOSITORY();
    			return _ZONE;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_REPOSITORY _AR_DOWNLOAD_ITEM;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_REPOSITORY AR_DOWNLOAD_ITEM 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_ITEM == null)
    				_AR_DOWNLOAD_ITEM = new Apps.Repository.SCV.AR.AR_DOWNLOAD_ITEM_REPOSITORY();
    			return _AR_DOWNLOAD_ITEM;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_BARCODE_REPOSITORY _AR_DOWNLOAD_ITEM_BARCODE;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_BARCODE_REPOSITORY AR_DOWNLOAD_ITEM_BARCODE 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_ITEM_BARCODE == null)
    				_AR_DOWNLOAD_ITEM_BARCODE = new Apps.Repository.SCV.AR.AR_DOWNLOAD_ITEM_BARCODE_REPOSITORY();
    			return _AR_DOWNLOAD_ITEM_BARCODE;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY _AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE == null)
    				_AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE = new Apps.Repository.SCV.AR.AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE_REPOSITORY();
    			return _AR_DOWNLOAD_ITEM_UNIT_OF_MEASURE;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_RECEIPT_DETAIL_REPOSITORY _AR_DOWNLOAD_RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_RECEIPT_DETAIL_REPOSITORY AR_DOWNLOAD_RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_RECEIPT_DETAIL == null)
    				_AR_DOWNLOAD_RECEIPT_DETAIL = new Apps.Repository.SCV.AR.AR_DOWNLOAD_RECEIPT_DETAIL_REPOSITORY();
    			return _AR_DOWNLOAD_RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_RECEIPT_HEADER_REPOSITORY _AR_DOWNLOAD_RECEIPT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_RECEIPT_HEADER_REPOSITORY AR_DOWNLOAD_RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_RECEIPT_HEADER == null)
    				_AR_DOWNLOAD_RECEIPT_HEADER = new Apps.Repository.SCV.AR.AR_DOWNLOAD_RECEIPT_HEADER_REPOSITORY();
    			return _AR_DOWNLOAD_RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_SHIPMENT_DETAIL_REPOSITORY _AR_DOWNLOAD_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_SHIPMENT_DETAIL_REPOSITORY AR_DOWNLOAD_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_SHIPMENT_DETAIL == null)
    				_AR_DOWNLOAD_SHIPMENT_DETAIL = new Apps.Repository.SCV.AR.AR_DOWNLOAD_SHIPMENT_DETAIL_REPOSITORY();
    			return _AR_DOWNLOAD_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_DOWNLOAD_SHIPMENT_HEADER_REPOSITORY _AR_DOWNLOAD_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_DOWNLOAD_SHIPMENT_HEADER_REPOSITORY AR_DOWNLOAD_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_DOWNLOAD_SHIPMENT_HEADER == null)
    				_AR_DOWNLOAD_SHIPMENT_HEADER = new Apps.Repository.SCV.AR.AR_DOWNLOAD_SHIPMENT_HEADER_REPOSITORY();
    			return _AR_DOWNLOAD_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_LOCATION_INVENTORY_REPOSITORY _AR_LOCATION_INVENTORY;
    	public Apps.IRepository.SCV.AR.IAR_LOCATION_INVENTORY_REPOSITORY AR_LOCATION_INVENTORY 
    	{ 
    		get
    		{
    			if (_AR_LOCATION_INVENTORY == null)
    				_AR_LOCATION_INVENTORY = new Apps.Repository.SCV.AR.AR_LOCATION_INVENTORY_REPOSITORY();
    			return _AR_LOCATION_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_PROCESS_HISTORY_REPOSITORY _AR_PROCESS_HISTORY;
    	public Apps.IRepository.SCV.AR.IAR_PROCESS_HISTORY_REPOSITORY AR_PROCESS_HISTORY 
    	{ 
    		get
    		{
    			if (_AR_PROCESS_HISTORY == null)
    				_AR_PROCESS_HISTORY = new Apps.Repository.SCV.AR.AR_PROCESS_HISTORY_REPOSITORY();
    			return _AR_PROCESS_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_RECEIPT_LOCATE_REQUEST_REPOSITORY _AR_RECEIPT_LOCATE_REQUEST;
    	public Apps.IRepository.SCV.AR.IAR_RECEIPT_LOCATE_REQUEST_REPOSITORY AR_RECEIPT_LOCATE_REQUEST 
    	{ 
    		get
    		{
    			if (_AR_RECEIPT_LOCATE_REQUEST == null)
    				_AR_RECEIPT_LOCATE_REQUEST = new Apps.Repository.SCV.AR.AR_RECEIPT_LOCATE_REQUEST_REPOSITORY();
    			return _AR_RECEIPT_LOCATE_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPMENT_ALLOC_REQUEST_REPOSITORY _AR_SHIPMENT_ALLOC_REQUEST;
    	public Apps.IRepository.SCV.AR.IAR_SHIPMENT_ALLOC_REQUEST_REPOSITORY AR_SHIPMENT_ALLOC_REQUEST 
    	{ 
    		get
    		{
    			if (_AR_SHIPMENT_ALLOC_REQUEST == null)
    				_AR_SHIPMENT_ALLOC_REQUEST = new Apps.Repository.SCV.AR.AR_SHIPMENT_ALLOC_REQUEST_REPOSITORY();
    			return _AR_SHIPMENT_ALLOC_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPMENT_DETAIL_REPOSITORY _AR_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_SHIPMENT_DETAIL_REPOSITORY AR_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_SHIPMENT_DETAIL == null)
    				_AR_SHIPMENT_DETAIL = new Apps.Repository.SCV.AR.AR_SHIPMENT_DETAIL_REPOSITORY();
    			return _AR_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPMENT_HEADER_REPOSITORY _AR_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_SHIPMENT_HEADER_REPOSITORY AR_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_SHIPMENT_HEADER == null)
    				_AR_SHIPMENT_HEADER = new Apps.Repository.SCV.AR.AR_SHIPMENT_HEADER_REPOSITORY();
    			return _AR_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPMENT_HISTORY_REPOSITORY _AR_SHIPMENT_HISTORY;
    	public Apps.IRepository.SCV.AR.IAR_SHIPMENT_HISTORY_REPOSITORY AR_SHIPMENT_HISTORY 
    	{ 
    		get
    		{
    			if (_AR_SHIPMENT_HISTORY == null)
    				_AR_SHIPMENT_HISTORY = new Apps.Repository.SCV.AR.AR_SHIPMENT_HISTORY_REPOSITORY();
    			return _AR_SHIPMENT_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPPING_CONTAINER_REPOSITORY _AR_SHIPPING_CONTAINER;
    	public Apps.IRepository.SCV.AR.IAR_SHIPPING_CONTAINER_REPOSITORY AR_SHIPPING_CONTAINER 
    	{ 
    		get
    		{
    			if (_AR_SHIPPING_CONTAINER == null)
    				_AR_SHIPPING_CONTAINER = new Apps.Repository.SCV.AR.AR_SHIPPING_CONTAINER_REPOSITORY();
    			return _AR_SHIPPING_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_SHIPPING_LOAD_REPOSITORY _AR_SHIPPING_LOAD;
    	public Apps.IRepository.SCV.AR.IAR_SHIPPING_LOAD_REPOSITORY AR_SHIPPING_LOAD 
    	{ 
    		get
    		{
    			if (_AR_SHIPPING_LOAD == null)
    				_AR_SHIPPING_LOAD = new Apps.Repository.SCV.AR.AR_SHIPPING_LOAD_REPOSITORY();
    			return _AR_SHIPPING_LOAD;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_INVENTORY_REPOSITORY _AR_UPLOAD_INVENTORY;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_INVENTORY_REPOSITORY AR_UPLOAD_INVENTORY 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_INVENTORY == null)
    				_AR_UPLOAD_INVENTORY = new Apps.Repository.SCV.AR.AR_UPLOAD_INVENTORY_REPOSITORY();
    			return _AR_UPLOAD_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_INVENTORY_TRANS_REPOSITORY _AR_UPLOAD_INVENTORY_TRANS;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_INVENTORY_TRANS_REPOSITORY AR_UPLOAD_INVENTORY_TRANS 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_INVENTORY_TRANS == null)
    				_AR_UPLOAD_INVENTORY_TRANS = new Apps.Repository.SCV.AR.AR_UPLOAD_INVENTORY_TRANS_REPOSITORY();
    			return _AR_UPLOAD_INVENTORY_TRANS;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_LOCATION_INVENTORY_REPOSITORY _AR_UPLOAD_LOCATION_INVENTORY;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_LOCATION_INVENTORY_REPOSITORY AR_UPLOAD_LOCATION_INVENTORY 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_LOCATION_INVENTORY == null)
    				_AR_UPLOAD_LOCATION_INVENTORY = new Apps.Repository.SCV.AR.AR_UPLOAD_LOCATION_INVENTORY_REPOSITORY();
    			return _AR_UPLOAD_LOCATION_INVENTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_ORDER_STATUS_REPOSITORY _AR_UPLOAD_ORDER_STATUS;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_ORDER_STATUS_REPOSITORY AR_UPLOAD_ORDER_STATUS 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_ORDER_STATUS == null)
    				_AR_UPLOAD_ORDER_STATUS = new Apps.Repository.SCV.AR.AR_UPLOAD_ORDER_STATUS_REPOSITORY();
    			return _AR_UPLOAD_ORDER_STATUS;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_CONTAINER_REPOSITORY _AR_UPLOAD_RECEIPT_CONTAINER;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_CONTAINER_REPOSITORY AR_UPLOAD_RECEIPT_CONTAINER 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_RECEIPT_CONTAINER == null)
    				_AR_UPLOAD_RECEIPT_CONTAINER = new Apps.Repository.SCV.AR.AR_UPLOAD_RECEIPT_CONTAINER_REPOSITORY();
    			return _AR_UPLOAD_RECEIPT_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_DETAIL_REPOSITORY _AR_UPLOAD_RECEIPT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_DETAIL_REPOSITORY AR_UPLOAD_RECEIPT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_RECEIPT_DETAIL == null)
    				_AR_UPLOAD_RECEIPT_DETAIL = new Apps.Repository.SCV.AR.AR_UPLOAD_RECEIPT_DETAIL_REPOSITORY();
    			return _AR_UPLOAD_RECEIPT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_HEADER_REPOSITORY _AR_UPLOAD_RECEIPT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_RECEIPT_HEADER_REPOSITORY AR_UPLOAD_RECEIPT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_RECEIPT_HEADER == null)
    				_AR_UPLOAD_RECEIPT_HEADER = new Apps.Repository.SCV.AR.AR_UPLOAD_RECEIPT_HEADER_REPOSITORY();
    			return _AR_UPLOAD_RECEIPT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPMENT_DETAIL_REPOSITORY _AR_UPLOAD_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPMENT_DETAIL_REPOSITORY AR_UPLOAD_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_SHIPMENT_DETAIL == null)
    				_AR_UPLOAD_SHIPMENT_DETAIL = new Apps.Repository.SCV.AR.AR_UPLOAD_SHIPMENT_DETAIL_REPOSITORY();
    			return _AR_UPLOAD_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPMENT_HEADER_REPOSITORY _AR_UPLOAD_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPMENT_HEADER_REPOSITORY AR_UPLOAD_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_SHIPMENT_HEADER == null)
    				_AR_UPLOAD_SHIPMENT_HEADER = new Apps.Repository.SCV.AR.AR_UPLOAD_SHIPMENT_HEADER_REPOSITORY();
    			return _AR_UPLOAD_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPPING_CONTAINER_REPOSITORY _AR_UPLOAD_SHIPPING_CONTAINER;
    	public Apps.IRepository.SCV.AR.IAR_UPLOAD_SHIPPING_CONTAINER_REPOSITORY AR_UPLOAD_SHIPPING_CONTAINER 
    	{ 
    		get
    		{
    			if (_AR_UPLOAD_SHIPPING_CONTAINER == null)
    				_AR_UPLOAD_SHIPPING_CONTAINER = new Apps.Repository.SCV.AR.AR_UPLOAD_SHIPPING_CONTAINER_REPOSITORY();
    			return _AR_UPLOAD_SHIPPING_CONTAINER;
    		}
    	}
    
    	Apps.IRepository.SCV.CHART.ICHART_CONFIG_REPOSITORY _CHART_CONFIG;
    	public Apps.IRepository.SCV.CHART.ICHART_CONFIG_REPOSITORY CHART_CONFIG 
    	{ 
    		get
    		{
    			if (_CHART_CONFIG == null)
    				_CHART_CONFIG = new Apps.Repository.SCV.CHART.CHART_CONFIG_REPOSITORY();
    			return _CHART_CONFIG;
    		}
    	}
    
    	Apps.IRepository.SCV.CONSOLIDATE.ICONSOLIDATE_SHIPMENT_HEADER_REPOSITORY _CONSOLIDATE_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.CONSOLIDATE.ICONSOLIDATE_SHIPMENT_HEADER_REPOSITORY CONSOLIDATE_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_CONSOLIDATE_SHIPMENT_HEADER == null)
    				_CONSOLIDATE_SHIPMENT_HEADER = new Apps.Repository.SCV.CONSOLIDATE.CONSOLIDATE_SHIPMENT_HEADER_REPOSITORY();
    			return _CONSOLIDATE_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_PREFERENCE_REPOSITORY _CYCLE_COUNT_PREFERENCE;
    	public Apps.IRepository.SCV.CYCLE.ICYCLE_COUNT_PREFERENCE_REPOSITORY CYCLE_COUNT_PREFERENCE 
    	{ 
    		get
    		{
    			if (_CYCLE_COUNT_PREFERENCE == null)
    				_CYCLE_COUNT_PREFERENCE = new Apps.Repository.SCV.CYCLE.CYCLE_COUNT_PREFERENCE_REPOSITORY();
    			return _CYCLE_COUNT_PREFERENCE;
    		}
    	}
    
    	Apps.IRepository.SCV.DELETED.IDELETED_SHIPMENT_DETAIL_REPOSITORY _DELETED_SHIPMENT_DETAIL;
    	public Apps.IRepository.SCV.DELETED.IDELETED_SHIPMENT_DETAIL_REPOSITORY DELETED_SHIPMENT_DETAIL 
    	{ 
    		get
    		{
    			if (_DELETED_SHIPMENT_DETAIL == null)
    				_DELETED_SHIPMENT_DETAIL = new Apps.Repository.SCV.DELETED.DELETED_SHIPMENT_DETAIL_REPOSITORY();
    			return _DELETED_SHIPMENT_DETAIL;
    		}
    	}
    
    	Apps.IRepository.SCV.DELETED.IDELETED_SHIPMENT_HEADER_REPOSITORY _DELETED_SHIPMENT_HEADER;
    	public Apps.IRepository.SCV.DELETED.IDELETED_SHIPMENT_HEADER_REPOSITORY DELETED_SHIPMENT_HEADER 
    	{ 
    		get
    		{
    			if (_DELETED_SHIPMENT_HEADER == null)
    				_DELETED_SHIPMENT_HEADER = new Apps.Repository.SCV.DELETED.DELETED_SHIPMENT_HEADER_REPOSITORY();
    			return _DELETED_SHIPMENT_HEADER;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_HEADER_FAILED_REPOSITORY _DOWNLOAD_RECEIPT_HEADER_FAILED;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_RECEIPT_HEADER_FAILED_REPOSITORY DOWNLOAD_RECEIPT_HEADER_FAILED 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_RECEIPT_HEADER_FAILED == null)
    				_DOWNLOAD_RECEIPT_HEADER_FAILED = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_RECEIPT_HEADER_FAILED_REPOSITORY();
    			return _DOWNLOAD_RECEIPT_HEADER_FAILED;
    		}
    	}
    
    	Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_HEADER_FAILED_REPOSITORY _DOWNLOAD_SHIPMENT_HEADER_FAILED;
    	public Apps.IRepository.SCV.DOWNLOAD.IDOWNLOAD_SHIPMENT_HEADER_FAILED_REPOSITORY DOWNLOAD_SHIPMENT_HEADER_FAILED 
    	{ 
    		get
    		{
    			if (_DOWNLOAD_SHIPMENT_HEADER_FAILED == null)
    				_DOWNLOAD_SHIPMENT_HEADER_FAILED = new Apps.Repository.SCV.DOWNLOAD.DOWNLOAD_SHIPMENT_HEADER_FAILED_REPOSITORY();
    			return _DOWNLOAD_SHIPMENT_HEADER_FAILED;
    		}
    	}
    
    	Apps.IRepository.SCV.END.IEND_POINT_REPOSITORY _END_POINT;
    	public Apps.IRepository.SCV.END.IEND_POINT_REPOSITORY END_POINT 
    	{ 
    		get
    		{
    			if (_END_POINT == null)
    				_END_POINT = new Apps.Repository.SCV.END.END_POINT_REPOSITORY();
    			return _END_POINT;
    		}
    	}
    
    	Apps.IRepository.SCV.g.Ig_login_history_REPOSITORY _g_login_history;
    	public Apps.IRepository.SCV.g.Ig_login_history_REPOSITORY g_login_history 
    	{ 
    		get
    		{
    			if (_g_login_history == null)
    				_g_login_history = new Apps.Repository.SCV.g.g_login_history_REPOSITORY();
    			return _g_login_history;
    		}
    	}
    
    	Apps.IRepository.SCV.g.Ig_user_REPOSITORY _g_user;
    	public Apps.IRepository.SCV.g.Ig_user_REPOSITORY g_user 
    	{ 
    		get
    		{
    			if (_g_user == null)
    				_g_user = new Apps.Repository.SCV.g.g_user_REPOSITORY();
    			return _g_user;
    		}
    	}
    
    	Apps.IRepository.SCV.GENERIC.IGENERIC_USER_AUTH_REPOSITORY _GENERIC_USER_AUTH;
    	public Apps.IRepository.SCV.GENERIC.IGENERIC_USER_AUTH_REPOSITORY GENERIC_USER_AUTH 
    	{ 
    		get
    		{
    			if (_GENERIC_USER_AUTH == null)
    				_GENERIC_USER_AUTH = new Apps.Repository.SCV.GENERIC.GENERIC_USER_AUTH_REPOSITORY();
    			return _GENERIC_USER_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.GSP.IGSP_CODE_REPOSITORY _GSP_CODE;
    	public Apps.IRepository.SCV.GSP.IGSP_CODE_REPOSITORY GSP_CODE 
    	{ 
    		get
    		{
    			if (_GSP_CODE == null)
    				_GSP_CODE = new Apps.Repository.SCV.GSP.GSP_CODE_REPOSITORY();
    			return _GSP_CODE;
    		}
    	}
    
    	Apps.IRepository.SCV.INTERFACE.IINTERFACE_REQUEST_REPOSITORY _INTERFACE_REQUEST;
    	public Apps.IRepository.SCV.INTERFACE.IINTERFACE_REQUEST_REPOSITORY INTERFACE_REQUEST 
    	{ 
    		get
    		{
    			if (_INTERFACE_REQUEST == null)
    				_INTERFACE_REQUEST = new Apps.Repository.SCV.INTERFACE.INTERFACE_REQUEST_REPOSITORY();
    			return _INTERFACE_REQUEST;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_HIS_REPOSITORY _LOCATION_INVENTORY_HIS;
    	public Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_HIS_REPOSITORY LOCATION_INVENTORY_HIS 
    	{ 
    		get
    		{
    			if (_LOCATION_INVENTORY_HIS == null)
    				_LOCATION_INVENTORY_HIS = new Apps.Repository.SCV.LOCATION.LOCATION_INVENTORY_HIS_REPOSITORY();
    			return _LOCATION_INVENTORY_HIS;
    		}
    	}
    
    	Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_TEMP_REPOSITORY _LOCATION_INVENTORY_TEMP;
    	public Apps.IRepository.SCV.LOCATION.ILOCATION_INVENTORY_TEMP_REPOSITORY LOCATION_INVENTORY_TEMP 
    	{ 
    		get
    		{
    			if (_LOCATION_INVENTORY_TEMP == null)
    				_LOCATION_INVENTORY_TEMP = new Apps.Repository.SCV.LOCATION.LOCATION_INVENTORY_TEMP_REPOSITORY();
    			return _LOCATION_INVENTORY_TEMP;
    		}
    	}
    
    	Apps.IRepository.SCV.Sys.IMESSAGE_REPOSITORY _MESSAGE;
    	public Apps.IRepository.SCV.Sys.IMESSAGE_REPOSITORY MESSAGE 
    	{ 
    		get
    		{
    			if (_MESSAGE == null)
    				_MESSAGE = new Apps.Repository.SCV.Sys.MESSAGE_REPOSITORY();
    			return _MESSAGE;
    		}
    	}
    
    	Apps.IRepository.SCV.MESSAGE.IMESSAGE_ROUTE_REPOSITORY _MESSAGE_ROUTE;
    	public Apps.IRepository.SCV.MESSAGE.IMESSAGE_ROUTE_REPOSITORY MESSAGE_ROUTE 
    	{ 
    		get
    		{
    			if (_MESSAGE_ROUTE == null)
    				_MESSAGE_ROUTE = new Apps.Repository.SCV.MESSAGE.MESSAGE_ROUTE_REPOSITORY();
    			return _MESSAGE_ROUTE;
    		}
    	}
    
    	Apps.IRepository.SCV.PT.IPT_QTY_REPOSITORY _PT_QTY;
    	public Apps.IRepository.SCV.PT.IPT_QTY_REPOSITORY PT_QTY 
    	{ 
    		get
    		{
    			if (_PT_QTY == null)
    				_PT_QTY = new Apps.Repository.SCV.PT.PT_QTY_REPOSITORY();
    			return _PT_QTY;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIPT.IRECEIPT_HISTORY_REPOSITORY _RECEIPT_HISTORY;
    	public Apps.IRepository.SCV.RECEIPT.IRECEIPT_HISTORY_REPOSITORY RECEIPT_HISTORY 
    	{ 
    		get
    		{
    			if (_RECEIPT_HISTORY == null)
    				_RECEIPT_HISTORY = new Apps.Repository.SCV.RECEIPT.RECEIPT_HISTORY_REPOSITORY();
    			return _RECEIPT_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.RECEIVING.IRECEIVING_CART_REPOSITORY _RECEIVING_CART;
    	public Apps.IRepository.SCV.RECEIVING.IRECEIVING_CART_REPOSITORY RECEIVING_CART 
    	{ 
    		get
    		{
    			if (_RECEIVING_CART == null)
    				_RECEIVING_CART = new Apps.Repository.SCV.RECEIVING.RECEIVING_CART_REPOSITORY();
    			return _RECEIVING_CART;
    		}
    	}
    
    	Apps.IRepository.SCV.SECURITY.ISECURITY_FUNCTION_bak_REPOSITORY _SECURITY_FUNCTION_bak;
    	public Apps.IRepository.SCV.SECURITY.ISECURITY_FUNCTION_bak_REPOSITORY SECURITY_FUNCTION_bak 
    	{ 
    		get
    		{
    			if (_SECURITY_FUNCTION_bak == null)
    				_SECURITY_FUNCTION_bak = new Apps.Repository.SCV.SECURITY.SECURITY_FUNCTION_bak_REPOSITORY();
    			return _SECURITY_FUNCTION_bak;
    		}
    	}
    
    	Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HISTORY_REPOSITORY _SHIPMENT_HISTORY;
    	public Apps.IRepository.SCV.SHIPMENT.ISHIPMENT_HISTORY_REPOSITORY SHIPMENT_HISTORY 
    	{ 
    		get
    		{
    			if (_SHIPMENT_HISTORY == null)
    				_SHIPMENT_HISTORY = new Apps.Repository.SCV.SHIPMENT.SHIPMENT_HISTORY_REPOSITORY();
    			return _SHIPMENT_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.test.Itest_LOC_V_REPOSITORY _test_LOC_V;
    	public Apps.IRepository.SCV.test.Itest_LOC_V_REPOSITORY test_LOC_V 
    	{ 
    		get
    		{
    			if (_test_LOC_V == null)
    				_test_LOC_V = new Apps.Repository.SCV.test.test_LOC_V_REPOSITORY();
    			return _test_LOC_V;
    		}
    	}
    
    	Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_HISTORY_REPOSITORY _UPLOAD_SHIPMENT_HISTORY;
    	public Apps.IRepository.SCV.UPLOAD.IUPLOAD_SHIPMENT_HISTORY_REPOSITORY UPLOAD_SHIPMENT_HISTORY 
    	{ 
    		get
    		{
    			if (_UPLOAD_SHIPMENT_HISTORY == null)
    				_UPLOAD_SHIPMENT_HISTORY = new Apps.Repository.SCV.UPLOAD.UPLOAD_SHIPMENT_HISTORY_REPOSITORY();
    			return _UPLOAD_SHIPMENT_HISTORY;
    		}
    	}
    
    	Apps.IRepository.SCV.USER.IUSER_ADDRESS_CARRIER_AUTH_REPOSITORY _USER_ADDRESS_CARRIER_AUTH;
    	public Apps.IRepository.SCV.USER.IUSER_ADDRESS_CARRIER_AUTH_REPOSITORY USER_ADDRESS_CARRIER_AUTH 
    	{ 
    		get
    		{
    			if (_USER_ADDRESS_CARRIER_AUTH == null)
    				_USER_ADDRESS_CARRIER_AUTH = new Apps.Repository.SCV.USER.USER_ADDRESS_CARRIER_AUTH_REPOSITORY();
    			return _USER_ADDRESS_CARRIER_AUTH;
    		}
    	}
    
    	Apps.IRepository.SCV.WAREHOUSE.IWAREHOUSE_ISSUE_REPOSITORY _WAREHOUSE_ISSUE;
    	public Apps.IRepository.SCV.WAREHOUSE.IWAREHOUSE_ISSUE_REPOSITORY WAREHOUSE_ISSUE 
    	{ 
    		get
    		{
    			if (_WAREHOUSE_ISSUE == null)
    				_WAREHOUSE_ISSUE = new Apps.Repository.SCV.WAREHOUSE.WAREHOUSE_ISSUE_REPOSITORY();
    			return _WAREHOUSE_ISSUE;
    		}
    	}
    
    }
}
