//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.IRepository.SCV.WAYBILL;
using System;
namespace Apps.Repository.SCV.WAYBILL
{
	public partial class WAYBILL_INFO_REPOSITORY:SCVBaseRepository<Apps.Models.WAYBILL_INFO>,IWAYBILL_INFO_REPOSITORY
	{
		
	}
}
