//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.TASK
{
	public class Virtual_TASK_PREF_USER_AUTH_MODEL
	{
			public virtual decimal INTERNAL_NUM { get; set; }
			public virtual string PREFERENCE_NAME { get; set; }
			public virtual string USER_ID { get; set; }
			public virtual string TASK_METHOD { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
		}
}
