//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.AR
{
	public class Virtual_AR_UPLOAD_INVENTORY_TRANS_MODEL
	{
			public virtual decimal INTERFACE_RECORD_ID { get; set; }
			public virtual string INTERFACE_ACTION_CODE { get; set; }
			public virtual string INTERFACE_CONDITION { get; set; }
			public virtual string PROCESS_STAMP { get; set; }
			public virtual string INTERFACE_ERROR { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string LOCATION { get; set; }
			public virtual string ATTRIBUTE1 { get; set; }
			public virtual string ATTRIBUTE2 { get; set; }
			public virtual string ATTRIBUTE3 { get; set; }
			public virtual string ATTRIBUTE4 { get; set; }
			public virtual string ATTRIBUTE5 { get; set; }
			public virtual string ATTRIBUTE6 { get; set; }
			public virtual string ATTRIBUTE7 { get; set; }
			public virtual string ATTRIBUTE8 { get; set; }
			public virtual Nullable<decimal> QUANTITY { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual string REFERENCE_ID { get; set; }
			public virtual Nullable<decimal> REFERENCE_LINE_NUM { get; set; }
			public virtual string REFERENCE_TYPE { get; set; }
			public virtual string REFERENCE_NUM_TYPE { get; set; }
			public virtual string TRANSACTION_TYPE { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string ZONE { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
			public virtual Nullable<System.DateTime> ACTIVITY_DATE_TIME { get; set; }
			public virtual string DIRECTION { get; set; }
			public virtual string LPN { get; set; }
			public virtual string BEFORE_INVENTORY_STS { get; set; }
			public virtual string AFTER_INVENTORY_STS { get; set; }
		}
}
