//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.AR
{
	public class Virtual_AR_UPLOAD_LOCATION_INVENTORY_MODEL
	{
			public virtual decimal INTERNAL_LOCATION_INV { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string LOCATION { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string ITEM_DESC { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string PERMANENT { get; set; }
			public virtual Nullable<decimal> ATTRIBUTE_NUM { get; set; }
			public virtual decimal ON_HAND_QTY { get; set; }
			public virtual decimal IN_TRANSIT_QTY { get; set; }
			public virtual decimal ALLOCATED_QTY { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual string INVENTORY_STS { get; set; }
			public virtual Nullable<System.DateTime> AGING_DATE { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
			public virtual string LPN { get; set; }
			public virtual string PARENT_LPN { get; set; }
			public virtual string ATTRIBUTE1 { get; set; }
			public virtual string ATTRIBUTE2 { get; set; }
			public virtual string ATTRIBUTE3 { get; set; }
			public virtual string ATTRIBUTE4 { get; set; }
			public virtual string ATTRIBUTE5 { get; set; }
			public virtual string ATTRIBUTE6 { get; set; }
			public virtual string ATTRIBUTE7 { get; set; }
			public virtual string ATTRIBUTE8 { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
		}
}
