//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.EX
{
	public class Virtual_EX_MENU_MODEL
	{
			public virtual decimal INTERNAL_NUM { get; set; }
			public virtual string MENU_TEXT { get; set; }
			public virtual Nullable<decimal> PARENT { get; set; }
			public virtual Nullable<decimal> SEQUENCE { get; set; }
			public virtual string ASSEMBLY { get; set; }
			public virtual string NAMESPACE { get; set; }
			public virtual string CLASS { get; set; }
			public virtual string INIT_METHOD { get; set; }
			public virtual string ACTIVE { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
		}
}
