//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.PURCHASE
{
	public class Virtual_PURCHASE_ORDER_HEADER_MODEL
	{
			public virtual decimal INTERNAL_PURCHASE_ORDER_NUM { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string PURCHASE_ORDER_ID { get; set; }
			public virtual string PURCHASE_ORDER_TYPE { get; set; }
			public virtual Nullable<System.DateTime> CLOSE_DATE { get; set; }
			public virtual Nullable<decimal> PRIORITY { get; set; }
			public virtual Nullable<decimal> STATUS { get; set; }
			public virtual string ERP_ORDER_ID { get; set; }
			public virtual string SHIP_FROM { get; set; }
			public virtual string SHIP_FROM_ADDRESS1 { get; set; }
			public virtual string SHIP_FROM_ADDRESS2 { get; set; }
			public virtual string SHIP_FROM_CITY { get; set; }
			public virtual string SHIP_FROM_STATE { get; set; }
			public virtual string SHIP_FROM_COUNTRY { get; set; }
			public virtual string SHIP_FROM_POSTAL_CODE { get; set; }
			public virtual string SHIP_FROM_NAME { get; set; }
			public virtual string SHIP_FROM_ATTENTION_TO { get; set; }
			public virtual string SHIP_FROM_EMAIL_ADDRESS { get; set; }
			public virtual string SHIP_FROM_PHONE_NUM { get; set; }
			public virtual string SHIP_FROM_FAX_NUM { get; set; }
			public virtual Nullable<System.DateTime> SCHEDULED_ARRIVE_DATE { get; set; }
			public virtual Nullable<System.DateTime> ACTUAL_ARRIVE_DATE { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
		}
}
