//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.REPLENISHMENT
{
	public class Virtual_REPLENISHMENT_MASTER_MODEL
	{
			public virtual decimal INTERNAL_NUM { get; set; }
			public virtual string MASTER_NAME { get; set; }
			public virtual string DESCRIPTION { get; set; }
			public virtual string ITEM_SEL { get; set; }
			public virtual string LOCATION_SEL { get; set; }
			public virtual string ALLOCATION_RULE { get; set; }
			public virtual string LOCATING_RULE { get; set; }
			public virtual string REPLENISH_MODE { get; set; }
			public virtual string REPLENISH_UM { get; set; }
			public virtual string STRATEGY { get; set; }
			public virtual string IN_PROCESS { get; set; }
			public virtual Nullable<decimal> PRIORITY { get; set; }
			public virtual Nullable<decimal> MAX_ITEMS { get; set; }
			public virtual Nullable<decimal> MAX_QTY { get; set; }
			public virtual Nullable<decimal> MAX_LINES { get; set; }
			public virtual Nullable<decimal> MAX_WEIGHT { get; set; }
			public virtual Nullable<decimal> MAX_VOLUME { get; set; }
			public virtual string ACTIVE { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
		}
}
