//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.FILTER
{
	public class Virtual_FILTER_ORDER_BY_MODEL
	{
			public virtual decimal SEQUENCE { get; set; }
			public virtual string RECORD_TYPE { get; set; }
			public virtual string FILTER_NAME { get; set; }
			public virtual string ATTRIBUTE { get; set; }
			public virtual string ASC_DESC { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
			public virtual string CREATE_BREAK { get; set; }
		}
}
