//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.PURCHASE
{
	public class Virtual_PURCHASE_ORDER_DETAIL_MODEL
	{
			public virtual decimal INTERNAL_PURCHASE_ORDER_LINE_NUM { get; set; }
			public virtual decimal INTERNAL_PURCHASE_ORDER_NUM { get; set; }
			public virtual string PURCHASE_ORDER_ID { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string ITEM_DESC { get; set; }
			public virtual string ITEM_CLASS { get; set; }
			public virtual string ATTRIBUTE_TRACK { get; set; }
			public virtual string ATTRIBUTE_NUM { get; set; }
			public virtual string ATTRIBUTE1 { get; set; }
			public virtual string ATTRIBUTE2 { get; set; }
			public virtual string ATTRIBUTE3 { get; set; }
			public virtual string ATTRIBUTE4 { get; set; }
			public virtual string ATTRIBUTE5 { get; set; }
			public virtual string ATTRIBUTE6 { get; set; }
			public virtual string ATTRIBUTE7 { get; set; }
			public virtual string ATTRIBUTE8 { get; set; }
			public virtual Nullable<decimal> TOTAL_QTY { get; set; }
			public virtual Nullable<decimal> OPEN_QTY { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual string ERP_ORDER_ID { get; set; }
			public virtual string ERP_ORDER_LINE_NUM { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
			public virtual string INVENTORY_STS { get; set; }
		}
}
