//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.LOCATION
{
	public class Virtual_LOCATION_SELECTION_MODEL
	{
			public virtual decimal OBJECT_ID { get; set; }
			public virtual string LOC_SEL_ID { get; set; }
			public virtual string LOC_SEL_DESC { get; set; }
			public virtual string SQL_STATEMENT { get; set; }
			public virtual string LOC_SEL_TYPE { get; set; }
		}
}
