//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.STATISTICS
{
	public class Virtual_STATISTICS_REPORT_MODEL
	{
			public virtual System.DateTime ACTIVITY_DATE { get; set; }
			public virtual Nullable<decimal> IN_CONTAINERS { get; set; }
			public virtual Nullable<decimal> OUT_CONTAINERS { get; set; }
			public virtual Nullable<decimal> IN_ORDERS { get; set; }
			public virtual Nullable<decimal> OUT_ORDERS { get; set; }
			public virtual Nullable<decimal> IN_QTY { get; set; }
			public virtual Nullable<decimal> OUT_QTY { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual Nullable<System.DateTime> DATE_TIME_STAMP { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual decimal INTERNAL_NUM { get; set; }
		}
}
