//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.BOM
{
	public class Virtual_BOM_HEADER_MODEL
	{
			public virtual decimal INTERNAL_NUM { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string ITEM_DESC { get; set; }
			public virtual decimal REVISION_NUM { get; set; }
			public virtual string BUILD_INSTRUCTIONS { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual string ACTIVE { get; set; }
			public virtual string BUILD_LOC { get; set; }
			public virtual Nullable<System.DateTime> VALID_FROM_DATE { get; set; }
			public virtual Nullable<System.DateTime> VALID_END_DATE { get; set; }
			public virtual Nullable<decimal> PRIORITY { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
			public virtual string PROCESS_STAMP { get; set; }
			public virtual string CREATED_USER { get; set; }
			public virtual Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
			public virtual string LAST_MODIFIED_USER { get; set; }
			public virtual Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
		}
}
