//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.CUSTOM
{
	public class Virtual_CUSTOM_RESOURCE_MODEL
	{
			public virtual string RESOURCE_KEY { get; set; }
			public virtual string LOCALE { get; set; }
			public virtual string RESOURCE_TYPE { get; set; }
			public virtual string RESOURCE_TEXT { get; set; }
		}
}
