//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.AR
{
	public class Virtual_AR_PROCESS_HISTORY_MODEL
	{
			public virtual decimal INTERNAL_ID { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string PROCESS_TYPE { get; set; }
			public virtual string CONDITION { get; set; }
			public virtual string IDENTIFIER1 { get; set; }
			public virtual string IDENTIFIER2 { get; set; }
			public virtual string IDENTIFIER3 { get; set; }
			public virtual string IDENTIFIER4 { get; set; }
			public virtual string IDENTIFIER5 { get; set; }
			public virtual string IDENTIFIER6 { get; set; }
			public virtual string IDENTIFIER7 { get; set; }
			public virtual string IDENTIFIER8 { get; set; }
			public virtual string MESSAGE { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
		}
}
