//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.GSP
{
	public class Virtual_GSP_CODE_MODEL
	{
			public virtual decimal INTERNAL_NUM { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string GSP_CODE1 { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual Nullable<decimal> INTERNAL_SHIPMENT_NUM { get; set; }
			public virtual Nullable<decimal> INTERNAL_SHIPMENT_LINE_NUM { get; set; }
			public virtual string SHIPMENT_ID { get; set; }
			public virtual string SHIP_CONT_ID { get; set; }
			public virtual Nullable<decimal> PARENT_SHIP_CONT_NUM { get; set; }
			public virtual Nullable<decimal> SHIP_CONT_NUM { get; set; }
			public virtual Nullable<decimal> INTERNAL_RECEIPT_NUM { get; set; }
			public virtual Nullable<decimal> INTERNAL_RECEIPT_LINE_NUM { get; set; }
			public virtual string RECEIPT_ID { get; set; }
			public virtual string RECV_CONT_ID { get; set; }
			public virtual Nullable<decimal> PARENT_RECV_CONT_NUM { get; set; }
			public virtual Nullable<decimal> RECV_CONT_NUM { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual Nullable<decimal> USER_DEF7 { get; set; }
			public virtual Nullable<decimal> USER_DEF8 { get; set; }
			public virtual Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
			public virtual string CREATED_USER { get; set; }
			public virtual Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
			public virtual string LAST_MODIFIED_USER { get; set; }
			public virtual string PROCESS_STAMP { get; set; }
		}
}
