//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.TASK
{
	public class Virtual_TASK_PREFERENCE_MODEL
	{
			public virtual decimal INTERNAL_PREF_NUM { get; set; }
			public virtual string PREFERENCE_NAME { get; set; }
			public virtual string TASK_TYPES { get; set; }
			public virtual string ZONES { get; set; }
			public virtual string TASK_INIT_METHOD { get; set; }
			public virtual string FROM_ASSIGN_METHOD { get; set; }
			public virtual string TO_ASSIGN_METHOD { get; set; }
			public virtual string PICK_METHOD { get; set; }
			public virtual string RF_SUCCESS_ENABLED { get; set; }
			public virtual string RF_SUCCESS_FIELD { get; set; }
			public virtual string RF_SUCCESS_MESSAGE { get; set; }
			public virtual string PUT_METHOD { get; set; }
			public virtual string DEFAULT_LP_AS_SHIP_CONT { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual Nullable<decimal> USER_DEF7 { get; set; }
			public virtual Nullable<decimal> USER_DEF8 { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
			public virtual string MULTI_PICK_METHOD { get; set; }
			public virtual string VERIFY_CART_POS { get; set; }
			public virtual string TASK_INIT_BY { get; set; }
			public virtual string ALLOW_PARTIAL { get; set; }
			public virtual string PICK_DROP_LOC { get; set; }
			public virtual string TASK_METHOD { get; set; }
			public virtual string DISPLAY_ITEM_INFO { get; set; }
		}
}
