//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.CYCLE
{
	public class Virtual_CYCLE_COUNT_DETAIL_MODEL
	{
			public virtual decimal INTERNAL_COUNT_NUM { get; set; }
			public virtual decimal INTERNAL_CYCLE_COUNT_NUM { get; set; }
			public virtual Nullable<decimal> ROUND { get; set; }
			public virtual Nullable<decimal> GROUP_NUM { get; set; }
			public virtual Nullable<decimal> GROUP_INDEX { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string LOCATION { get; set; }
			public virtual string PARENT_LPN { get; set; }
			public virtual string LPN { get; set; }
			public virtual string ITEM { get; set; }
			public virtual string ITEM_DESC { get; set; }
			public virtual string COMPANY { get; set; }
			public virtual string INVENTORY_STS { get; set; }
			public virtual Nullable<decimal> SYSTEM_QTY { get; set; }
			public virtual Nullable<decimal> COUNTED_QTY { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual Nullable<decimal> ATTRIBUTE_NUM { get; set; }
			public virtual string ATTRIBUTE1 { get; set; }
			public virtual string ATTRIBUTE2 { get; set; }
			public virtual string ATTRIBUTE3 { get; set; }
			public virtual string ATTRIBUTE4 { get; set; }
			public virtual string ATTRIBUTE5 { get; set; }
			public virtual string ATTRIBUTE6 { get; set; }
			public virtual string ATTRIBUTE7 { get; set; }
			public virtual string ATTRIBUTE8 { get; set; }
			public virtual string COUNT_ATTRIBUTE { get; set; }
			public virtual Nullable<System.DateTime> COUNTED_DATE_TIME { get; set; }
			public virtual string COUNTED_BY_USER { get; set; }
			public virtual string ASSIGNED_USER { get; set; }
			public virtual Nullable<System.DateTime> ASSIGNED_DATE_TIME { get; set; }
			public virtual string COMPLETED_USER { get; set; }
			public virtual Nullable<System.DateTime> COMPLETED_DATE_TIME { get; set; }
			public virtual string CONDITION { get; set; }
			public virtual string CREATED_USER { get; set; }
			public virtual Nullable<System.DateTime> CREATED_DATE_TIME { get; set; }
			public virtual string LAST_MODIFIED_USER { get; set; }
			public virtual Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
		}
}
