//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.CYCLE
{
	public class Virtual_CYCLE_COUNT_HEADER_MODEL
	{
			public virtual decimal INTERNAL_CYCLE_COUNT_NUM { get; set; }
			public virtual Nullable<decimal> ORIGINAL_CYCLE_COUNT_NUM { get; set; }
			public virtual Nullable<decimal> ROUND { get; set; }
			public virtual string MASTER_ID { get; set; }
			public virtual string COUNT_TYPE { get; set; }
			public virtual string CONDITION { get; set; }
			public virtual string COUNT_ATTRIBUTE { get; set; }
			public virtual string REFERENCE_ID { get; set; }
			public virtual string REMARK { get; set; }
			public virtual Nullable<decimal> TOTAL_LOCS { get; set; }
			public virtual Nullable<decimal> TOTAL_ITEMS { get; set; }
			public virtual string INVENTORY_STSES { get; set; }
			public virtual string ITEMS { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
			public virtual string CREATED_USER { get; set; }
			public virtual System.DateTime CREATED_DATE_TIME { get; set; }
			public virtual string RELEASED_USER { get; set; }
			public virtual Nullable<System.DateTime> RELEASED_DATE_TIME { get; set; }
			public virtual string CLOSED_USER { get; set; }
			public virtual Nullable<System.DateTime> CLOSED_DATE_TIME { get; set; }
			public virtual string LAST_MODIFIED_USER { get; set; }
			public virtual Nullable<System.DateTime> LAST_MODIFIED_DATE_TIME { get; set; }
		}
}
