//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.SCV.Sys
{
	public class Virtual_WAVE_MODEL
	{
			public virtual decimal INTERNAL_WAVE_NUM { get; set; }
			public virtual string WAREHOUSE { get; set; }
			public virtual string WAVE_NAME { get; set; }
			public virtual string WAVE_MASTER { get; set; }
			public virtual decimal STATUS { get; set; }
			public virtual string CURRENT_WAVE_STEP { get; set; }
			public virtual string LAST_WAVE_STEP { get; set; }
			public virtual Nullable<decimal> TOTAL_SHIPMENTS { get; set; }
			public virtual Nullable<decimal> TOTAL_LINES { get; set; }
			public virtual Nullable<decimal> TOTAL_QTY { get; set; }
			public virtual string QUANTITY_UM { get; set; }
			public virtual Nullable<System.DateTime> WAVE_DATE_TIME_STARTED { get; set; }
			public virtual Nullable<System.DateTime> WAVE_DATE_TIME_ENDED { get; set; }
			public virtual string USER_DEF1 { get; set; }
			public virtual string USER_DEF2 { get; set; }
			public virtual string USER_DEF3 { get; set; }
			public virtual string USER_DEF4 { get; set; }
			public virtual string USER_DEF5 { get; set; }
			public virtual string USER_DEF6 { get; set; }
			public virtual string USER_DEF7 { get; set; }
			public virtual string USER_DEF8 { get; set; }
			public virtual string USER_STAMP { get; set; }
			public virtual System.DateTime DATE_TIME_STAMP { get; set; }
			public virtual string WAVE_MODE { get; set; }
			public virtual string ERROR_MESSAGE { get; set; }
			public virtual string LOCKED { get; set; }
			public virtual string REPLENISHMENT_REQD { get; set; }
			public virtual string PROCESS_STAMP { get; set; }
			public virtual string MESSAGE_ID { get; set; }
			public virtual string RUN_USER { get; set; }
			public virtual string RELESAE_USER { get; set; }
			public virtual Nullable<System.DateTime> RELESAE_DATE_TIME { get; set; }
			public virtual string PRINT { get; set; }
		}
}
